/*
 * Este Software tem Objetivo Educacional
 * Para fins de aprendizagem e avaliacao na
 * Na Disciplina de Programa��o Orientada a Objetos - Avan�ada
 *  do Curso de Analise de Sistemas da Fatec - Ipiranga
 * Ano 2016 - Janeiro a Junho 
 * Aluno Decio Antonio de Carvalho  * 
 */
package view;

import java.util.List;
import model.Passagem;

/**
 *
 * @author deciodecarvalho
 */
public class FrameListaPassagem extends javax.swing.JFrame {

    public FrameListaPassagem() {
        initComponents();
    }

    /**
     * Creates new form FrameListaPassagem
     */
    public FrameListaPassagem(List<Passagem> lista) {
        initComponents();
        setLocation(50,50);
        carregarLista(lista);
       
        
    }
    
    private void carregarLista(List<Passagem> listaPassagens){
       String newline = System.getProperty("line.separator");
       String resultado = "";
       for (Passagem p : listaPassagens){
         resultado += "\tNum:  " + p.getNumeroPassagem() + "\n"
         +"\tNome Passageiro: "+ p.getNomePassageiro() + " RG: "+ p.getRgPassageiro()+"\n"
         
         +"\tData: "+p.getPartidaData() + "\t - "+"\tHora: "+ 
         p.getPartidaHora() + "\n"+ "\tAeroporto Partida: " + p.getPartidaAeroporto() + "\n"+ "\tAeroporto Destino: " + p.getChegadaAeroporto()+"\n";
         
         resultado += newline;
       }
       txtPassagem.setText(resultado);
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPassagem = new javax.swing.JTextArea();
        PainelRelatoriosPassagem = new javax.swing.JPanel();
        btnSairPassagemRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPassagem.setColumns(20);
        txtPassagem.setRows(5);
        jScrollPane1.setViewportView(txtPassagem);

        btnSairPassagemRelatorio.setBackground(new java.awt.Color(204, 204, 204));
        btnSairPassagemRelatorio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSairPassagemRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairPassagemRelatorio.setText("Voltar");
        btnSairPassagemRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSairPassagemRelatorio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSairPassagemRelatorio.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairPassagemRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairPassagemRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelRelatoriosPassagemLayout = new javax.swing.GroupLayout(PainelRelatoriosPassagem);
        PainelRelatoriosPassagem.setLayout(PainelRelatoriosPassagemLayout);
        PainelRelatoriosPassagemLayout.setHorizontalGroup(
            PainelRelatoriosPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelatoriosPassagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSairPassagemRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelRelatoriosPassagemLayout.setVerticalGroup(
            PainelRelatoriosPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRelatoriosPassagemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSairPassagemRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                    .addComponent(PainelRelatoriosPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelRelatoriosPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairPassagemRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairPassagemRelatorioActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairPassagemRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameListaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameListaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameListaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameListaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameListaPassagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelRelatoriosPassagem;
    private javax.swing.JButton btnSairPassagemRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPassagem;
    // End of variables declaration//GEN-END:variables
}
