/*
 * Este Software tem Objetivo Educacional
 * Para fins de aprendizagem e avaliacao na
 * Na Disciplina de Programacao Orientada a Objetos - Avancada
 *  do Curso de Analise de Sistemas da Fatec - Ipiranga
 * Ano 2016 - Janeiro a Junho 
 * Aluno Decio Antonio de Carvalho  * 
 */
package view;

import Control.AeronaveCtrl;
import Control.ValidaCampos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Aeronave;

/**
 *
 * @author deciodecarvalho
 */
public class TelaAeronave extends javax.swing.JInternalFrame {

    public static ArrayList<model.Aeronave> arrayAero;
    public static boolean temAero;
    private static String oldPrefixo; //utilizar na alteração inclusive do prefixo

    /**
     * Instanciando objeto Aeronave
     */
    /**
     * Creates new form TelaAeronave
     */
    public TelaAeronave() {

        initComponents();
        if (!temAero) {
            arrayAero = new ArrayList<>();
            temAero = true;
        }
        //Status dos botões 
        btnAlterarAeronave.setEnabled(false);
        btnSalvarAeronave.setEnabled(true);
        btnEditarAeronave.setEnabled(false);
        btnExcluirAeronave.setEnabled(false);
        //controle da mensagem true se encontrou e false se não
        //inicalizando valores de variáveis de tela
        tftClasseEconomica.setText("0");
        tftClasseEmpresarial.setText("0");
        tftPrimeiraClasse.setText("0");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelClienteTitulo = new javax.swing.JPanel();
        lblTituloTelaPassageiro = new javax.swing.JLabel();
        lblTelaAeronave = new javax.swing.JLabel();
        JPanelClienteBotoes = new javax.swing.JPanel();
        btnSalvarAeronave = new javax.swing.JButton();
        btnPesquisarAeronave = new javax.swing.JButton();
        btnSairAeronave = new javax.swing.JButton();
        btnLimparAeronave = new javax.swing.JButton();
        btnExcluirAeronave = new javax.swing.JButton();
        btnEditarAeronave = new javax.swing.JButton();
        btnAlterarAeronave = new javax.swing.JButton();
        PainelAeronaveVoo = new javax.swing.JPanel();
        lblModeloAeronave = new javax.swing.JLabel();
        tctModeloAeronave = new javax.swing.JTextField();
        lblPrefixoAeronave = new javax.swing.JLabel();
        lblFabricanteAeronave = new javax.swing.JLabel();
        tctFabricanteAeronave = new javax.swing.JTextField();
        lblClasse1 = new javax.swing.JLabel();
        tftClasseEconomica = new javax.swing.JFormattedTextField();
        lblClasse2 = new javax.swing.JLabel();
        tftClasseEmpresarial = new javax.swing.JFormattedTextField();
        lblClasse3 = new javax.swing.JLabel();
        tftPrimeiraClasse = new javax.swing.JFormattedTextField();
        tftPrefixoAeronave = new javax.swing.JTextField();
        lblNumAssentosEconomica = new javax.swing.JLabel();
        lblNumAssentosEmpresarial = new javax.swing.JLabel();
        lblNumAssentosPrimeira = new javax.swing.JLabel();
        tctOperadoraAeronave = new javax.swing.JTextField();
        lblOperadoraAeronave = new javax.swing.JLabel();
        tftClasseEconomicaColunas = new javax.swing.JFormattedTextField();
        tftClasseEmpresarialColunas = new javax.swing.JFormattedTextField();
        tftPrimeiraClasseColunas = new javax.swing.JFormattedTextField();
        lblNumAssentosEconomicaCol = new javax.swing.JLabel();
        lblNumAssentosEmpresarialCol = new javax.swing.JLabel();
        lblNumAssentosPrimeiraCol = new javax.swing.JLabel();
        lblClasse4 = new javax.swing.JLabel();
        tftLayoutAssentos = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JPanelClienteTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTituloTelaPassageiro.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTituloTelaPassageiro.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloTelaPassageiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTelaPassageiro.setText("Aeronave");

        lblTelaAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voo 40x40.png"))); // NOI18N

        javax.swing.GroupLayout JPanelClienteTituloLayout = new javax.swing.GroupLayout(JPanelClienteTitulo);
        JPanelClienteTitulo.setLayout(JPanelClienteTituloLayout);
        JPanelClienteTituloLayout.setHorizontalGroup(
            JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteTituloLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(lblTelaAeronave)
                .addGap(31, 31, 31)
                .addComponent(lblTituloTelaPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        JPanelClienteTituloLayout.setVerticalGroup(
            JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelaAeronave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteTituloLayout.createSequentialGroup()
                        .addComponent(lblTituloTelaPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        JPanelClienteBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalvarAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvarAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSalvarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarGreen_1.png"))); // NOI18N
        btnSalvarAeronave.setText("Salvar");
        btnSalvarAeronave.setToolTipText("Salvar Alterações");
        btnSalvarAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalvarAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvarAeronave.setIconTextGap(2);
        btnSalvarAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSalvarAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSalvarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAeronaveActionPerformed(evt);
            }
        });

        btnPesquisarAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnPesquisarAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnPesquisarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lupaVermelha 40x40.png"))); // NOI18N
        btnPesquisarAeronave.setText("Pesquisar");
        btnPesquisarAeronave.setToolTipText("Entre com prefixo da Aeronave para pesquisar.");
        btnPesquisarAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPesquisarAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPesquisarAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPesquisarAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnPesquisarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarAeronaveActionPerformed(evt);
            }
        });

        btnSairAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnSairAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSairAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairAeronave.setText("Voltar");
        btnSairAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSairAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSairAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSairAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairAeronaveActionPerformed(evt);
            }
        });

        btnLimparAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLimparAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/oopsRed.png"))); // NOI18N
        btnLimparAeronave.setText("Limpar");
        btnLimparAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimparAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLimparAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLimparAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnLimparAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparAeronaveActionPerformed(evt);
            }
        });

        btnExcluirAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnExcluirAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnExcluirAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/excluir 40x40 vermelho.png"))); // NOI18N
        btnExcluirAeronave.setText("Excluir");
        btnExcluirAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExcluirAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnExcluirAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnExcluirAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnExcluirAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAeronaveActionPerformed(evt);
            }
        });

        btnEditarAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnEditarAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEditarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inserir.png"))); // NOI18N
        btnEditarAeronave.setText("Editar");
        btnEditarAeronave.setToolTipText("Editar Alterações");
        btnEditarAeronave.setDefaultCapable(false);
        btnEditarAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditarAeronave.setIconTextGap(1);
        btnEditarAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnEditarAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnEditarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAeronaveActionPerformed(evt);
            }
        });

        btnAlterarAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnAlterarAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAlterarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarRed.png"))); // NOI18N
        btnAlterarAeronave.setText("Alterar");
        btnAlterarAeronave.setToolTipText("Alterar Dados");
        btnAlterarAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAlterarAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAlterarAeronave.setIconTextGap(0);
        btnAlterarAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAlterarAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnAlterarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarAeronaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelClienteBotoesLayout = new javax.swing.GroupLayout(JPanelClienteBotoes);
        JPanelClienteBotoes.setLayout(JPanelClienteBotoesLayout);
        JPanelClienteBotoesLayout.setHorizontalGroup(
            JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSairAeronave, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
        );
        JPanelClienteBotoesLayout.setVerticalGroup(
            JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSairAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PainelAeronaveVoo.setBorder(javax.swing.BorderFactory.createTitledBorder("Aeronave - Voo"));
        PainelAeronaveVoo.setToolTipText("");

        lblModeloAeronave.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblModeloAeronave.setForeground(new java.awt.Color(102, 102, 102));
        lblModeloAeronave.setText("Modelo:");

        tctModeloAeronave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctModeloAeronave.setForeground(new java.awt.Color(51, 51, 51));
        tctModeloAeronave.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPrefixoAeronave.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPrefixoAeronave.setForeground(new java.awt.Color(102, 102, 102));
        lblPrefixoAeronave.setText("Prefixo :");

        lblFabricanteAeronave.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblFabricanteAeronave.setForeground(new java.awt.Color(102, 102, 102));
        lblFabricanteAeronave.setText("Fabricante: ");

        tctFabricanteAeronave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctFabricanteAeronave.setForeground(new java.awt.Color(51, 51, 51));
        tctFabricanteAeronave.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblClasse1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblClasse1.setForeground(new java.awt.Color(102, 102, 102));
        lblClasse1.setText("Classe Economica: ");

        tftClasseEconomica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tftClasseEconomica.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftClasseEconomica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftClasseEconomicaActionPerformed(evt);
            }
        });

        lblClasse2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblClasse2.setForeground(new java.awt.Color(102, 102, 102));
        lblClasse2.setText("Classe Empresarial:  ");

        tftClasseEmpresarial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tftClasseEmpresarial.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftClasseEmpresarial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftClasseEmpresarialActionPerformed(evt);
            }
        });

        lblClasse3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblClasse3.setForeground(new java.awt.Color(102, 102, 102));
        lblClasse3.setText("Classe Primeira: ");

        tftPrimeiraClasse.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tftPrimeiraClasse.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftPrimeiraClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftPrimeiraClasseActionPerformed(evt);
            }
        });

        tftPrefixoAeronave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftPrefixoAeronave.setForeground(new java.awt.Color(51, 51, 51));
        tftPrefixoAeronave.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNumAssentosEconomica.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumAssentosEconomica.setForeground(new java.awt.Color(102, 102, 102));
        lblNumAssentosEconomica.setText("número de Assentos.");

        lblNumAssentosEmpresarial.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumAssentosEmpresarial.setForeground(new java.awt.Color(102, 102, 102));
        lblNumAssentosEmpresarial.setText("número de Assentos.");

        lblNumAssentosPrimeira.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumAssentosPrimeira.setForeground(new java.awt.Color(102, 102, 102));
        lblNumAssentosPrimeira.setText("número de Assentos.");

        tctOperadoraAeronave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctOperadoraAeronave.setForeground(new java.awt.Color(51, 51, 51));
        tctOperadoraAeronave.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblOperadoraAeronave.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblOperadoraAeronave.setForeground(new java.awt.Color(102, 102, 102));
        lblOperadoraAeronave.setText("Operadora:");

        tftClasseEconomicaColunas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tftClasseEconomicaColunas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftClasseEconomicaColunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftClasseEconomicaColunasActionPerformed(evt);
            }
        });

        tftClasseEmpresarialColunas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tftClasseEmpresarialColunas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftClasseEmpresarialColunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftClasseEmpresarialColunasActionPerformed(evt);
            }
        });

        tftPrimeiraClasseColunas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tftPrimeiraClasseColunas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftPrimeiraClasseColunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftPrimeiraClasseColunasActionPerformed(evt);
            }
        });

        lblNumAssentosEconomicaCol.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumAssentosEconomicaCol.setForeground(new java.awt.Color(102, 102, 102));
        lblNumAssentosEconomicaCol.setText("Quantidade de colunas de assentos");

        lblNumAssentosEmpresarialCol.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumAssentosEmpresarialCol.setForeground(new java.awt.Color(102, 102, 102));
        lblNumAssentosEmpresarialCol.setText("Quantidade de colunas de assentos");

        lblNumAssentosPrimeiraCol.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumAssentosPrimeiraCol.setForeground(new java.awt.Color(102, 102, 102));
        lblNumAssentosPrimeiraCol.setText("Quantidade de colunas de assentos");

        lblClasse4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblClasse4.setForeground(new java.awt.Color(102, 102, 102));
        lblClasse4.setText("Layout assentos:");

        tftLayoutAssentos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tftLayoutAssentos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftLayoutAssentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftLayoutAssentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelAeronaveVooLayout = new javax.swing.GroupLayout(PainelAeronaveVoo);
        PainelAeronaveVoo.setLayout(PainelAeronaveVooLayout);
        PainelAeronaveVooLayout.setHorizontalGroup(
            PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAeronaveVooLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelAeronaveVooLayout.createSequentialGroup()
                        .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModeloAeronave)
                            .addComponent(lblClasse1)
                            .addComponent(lblFabricanteAeronave)
                            .addComponent(lblPrefixoAeronave)
                            .addComponent(lblOperadoraAeronave))
                        .addGap(27, 27, 27)
                        .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tctModeloAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tctFabricanteAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tctOperadoraAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftPrefixoAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelAeronaveVooLayout.createSequentialGroup()
                                .addComponent(tftClasseEconomica, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNumAssentosEmpresarial)
                                .addGap(26, 26, 26)
                                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tftPrimeiraClasseColunas, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(tftClasseEmpresarialColunas, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tftClasseEconomicaColunas, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumAssentosPrimeiraCol)
                                    .addComponent(lblNumAssentosEmpresarialCol)
                                    .addComponent(lblNumAssentosEconomicaCol)))))
                    .addGroup(PainelAeronaveVooLayout.createSequentialGroup()
                        .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClasse2)
                            .addComponent(lblClasse3)
                            .addComponent(lblClasse4))
                        .addGap(18, 18, 18)
                        .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tftClasseEmpresarial, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftPrimeiraClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftLayoutAssentos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumAssentosPrimeira)
                            .addComponent(lblNumAssentosEconomica))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelAeronaveVooLayout.setVerticalGroup(
            PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAeronaveVooLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloAeronave)
                    .addComponent(tctModeloAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFabricanteAeronave)
                    .addComponent(tctFabricanteAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOperadoraAeronave)
                    .addComponent(tctOperadoraAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrefixoAeronave)
                    .addComponent(tftPrefixoAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelAeronaveVooLayout.createSequentialGroup()
                        .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClasse1)
                            .addComponent(tftClasseEconomica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumAssentosEmpresarial)
                            .addComponent(tftClasseEconomicaColunas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClasse2)
                            .addComponent(tftClasseEmpresarial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumAssentosPrimeira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClasse3)
                            .addComponent(tftPrimeiraClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumAssentosEconomica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClasse4)
                            .addComponent(tftLayoutAssentos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(PainelAeronaveVooLayout.createSequentialGroup()
                        .addComponent(lblNumAssentosEconomicaCol)
                        .addGap(18, 18, 18)
                        .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tftClasseEmpresarialColunas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumAssentosEmpresarialCol))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tftPrimeiraClasseColunas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumAssentosPrimeiraCol))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PainelAeronaveVoo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPanelClienteBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelAeronaveVoo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPanelClienteBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairAeronaveActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairAeronaveActionPerformed

    private void btnPesquisarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarAeronaveActionPerformed
        //Status dos botões 
        btnAlterarAeronave.setEnabled(false);
        btnSalvarAeronave.setEnabled(false);
        btnEditarAeronave.setEnabled(false);
        btnLimparAeronave.setEnabled(false);
        btnExcluirAeronave.setEnabled(true);
        //controle da mensagem true se encontrou e false se não
        boolean flag = false;
        String tituloMsg = "";
        String vAeronave = tftPrefixoAeronave.getText();
        AeronaveCtrl cAeronave = new AeronaveCtrl();
        Aeronave aeronave;
        aeronave = new Aeronave();

        String msg = "";

        aeronave = cAeronave.receberAeronavePrefixo(vAeronave);

        if (aeronave != null) {
            oldPrefixo = tftPrefixoAeronave.getText(); //valor a ser utilizado na alteração

            tctModeloAeronave.setText(aeronave.getModelo());
            tftPrefixoAeronave.setText(aeronave.getPrefixo());
            tftClasseEconomica.setText(aeronave.getSeatEconomyClasse() + "");
            tftClasseEmpresarial.setText(aeronave.getSeatBusinesClasse() + "");
            tftPrimeiraClasse.setText(aeronave.getSeatFirstClasse() + "");
            tctFabricanteAeronave.setText(aeronave.getFabricante());
            tctOperadoraAeronave.setText(aeronave.getOperadora());
            //desabilitar edição
            desabilitarDadosAeronave();
            btnEditarAeronave.setEnabled(true);
            tituloMsg = "Pesquisar Aeronave";
            msg = msg + "Aeronave Localizada na base de dados!!!, Prefixo: " + vAeronave + "\n";

            flag = true;
        }//fim do if
        else {
            tituloMsg = "Pesquisar Aeronave";
            msg = msg + "Aeronave não encontrada!!! " + vAeronave + " "
                    + ", Por favor entre com outro prefixo\n";

            limparAeronave();
            habilitarDadosAeronave();
            btnExcluirAeronave.setEnabled(false);
            btnSalvarAeronave.setEnabled(true);
            btnEditarAeronave.setEnabled(false);
            btnLimparAeronave.setEnabled(true);
            flag = true;
        }

        if (flag == false) {
            // tituloMsg = "Alteração Aeronave";
            //msg = msg + "Aeronave não encontrada!!!, Entre com outro prefixo\n" ;
            //msg = msg + "Nenhuma Aeronave Cadastrada!!\n";
            //JOptionPane.showMessageDialog(this, msg);
            btnExcluirAeronave.setEnabled(false);
            btnSalvarAeronave.setEnabled(true);
            btnEditarAeronave.setEnabled(false);
            btnLimparAeronave.setEnabled(true);
        }
        if (msg.equals("")) {

        } else {
            JOptionPane.showMessageDialog(this, msg, tituloMsg, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarAeronaveActionPerformed

    private void btnSalvarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAeronaveActionPerformed
        AeronaveCtrl cAeronave = new AeronaveCtrl();
        Aeronave objAero;
        objAero = new Aeronave();
        boolean flag = false; //ainda não alterou
        String msg = "";
        String tituloMsg = "";
        objAero.setIdAeronave("0");

        /**
         * Preenchimento objeto objAero (Aeronave)
         */
        objAero.setPrefixo(tftPrefixoAeronave.getText());
        objAero.setSeatEconomyClasse(Integer.parseInt(tftClasseEconomica.getText()));
        objAero.setSeatFirstClasse(Integer.parseInt(tftPrimeiraClasse.getText()));
        objAero.setSeatBusinesClasse(Integer.parseInt(tftClasseEmpresarial.getText()));
        objAero.setModelo(tctModeloAeronave.getText());
        objAero.setFabricante(tctFabricanteAeronave.getText());
        objAero.setOperadora(tctOperadoraAeronave.getText());
        /**
         *
         * Validações para o Form Aeronave (objAero)
         *
         */
        boolean validaModelo = ValidaCampos.validaVazio(tctModeloAeronave.getText().trim());
        boolean validaPrefixo = ValidaCampos.validaVazio(tftPrefixoAeronave.getText().trim());
        boolean validaClasseE = ValidaCampos.validaNumeroVazio(Integer.parseInt(tftClasseEconomica.getText()));
        boolean validaClasseP = ValidaCampos.validaNumeroVazio(Integer.parseInt(tftPrimeiraClasse.getText()));
        boolean validaClasseB = ValidaCampos.validaNumeroVazio(Integer.parseInt(tftClasseEmpresarial.getText()));
        boolean validaFabricante = ValidaCampos.validaVazio(tctFabricanteAeronave.getText());
        boolean validaOperadora = ValidaCampos.validaVazio(tctOperadoraAeronave.getText());
        boolean validaPrefixoExiste = AeronaveCtrl.receberPesquisarAeronavePrefixo(tftPrefixoAeronave.getText());

        if (btnSalvarAeronave.isEnabled()) {
            if (validaPrefixoExiste) {
            } else {
                msg = msg + "Campo Prefixo da aeronave já existe na base de dados Aerofast" + "\n";
                TelaAeronave.tftPrefixoAeronave.setText(null);
            }
            
        }

        if (validaModelo) {
        } else {
            msg = msg + "Campo Modelo Vazio" + "\n";
        }

        if (validaPrefixo) {
        } else {
            msg = msg + "Campo Prefixo Vazio" + "\n";
        }

        if (validaClasseE) {
        } else {
            msg = msg + "Campo Classe Economica invalido: " + tftClasseEconomica.getText() + "\n";
            this.tftClasseEconomica.setText(null);
        }

        if (validaClasseP) {
        } else {
            msg = msg + "Campo Classe Primeira invalido: " + tftPrimeiraClasse.getText() + "\n";
            this.tftPrimeiraClasse.setText(null);
        }

        if (validaClasseB) {
        } else {
            msg = msg + "Campo Classe Empresarial invalido: " + tftClasseEmpresarial.getText() + "\n";
            this.tftClasseEmpresarial.setText(null);
        }

        if (validaFabricante) {
        } else {
            msg = msg + "Campo Fabricante Vazio" + "\n";
        }
        
        if (validaOperadora) {
        } else {
            msg = msg + "Campo Operadora Vazio" + "\n";
        }
        
        if ("".equals(msg)) {

            if (btnSalvarAeronave.isEnabled()) {

                boolean resultadoAeronave = arrayAero.add(objAero);
                if (resultadoAeronave) {

                    cAeronave.receberAeronave(objAero);
                    tituloMsg = "Inclusão Aeronave";
                    msg = "Dados Enviados ao banco de dados do sistema!";
                    //JOptionPane.showMessageDialog(this, msg, "Dados Enviados", JOptionPane.INFORMATION_MESSAGE);
                    flag = true;
                }
                //JOptionPane.showMessageDialog(this, msg, "Dados Enviados", JOptionPane.INFORMATION_MESSAGE);
                btnLimparAeronave.doClick();

            } else {//Alteração Aeronave

                cAeronave.alterarAeronaveCtrl(objAero, oldPrefixo);
                tituloMsg = "Alteração Aeronave";
                msg = "Dados da Aeronave alterados com Sucesso";
                btnLimparAeronave.doClick();
                flag = true;
            }
            btnLimparAeronave.doClick();
            btnSairAeronave.doClick();
        } else {
            tituloMsg = "Campo Inválido ou vazio";
            flag = false;
        }
        if (flag == false) {
            JOptionPane.showMessageDialog(this, msg, tituloMsg, JOptionPane.WARNING_MESSAGE);
        }

        /**
         * final btnSalvarAeronaveActionPerformed*
         */

    }//GEN-LAST:event_btnSalvarAeronaveActionPerformed

    private void tftClasseEconomicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftClasseEconomicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftClasseEconomicaActionPerformed

    private void btnLimparAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparAeronaveActionPerformed
        limparAeronave();
        
        /*
        tctModeloAeronave.setText(null);
        tftPrefixoAeronave.setText(null);
        tctFabricanteAeronave.setText(null);
        tftClasseEconomica.setText("0");
        tftClasseEmpresarial.setText("0");
        tftPrimeiraClasse.setText("0");
        */
    }//GEN-LAST:event_btnLimparAeronaveActionPerformed

    private void tftClasseEmpresarialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftClasseEmpresarialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftClasseEmpresarialActionPerformed

    private void tftPrimeiraClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftPrimeiraClasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftPrimeiraClasseActionPerformed

    private void btnExcluirAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAeronaveActionPerformed
        btnSalvarAeronave.setEnabled(false);
        btnAlterarAeronave.setEnabled(false);
        btnEditarAeronave.setEnabled(false);
        boolean flag = false;

        //início
        Aeronave aeronave;

        aeronave = AeronaveCtrl.receberAeronavePrefixo(tftPrefixoAeronave.getText());
        if (aeronave != null) {
            oldPrefixo = tftPrefixoAeronave.getText();
            tctModeloAeronave.setText(aeronave.getModelo());
            tftPrefixoAeronave.setText(aeronave.getPrefixo());
            tftClasseEconomica.setText(aeronave.getSeatEconomyClasse() + "");
            tftClasseEmpresarial.setText(aeronave.getSeatBusinesClasse() + "");
            tftPrimeiraClasse.setText(aeronave.getSeatFirstClasse() + "");
            tctFabricanteAeronave.setText(aeronave.getFabricante());
            tctOperadoraAeronave.setText(aeronave.getOperadora());
            //desabilitar edição
            desabilitarDadosAeronave();
            AeronaveCtrl cAeronave = new AeronaveCtrl();
            cAeronave.deletarAeronaveCtrl(aeronave, oldPrefixo);
            btnLimparAeronaveActionPerformed(evt);
            habilitarDadosAeronave();
            flag = true;
        }//fim if


    }//GEN-LAST:event_btnExcluirAeronaveActionPerformed

    private void btnEditarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAeronaveActionPerformed
        // TODO add your handling code here:
        //Status dos botões
        btnAlterarAeronave.setEnabled(true);
        btnSalvarAeronave.setEnabled(false);
        btnEditarAeronave.setEnabled(false);

        if (!tctModeloAeronave.isEditable()) {
            //msg = "Pode realizar alterações agora";
            habilitarDadosAeronave();
            //  JOptionPane.showMessageDialog(this, msg,"", JOptionPane.INFORMATION_MESSAGE );
        }
        btnAlterarAeronave.setEnabled(true);
        btnEditarAeronave.setEnabled(false);
    }//GEN-LAST:event_btnEditarAeronaveActionPerformed

    private void btnAlterarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarAeronaveActionPerformed
        // TODO add your handling code here:
        //btnSalvarPassageiro.doClick();
        btnSalvarAeronaveActionPerformed(evt);
    }//GEN-LAST:event_btnAlterarAeronaveActionPerformed

    private void tftClasseEconomicaColunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftClasseEconomicaColunasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftClasseEconomicaColunasActionPerformed

    private void tftClasseEmpresarialColunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftClasseEmpresarialColunasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftClasseEmpresarialColunasActionPerformed

    private void tftPrimeiraClasseColunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftPrimeiraClasseColunasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftPrimeiraClasseColunasActionPerformed

    private void tftLayoutAssentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftLayoutAssentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftLayoutAssentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaAeronave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelClienteBotoes;
    private javax.swing.JPanel JPanelClienteTitulo;
    private javax.swing.JPanel PainelAeronaveVoo;
    private static javax.swing.JButton btnAlterarAeronave;
    private javax.swing.JButton btnEditarAeronave;
    private javax.swing.JButton btnExcluirAeronave;
    private javax.swing.JButton btnLimparAeronave;
    private javax.swing.JButton btnPesquisarAeronave;
    private javax.swing.JButton btnSairAeronave;
    private javax.swing.JButton btnSalvarAeronave;
    private javax.swing.JLabel lblClasse1;
    private javax.swing.JLabel lblClasse2;
    private javax.swing.JLabel lblClasse3;
    private javax.swing.JLabel lblClasse4;
    private javax.swing.JLabel lblFabricanteAeronave;
    private javax.swing.JLabel lblModeloAeronave;
    private javax.swing.JLabel lblNumAssentosEconomica;
    private javax.swing.JLabel lblNumAssentosEconomicaCol;
    private javax.swing.JLabel lblNumAssentosEmpresarial;
    private javax.swing.JLabel lblNumAssentosEmpresarialCol;
    private javax.swing.JLabel lblNumAssentosPrimeira;
    private javax.swing.JLabel lblNumAssentosPrimeiraCol;
    private javax.swing.JLabel lblOperadoraAeronave;
    private javax.swing.JLabel lblPrefixoAeronave;
    private javax.swing.JLabel lblTelaAeronave;
    private javax.swing.JLabel lblTituloTelaPassageiro;
    private static javax.swing.JTextField tctFabricanteAeronave;
    private static javax.swing.JTextField tctModeloAeronave;
    private static javax.swing.JTextField tctOperadoraAeronave;
    private javax.swing.JFormattedTextField tftClasseEconomica;
    private javax.swing.JFormattedTextField tftClasseEconomicaColunas;
    private javax.swing.JFormattedTextField tftClasseEmpresarial;
    private javax.swing.JFormattedTextField tftClasseEmpresarialColunas;
    private javax.swing.JFormattedTextField tftLayoutAssentos;
    private static javax.swing.JTextField tftPrefixoAeronave;
    private javax.swing.JFormattedTextField tftPrimeiraClasse;
    private javax.swing.JFormattedTextField tftPrimeiraClasseColunas;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para Limpar os dados de edição da tela Aeronave
     */
    private void limparAeronave() {
        tctModeloAeronave.setText(null);
        tftPrefixoAeronave.setText(null);
        tctFabricanteAeronave.setText(null);
        tctOperadoraAeronave.setText(null);
        tftClasseEconomica.setText("0");
        tftClasseEmpresarial.setText("0");
        tftPrimeiraClasse.setText("0");
    }

    /**
     * Método para habilitar a edição da tela Aeronave
     */
    private void habilitarDadosAeronave() {
        tctModeloAeronave.setEditable(true);
        tftPrefixoAeronave.setEditable(true);
        tctFabricanteAeronave.setEditable(true);
        tctOperadoraAeronave.setEditable(true);
        tftClasseEconomica.setEditable(true);
        tftClasseEmpresarial.setEditable(true);
        tftPrimeiraClasse.setEditable(true);

    }

    /**
     * Método para desabilitar a edição da tela Aeronave
     */
    private void desabilitarDadosAeronave() {
        tctModeloAeronave.setEditable(false);
        tftPrefixoAeronave.setEditable(false);
        tctFabricanteAeronave.setEditable(false);
        tctOperadoraAeronave.setEditable(false);
        tftClasseEconomica.setEditable(false);
        tftClasseEmpresarial.setEditable(false);
        tftPrimeiraClasse.setEditable(false);

    }
}
