/*
 * Este Software tem Objetivo Educacional
 * Para fins de aprendizagem e avaliacao na
 * Na Disciplina de Programacao Orientada a Objetos - Avancada
 *  do Curso de Analise de Sistemas da Fatec - Ipiranga
 * Ano 2016 - Janeiro a Junho 
 * Aluno Decio Antonio de Carvalho  * 
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Passagem;
//import src.ValidaCampos;
/**
 *
 * @author deciodecarvalho
 */
public class TelaPassagem extends javax.swing.JFrame {

    public static ArrayList<model.Passagem> arrayPass;  //Para ser utilizado em todas as partes do programa
    public static boolean temPassagem;
    
        
    
    /**
     * Creates new form TelaCliente
     */
       public TelaPassagem() {
        
        initComponents();
       cbxClasse.setSelectedIndex(-1);
        if (!temPassagem){
        arrayPass = new ArrayList<>();
        temPassagem = true;
        }
       
    }

       
       
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPassagemTitulo = new javax.swing.JPanel();
        lblTelaPassagem = new javax.swing.JLabel();
        lblTituloTelaPassagem = new javax.swing.JLabel();
        PainelTotalPassagem = new javax.swing.JPanel();
        PainelPassagemChegada = new javax.swing.JPanel();
        lblPassagemHoraChegada = new javax.swing.JLabel();
        tftHoraChegada = new javax.swing.JFormattedTextField();
        tftDataChegada = new javax.swing.JFormattedTextField();
        lblPassagemDataChegada = new javax.swing.JLabel();
        lblPassagemAeroportoChegada = new javax.swing.JLabel();
        tctAeroportoChegada = new javax.swing.JTextField();
        lblPassagemSiglaAeroportoChegada = new javax.swing.JLabel();
        tctSiglaAeroportoChegada = new javax.swing.JTextField();
        lblPassagemPortaoChegada = new javax.swing.JLabel();
        tctPortaoAeroportoChegada = new javax.swing.JTextField();
        PainelPassagemEscalas = new javax.swing.JPanel();
        lblPassagemEscalas = new javax.swing.JLabel();
        tctPassagemEscalas = new javax.swing.JTextField();
        PanelPassagemBotoes = new javax.swing.JPanel();
        btnSalvarPassagem = new javax.swing.JButton();
        btnPesquisarPassagem = new javax.swing.JButton();
        btnSairPassagem = new javax.swing.JButton();
        btnLimparPassagem = new javax.swing.JButton();
        btnExcluirPassagem = new javax.swing.JButton();
        PainelPassagemPartida = new javax.swing.JPanel();
        lblHoraPartidaPassagem = new javax.swing.JLabel();
        tftHoraPartida = new javax.swing.JFormattedTextField();
        tftDataPartida = new javax.swing.JFormattedTextField();
        lblDataPartidaPassagem = new javax.swing.JLabel();
        lblAeroportoPartidaPassagem = new javax.swing.JLabel();
        tctAeroportoPartida = new javax.swing.JTextField();
        lblSiglaAeroportoPartidaPassagem = new javax.swing.JLabel();
        tctSiglaAeroportoPartida = new javax.swing.JTextField();
        lblPortaoPartidaPassagem = new javax.swing.JLabel();
        tctPortaoAeroportoPartida = new javax.swing.JTextField();
        PainelPassagemEmpresaVoo = new javax.swing.JPanel();
        tctNomePassageiro = new javax.swing.JTextField();
        lblPassagemNome = new javax.swing.JLabel();
        lblRgPassagem = new javax.swing.JLabel();
        tftRgPassagem = new javax.swing.JFormattedTextField();
        tctNumeroPassagem = new javax.swing.JTextField();
        lblNumeroPassagem = new javax.swing.JLabel();
        tftDataPassagem = new javax.swing.JFormattedTextField();
        lblDataPassagem = new javax.swing.JLabel();
        PainelPassagemTarifas = new javax.swing.JPanel();
        lblPassagemTarifaE = new javax.swing.JLabel();
        tftPassagemTarifaTotal = new javax.swing.JFormattedTextField();
        lblNumeroVooPassagem = new javax.swing.JLabel();
        tctNumeroVoo = new javax.swing.JTextField();
        lblCiaAereaPassagem = new javax.swing.JLabel();
        tctCiaAereaPassagem = new javax.swing.JTextField();
        lblPassagemAssentoNumero = new javax.swing.JLabel();
        tctPassagemNumeroAssento = new javax.swing.JTextField();
        lblPassagemTarifa = new javax.swing.JLabel();
        lblPassagemStatus = new javax.swing.JLabel();
        tctStatus = new javax.swing.JTextField();
        cbxClasse = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTelaPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/infraero/PassagemIcone.png"))); // NOI18N

        lblTituloTelaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTituloTelaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloTelaPassagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTelaPassagem.setText("Passagem Aérea");

        javax.swing.GroupLayout PainelPassagemTituloLayout = new javax.swing.GroupLayout(PainelPassagemTitulo);
        PainelPassagemTitulo.setLayout(PainelPassagemTituloLayout);
        PainelPassagemTituloLayout.setHorizontalGroup(
            PainelPassagemTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPassagemTituloLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(lblTelaPassagem)
                .addGap(41, 41, 41)
                .addComponent(lblTituloTelaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        PainelPassagemTituloLayout.setVerticalGroup(
            PainelPassagemTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloTelaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblTelaPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        PainelPassagemChegada.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem - Voo Chegada"));
        PainelPassagemChegada.setToolTipText("");

        lblPassagemHoraChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemHoraChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemHoraChegada.setText("Hora Chegada: ");

        tftHoraChegada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tftHoraChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        try {
            tftDataChegada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftDataChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftDataChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftDataChegadaActionPerformed(evt);
            }
        });

        lblPassagemDataChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemDataChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemDataChegada.setText("Data Chegada: ");

        lblPassagemAeroportoChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemAeroportoChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemAeroportoChegada.setText("Aeroporto Chegada: ");

        tctAeroportoChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctAeroportoChegada.setForeground(new java.awt.Color(51, 51, 51));
        tctAeroportoChegada.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPassagemSiglaAeroportoChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemSiglaAeroportoChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemSiglaAeroportoChegada.setText("Sigla Aeroporto Partida: ");

        tctSiglaAeroportoChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctSiglaAeroportoChegada.setForeground(new java.awt.Color(51, 51, 51));
        tctSiglaAeroportoChegada.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPassagemPortaoChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemPortaoChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemPortaoChegada.setText("Gate / Portão:");

        tctPortaoAeroportoChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPortaoAeroportoChegada.setForeground(new java.awt.Color(51, 51, 51));
        tctPortaoAeroportoChegada.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout PainelPassagemChegadaLayout = new javax.swing.GroupLayout(PainelPassagemChegada);
        PainelPassagemChegada.setLayout(PainelPassagemChegadaLayout);
        PainelPassagemChegadaLayout.setHorizontalGroup(
            PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemChegadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassagemChegadaLayout.createSequentialGroup()
                        .addComponent(lblPassagemAeroportoChegada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tctAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPassagemSiglaAeroportoChegada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tctSiglaAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassagemChegadaLayout.createSequentialGroup()
                        .addComponent(lblPassagemDataChegada)
                        .addGap(18, 18, 18)
                        .addComponent(tftDataChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPassagemHoraChegada)
                        .addGap(18, 18, 18)
                        .addComponent(tftHoraChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPassagemPortaoChegada)
                        .addGap(18, 18, 18)
                        .addComponent(tctPortaoAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 66, Short.MAX_VALUE))
        );
        PainelPassagemChegadaLayout.setVerticalGroup(
            PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemChegadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassagemAeroportoChegada)
                    .addComponent(tctAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemSiglaAeroportoChegada)
                    .addComponent(tctSiglaAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassagemDataChegada)
                    .addComponent(tftDataChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemHoraChegada)
                    .addComponent(tftHoraChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemPortaoChegada)
                    .addComponent(tctPortaoAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        PainelPassagemEscalas.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem - Voo Escalas"));

        lblPassagemEscalas.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemEscalas.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemEscalas.setText("Escalas: ");

        tctPassagemEscalas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPassagemEscalas.setForeground(new java.awt.Color(51, 51, 51));
        tctPassagemEscalas.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout PainelPassagemEscalasLayout = new javax.swing.GroupLayout(PainelPassagemEscalas);
        PainelPassagemEscalas.setLayout(PainelPassagemEscalasLayout);
        PainelPassagemEscalasLayout.setHorizontalGroup(
            PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemEscalasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPassagemEscalas)
                .addGap(18, 18, 18)
                .addComponent(tctPassagemEscalas)
                .addContainerGap())
        );
        PainelPassagemEscalasLayout.setVerticalGroup(
            PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemEscalasLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassagemEscalas)
                    .addComponent(tctPassagemEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelPassagemBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalvarPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvarPassagem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSalvarPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarGreen_1.png"))); // NOI18N
        btnSalvarPassagem.setText("Salvar");
        btnSalvarPassagem.setToolTipText("Salvar Alterações");
        btnSalvarPassagem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvarPassagem.setIconTextGap(2);
        btnSalvarPassagem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSalvarPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSalvarPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPassagemActionPerformed(evt);
            }
        });

        btnPesquisarPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnPesquisarPassagem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPesquisarPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lupaVermelha 40x40.png"))); // NOI18N
        btnPesquisarPassagem.setText("Pesquisar");
        btnPesquisarPassagem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnPesquisarPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnPesquisarPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPassagemActionPerformed(evt);
            }
        });

        btnSairPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnSairPassagem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSairPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairPassagem.setText("Voltar");
        btnSairPassagem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSairPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairPassagemActionPerformed(evt);
            }
        });

        btnLimparPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparPassagem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLimparPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/oopsRed.png"))); // NOI18N
        btnLimparPassagem.setText("Limpar");
        btnLimparPassagem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnLimparPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnLimparPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPassagemActionPerformed(evt);
            }
        });

        btnExcluirPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnExcluirPassagem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnExcluirPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/excluir 40x40 vermelho.png"))); // NOI18N
        btnExcluirPassagem.setText("Excluir");
        btnExcluirPassagem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnExcluirPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnExcluirPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPassagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPassagemBotoesLayout = new javax.swing.GroupLayout(PanelPassagemBotoes);
        PanelPassagemBotoes.setLayout(PanelPassagemBotoesLayout);
        PanelPassagemBotoesLayout.setHorizontalGroup(
            PanelPassagemBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPassagemBotoesLayout.createSequentialGroup()
                .addComponent(btnSalvarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimparPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSairPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelPassagemBotoesLayout.setVerticalGroup(
            PanelPassagemBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPassagemBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPassagemBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPassagemBotoesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelPassagemBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSairPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimparPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelPassagemBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvarPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        PanelPassagemBotoesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExcluirPassagem, btnLimparPassagem, btnPesquisarPassagem, btnSairPassagem});

        PainelPassagemPartida.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem - Voo Partida"));
        PainelPassagemPartida.setToolTipText("");

        lblHoraPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblHoraPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblHoraPartidaPassagem.setText("Hora Partida: ");

        tftHoraPartida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tftHoraPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        try {
            tftDataPartida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftDataPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftDataPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftDataPartidaActionPerformed(evt);
            }
        });

        lblDataPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblDataPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblDataPartidaPassagem.setText("Data Partida: ");

        lblAeroportoPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblAeroportoPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblAeroportoPartidaPassagem.setText("Aeroporto Partida: ");

        tctAeroportoPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctAeroportoPartida.setForeground(new java.awt.Color(51, 51, 51));
        tctAeroportoPartida.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblSiglaAeroportoPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblSiglaAeroportoPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblSiglaAeroportoPartidaPassagem.setText("Sigla Aeroporto Partida: ");

        tctSiglaAeroportoPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctSiglaAeroportoPartida.setForeground(new java.awt.Color(51, 51, 51));
        tctSiglaAeroportoPartida.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPortaoPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPortaoPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblPortaoPartidaPassagem.setText("Gate / Portão:");

        tctPortaoAeroportoPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPortaoAeroportoPartida.setForeground(new java.awt.Color(51, 51, 51));
        tctPortaoAeroportoPartida.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout PainelPassagemPartidaLayout = new javax.swing.GroupLayout(PainelPassagemPartida);
        PainelPassagemPartida.setLayout(PainelPassagemPartidaLayout);
        PainelPassagemPartidaLayout.setHorizontalGroup(
            PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassagemPartidaLayout.createSequentialGroup()
                        .addComponent(lblAeroportoPartidaPassagem)
                        .addGap(18, 18, 18)
                        .addComponent(tctAeroportoPartida)
                        .addGap(18, 18, 18)
                        .addComponent(lblSiglaAeroportoPartidaPassagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tctSiglaAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassagemPartidaLayout.createSequentialGroup()
                        .addComponent(lblDataPartidaPassagem)
                        .addGap(18, 18, 18)
                        .addComponent(tftDataPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblHoraPartidaPassagem)
                        .addGap(18, 18, 18)
                        .addComponent(tftHoraPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPortaoPartidaPassagem)
                        .addGap(18, 18, 18)
                        .addComponent(tctPortaoAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 67, Short.MAX_VALUE))))
        );
        PainelPassagemPartidaLayout.setVerticalGroup(
            PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemPartidaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAeroportoPartidaPassagem)
                    .addComponent(tctAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSiglaAeroportoPartidaPassagem)
                    .addComponent(tctSiglaAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataPartidaPassagem)
                    .addComponent(tftDataPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraPartidaPassagem)
                    .addComponent(tftHoraPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPortaoPartidaPassagem)
                    .addComponent(tctPortaoAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelTotalPassagemLayout = new javax.swing.GroupLayout(PainelTotalPassagem);
        PainelTotalPassagem.setLayout(PainelTotalPassagemLayout);
        PainelTotalPassagemLayout.setHorizontalGroup(
            PainelTotalPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPassagemEscalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelPassagemBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelTotalPassagemLayout.createSequentialGroup()
                .addGroup(PainelTotalPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PainelPassagemChegada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelPassagemPartida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainelTotalPassagemLayout.setVerticalGroup(
            PainelTotalPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTotalPassagemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelPassagemPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelPassagemChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelPassagemEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPassagemBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PainelPassagemEmpresaVoo.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem Aérea - Passageiro"));

        tctNomePassageiro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctNomePassageiro.setForeground(new java.awt.Color(51, 51, 51));
        tctNomePassageiro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctNomePassageiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctNomePassageiroMouseReleased(evt);
            }
        });

        lblPassagemNome.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemNome.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemNome.setText("Passageiro :");

        lblRgPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblRgPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblRgPassagem.setText("RG :");

        try {
            tftRgPassagem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftRgPassagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftRgPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftRgPassagemActionPerformed(evt);
            }
        });

        tctNumeroPassagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctNumeroPassagem.setForeground(new java.awt.Color(51, 51, 51));
        tctNumeroPassagem.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctNumeroPassagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctNumeroPassagemMouseReleased(evt);
            }
        });

        lblNumeroPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumeroPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblNumeroPassagem.setText("Número Passagem : ");

        try {
            tftDataPassagem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftDataPassagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftDataPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftDataPassagemActionPerformed(evt);
            }
        });

        lblDataPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblDataPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblDataPassagem.setText("Data Passagem : ");

        javax.swing.GroupLayout PainelPassagemEmpresaVooLayout = new javax.swing.GroupLayout(PainelPassagemEmpresaVoo);
        PainelPassagemEmpresaVoo.setLayout(PainelPassagemEmpresaVooLayout);
        PainelPassagemEmpresaVooLayout.setHorizontalGroup(
            PainelPassagemEmpresaVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemEmpresaVooLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemEmpresaVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelPassagemEmpresaVooLayout.createSequentialGroup()
                        .addComponent(lblPassagemNome)
                        .addGap(18, 18, 18)
                        .addComponent(tctNomePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassagemEmpresaVooLayout.createSequentialGroup()
                        .addComponent(lblNumeroPassagem)
                        .addGap(18, 18, 18)
                        .addComponent(tctNumeroPassagem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemEmpresaVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelPassagemEmpresaVooLayout.createSequentialGroup()
                        .addComponent(lblRgPassagem)
                        .addGap(18, 18, 18)
                        .addComponent(tftRgPassagem))
                    .addGroup(PainelPassagemEmpresaVooLayout.createSequentialGroup()
                        .addComponent(lblDataPassagem)
                        .addGap(18, 18, 18)
                        .addComponent(tftDataPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelPassagemEmpresaVooLayout.setVerticalGroup(
            PainelPassagemEmpresaVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemEmpresaVooLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemEmpresaVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassagemEmpresaVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDataPassagem)
                        .addComponent(tftDataPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassagemEmpresaVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumeroPassagem)
                        .addComponent(tctNumeroPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemEmpresaVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassagemNome)
                    .addComponent(tctNomePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRgPassagem)
                    .addComponent(tftRgPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelPassagemTarifas.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem - Empresa / Tarifas Voos"));

        lblPassagemTarifaE.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemTarifaE.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemTarifaE.setText("Classe : ");

        tftPassagemTarifaTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        tftPassagemTarifaTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tftPassagemTarifaTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftPassagemTarifaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftPassagemTarifaTotalActionPerformed(evt);
            }
        });

        lblNumeroVooPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumeroVooPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblNumeroVooPassagem.setText("Número Voo:");

        tctNumeroVoo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctNumeroVoo.setForeground(new java.awt.Color(51, 51, 51));
        tctNumeroVoo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctNumeroVoo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctNumeroVooMouseReleased(evt);
            }
        });

        lblCiaAereaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblCiaAereaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblCiaAereaPassagem.setText("Cia Aérea: ");

        tctCiaAereaPassagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctCiaAereaPassagem.setForeground(new java.awt.Color(51, 51, 51));
        tctCiaAereaPassagem.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPassagemAssentoNumero.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemAssentoNumero.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemAssentoNumero.setText("Assento Número : ");

        tctPassagemNumeroAssento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPassagemNumeroAssento.setForeground(new java.awt.Color(51, 51, 51));
        tctPassagemNumeroAssento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctPassagemNumeroAssento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctPassagemNumeroAssentoMouseReleased(evt);
            }
        });

        lblPassagemTarifa.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemTarifa.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemTarifa.setText(" Tarifa Total R$ : ");

        lblPassagemStatus.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemStatus.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemStatus.setText("Status :");

        tctStatus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctStatus.setForeground(new java.awt.Color(51, 51, 51));
        tctStatus.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctStatusMouseReleased(evt);
            }
        });

        cbxClasse.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbxClasse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economica", "Empresarial", "Primeira" }));

        javax.swing.GroupLayout PainelPassagemTarifasLayout = new javax.swing.GroupLayout(PainelPassagemTarifas);
        PainelPassagemTarifas.setLayout(PainelPassagemTarifasLayout);
        PainelPassagemTarifasLayout.setHorizontalGroup(
            PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addComponent(lblPassagemAssentoNumero)
                        .addGap(18, 18, 18)
                        .addComponent(tctPassagemNumeroAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addComponent(lblNumeroVooPassagem)
                        .addGap(18, 18, 18)
                        .addComponent(tctNumeroVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblCiaAereaPassagem)
                        .addGap(18, 18, 18)
                        .addComponent(tctCiaAereaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPassagemStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(tctStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblPassagemTarifaE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPassagemTarifa)
                        .addGap(32, 32, 32)
                        .addComponent(tftPassagemTarifaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelPassagemTarifasLayout.setVerticalGroup(
            PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPassagemTarifasLayout.createSequentialGroup()
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tctStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tctCiaAereaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumeroVooPassagem)
                        .addComponent(tctNumeroVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCiaAereaPassagem))
                    .addComponent(lblPassagemStatus, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPassagemAssentoNumero)
                        .addGap(26, 26, 26))
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassagemTarifaE)
                            .addComponent(cbxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassagemTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tctPassagemNumeroAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftPassagemTarifaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelTotalPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelPassagemTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PainelPassagemEmpresaVoo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PainelPassagemTarifas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPassagemTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelPassagemEmpresaVoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelPassagemTarifas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelTotalPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairPassagemActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairPassagemActionPerformed

    private void btnPesquisarPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPassagemActionPerformed
        boolean flag = false;
       
        for(int i = 0; i < arrayPass.size(); i++){
        if(tftRgPassagem.getText().equals(arrayPass.get(i).getRgPassageiro())){
            
           
       tctNumeroPassagem.setText(arrayPass.get(i).getNumeroPassagem());
       tctNomePassageiro.setText(arrayPass.get(i).getNomePassageiro());
       tftRgPassagem.setText(arrayPass.get(i).getRgPassageiro());
       tctStatus.setText(arrayPass.get(i).getReserva());
       tctNumeroVoo.setText(arrayPass.get(i).getVooNumero());
       tctPassagemNumeroAssento.setText(arrayPass.get(i).getAssentoNumero());
       cbxClasse.setSelectedItem(arrayPass.get(i).getClasse());
       tctCiaAereaPassagem.setText(arrayPass.get(i).getCiaAerea());
       tftPassagemTarifaTotal.setText(arrayPass.get(i).getTarifa());
       tctAeroportoPartida.setText(arrayPass.get(i).getPartidaAeroporto());
       tctSiglaAeroportoPartida.setText(arrayPass.get(i).getPartidaSiglaAeroporto());
       tftDataPartida.setText(arrayPass.get(i).getPartidaData());
       tftHoraPartida.setText(arrayPass.get(i).getPartidaHora());
       tctPortaoAeroportoPartida.setText(arrayPass.get(i).getPartidaPortao());
       tctAeroportoChegada.setText(arrayPass.get(i).getChegadaAeroporto());
       tctSiglaAeroportoChegada.setText(arrayPass.get(i).getChegadaSiglaAeroporto());
       tftDataChegada.setText(arrayPass.get(i).getChegadaData());
       tftHoraChegada.setText(arrayPass.get(i).getChegadaHora());
       tctPortaoAeroportoChegada.setText(arrayPass.get(i).getChegadaPortao());
       tctPassagemEscalas.setText(arrayPass.get(i).getEscalasVoo());
         
            
            
            flag = true;
        }//fim do if
       }// fim do for
        
        if(arrayPass.isEmpty())
            JOptionPane.showMessageDialog(this,"Nenhuma Passagem Cadastrada!!");
        else if (flag == false)
            JOptionPane.showMessageDialog(this, "Passagem não encontrada!!!");    
    }//GEN-LAST:event_btnPesquisarPassagemActionPerformed

    private void btnSalvarPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPassagemActionPerformed
        Passagem objPass;
        objPass = new Passagem();
        
        int id1 = arrayPass.size();
        id1++;
        String id = id1+"";
        
        
        
        objPass.setIdPassagem(id);
        objPass.setNumeroPassagem(tctNumeroPassagem.getText());
        objPass.setDataPassagem(tftDataPassagem.getText());
        objPass.setNomePassageiro(tctNomePassageiro.getText());
        objPass.setRgPassageiro(tftRgPassagem.getText());
        objPass.setReserva(tctStatus.getText());
        objPass.setVooNumero(tctNumeroVoo.getText());
        objPass.setCiaAerea(tctCiaAereaPassagem.getText());
        objPass.setAssentoNumero(tctPassagemNumeroAssento.getText());
        objPass.setClasse(cbxClasse.getSelectedItem().toString());
        objPass.setTarifa(tftPassagemTarifaTotal.getText());
        objPass.setPartidaAeroporto(tctAeroportoPartida.getText());
        objPass.setPartidaSiglaAeroporto(tctSiglaAeroportoPartida.getText());
        objPass.setPartidaData(tftDataPartida.getText());
        objPass.setPartidaHora(tftHoraPartida.getText());
        objPass.setPartidaPortao(tctPortaoAeroportoPartida.getText());
                
        objPass.setChegadaAeroporto(tctAeroportoChegada.getText());
        objPass.setChegadaSiglaAeroporto(tctSiglaAeroportoChegada.getText());
        objPass.setChegadaData(tftDataChegada.getText());
        objPass.setChegadaHora(tftHoraChegada.getText());
        objPass.setChegadaPortao(tctPortaoAeroportoChegada.getText());
        objPass.setEscalasVoo(tctPassagemEscalas.getText());
       
        
        
        String msg;
        msg = "";
/*
        boolean validaVoo = ValidaCampos.validaVazio(tctNumeroVooPassagem.getText());
        boolean validaCia = ValidaCampos.validaVazio(tctCiaAereaPassagem.getText());
        boolean validaDataP = ValidaCampos.validaData(tftDataPartidaPassagem.getText());
        boolean validaHoraP = ValidaCampos.validaHora(tftHoraPartidaPassagem.getText());
        boolean validaAeroportoP = ValidaCampos.validaVazio(tctAeroportoPartidaPassagem.getText());
        boolean validaDataC = ValidaCampos.validaData(tftPassagemDataChegada.getText());
        boolean validaHoraC = ValidaCampos.validaHora(tftPassagemHoraChegada.getText());
        boolean validaAeroportoC = ValidaCampos.validaVazio(tctPassagemAeroportoChegada.getText());
                
       */
         /**
         * Validações Voo
         * 
         */
/*
        if (validaVoo) {
        } else {
            msg = msg + "Campo Voo Vazio" + "\n";
        }
        if (validaCia) {
        } else {
            msg = msg + "Campo Companhia Aérea Vazio" + "\n";
        }
         
        if (validaAeroportoP) {
        } else {
            msg = msg + "Campo Aeroporto Partida Vazio" + "\n";
        }
        
        if (validaDataP) {
        } else {
            msg = msg + "Campo Data Partida invalido: "+ tftDataPartidaPassagem.getText() + "\n";
            this.tftDataPartidaPassagem.setText(null);
        }
         
        if (validaHoraP) {
        } else {
            msg = msg + "Campo Hora Partida invalido: "+ tftHoraPartidaPassagem.getText() + "\n";
            this.tftHoraPartidaPassagem.setText(null);
        }
        
        if (validaAeroportoC) {
        } else {
            msg = msg + "Campo Aeroporto Chegada Vazio" + "\n";
        }
        
        if (validaDataC) {
        } else {
            msg = msg + "Campo Data Chegada invalido: "+ tftPassagemDataChegada.getText() + "\n";
            this.tftPassagemDataChegada.setText(null);
        }
         if (validaHoraC) {
        } else {
            msg = msg + "Campo Hora Chegada invalido: "+ tftPassagemHoraChegada.getText() + "\n";
            this.tftPassagemHoraChegada.setText(null);
        }
          
         
*/
                 
        if ("".equals(msg)){
            msg = "Dados Enviados ao banco de dados do sistema!";
            boolean resultadoPassagem = arrayPass.add(objPass);
            JOptionPane.showMessageDialog(this, msg,"Dados Enviados", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Resposta se adcionou nova Passagem? "+resultadoPassagem+" id:"+id);
            btnLimparPassagem.doClick();
        }
        else{
            JOptionPane.showMessageDialog(this, msg,"Campo Inválido ou vazio", JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_btnSalvarPassagemActionPerformed

    private void tftDataPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftDataPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftDataPartidaActionPerformed

    private void btnLimparPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPassagemActionPerformed
       tctNumeroPassagem.setText(null);
       tftDataPassagem.setText(null);
       tctNomePassageiro.setText(null);
       tftRgPassagem.setText(null);
       tctStatus.setText(null);
       tctNumeroVoo.setText(null);
       tctPassagemNumeroAssento.setText(null);
       cbxClasse.setSelectedIndex(-1);
       tctCiaAereaPassagem.setText(null);
       tftPassagemTarifaTotal.setText(null);
       tctAeroportoPartida.setText(null);
       tctSiglaAeroportoPartida.setText(null);
       tftDataPartida.setText(null);
       tftHoraPartida.setText(null);
       tctPortaoAeroportoPartida.setText(null);
       tctAeroportoChegada.setText(null);
       tctSiglaAeroportoChegada.setText(null);
       tftDataChegada.setText(null);
       tftHoraChegada.setText(null);
       tctPortaoAeroportoChegada.setText(null);
       tctPassagemEscalas.setText(null);
       
    }//GEN-LAST:event_btnLimparPassagemActionPerformed

    private void tftDataChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftDataChegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftDataChegadaActionPerformed

    private void tctNumeroVooMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctNumeroVooMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctNumeroVooMouseReleased

    private void tftPassagemTarifaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftPassagemTarifaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftPassagemTarifaTotalActionPerformed

    private void btnExcluirPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPassagemActionPerformed
        boolean flag = false;

        for(int i = 0; i < arrayPass.size(); i++){

            if(tctNumeroPassagem.getText().trim().equals(arrayPass.get(i).getNumeroPassagem())){
                String removidaPassagem = arrayPass.get(i).getNumeroPassagem();
                Passagem removido = arrayPass.remove(i);

                JOptionPane.showMessageDialog(this,"Passagem nº: "+removidaPassagem+" Removida!");
                btnLimparPassagem.doClick(); //Limpar tela

                flag = true;

            }//fim do if
        }// fim do for

        if(arrayPass.isEmpty())
        JOptionPane.showMessageDialog(this,"Nenhuma Passagem Cadastrada!!");
        else if (flag == false)
        JOptionPane.showMessageDialog(this, "Número de Passagem não Encontrado!!!");
    }//GEN-LAST:event_btnExcluirPassagemActionPerformed

    private void tctNomePassageiroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctNomePassageiroMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctNomePassageiroMouseReleased

    private void tftRgPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftRgPassagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftRgPassagemActionPerformed

    private void tctPassagemNumeroAssentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctPassagemNumeroAssentoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctPassagemNumeroAssentoMouseReleased

    private void tctNumeroPassagemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctNumeroPassagemMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctNumeroPassagemMouseReleased

    private void tctStatusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctStatusMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctStatusMouseReleased

    private void tftDataPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftDataPassagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftDataPassagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPassagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPassagemChegada;
    private javax.swing.JPanel PainelPassagemEmpresaVoo;
    private javax.swing.JPanel PainelPassagemEscalas;
    private javax.swing.JPanel PainelPassagemPartida;
    private javax.swing.JPanel PainelPassagemTarifas;
    private javax.swing.JPanel PainelPassagemTitulo;
    private javax.swing.JPanel PainelTotalPassagem;
    private javax.swing.JPanel PanelPassagemBotoes;
    private javax.swing.JButton btnExcluirPassagem;
    private javax.swing.JButton btnLimparPassagem;
    private javax.swing.JButton btnPesquisarPassagem;
    private javax.swing.JButton btnSairPassagem;
    private javax.swing.JButton btnSalvarPassagem;
    private javax.swing.JComboBox cbxClasse;
    private javax.swing.JLabel lblAeroportoPartidaPassagem;
    private javax.swing.JLabel lblCiaAereaPassagem;
    private javax.swing.JLabel lblDataPartidaPassagem;
    private javax.swing.JLabel lblDataPassagem;
    private javax.swing.JLabel lblHoraPartidaPassagem;
    private javax.swing.JLabel lblNumeroPassagem;
    private javax.swing.JLabel lblNumeroVooPassagem;
    private javax.swing.JLabel lblPassagemAeroportoChegada;
    private javax.swing.JLabel lblPassagemAssentoNumero;
    private javax.swing.JLabel lblPassagemDataChegada;
    private javax.swing.JLabel lblPassagemEscalas;
    private javax.swing.JLabel lblPassagemHoraChegada;
    private javax.swing.JLabel lblPassagemNome;
    private javax.swing.JLabel lblPassagemPortaoChegada;
    private javax.swing.JLabel lblPassagemSiglaAeroportoChegada;
    private javax.swing.JLabel lblPassagemStatus;
    private javax.swing.JLabel lblPassagemTarifa;
    private javax.swing.JLabel lblPassagemTarifaE;
    private javax.swing.JLabel lblPortaoPartidaPassagem;
    private javax.swing.JLabel lblRgPassagem;
    private javax.swing.JLabel lblSiglaAeroportoPartidaPassagem;
    private javax.swing.JLabel lblTelaPassagem;
    private javax.swing.JLabel lblTituloTelaPassagem;
    private static javax.swing.JTextField tctAeroportoChegada;
    private static javax.swing.JTextField tctAeroportoPartida;
    private static javax.swing.JTextField tctCiaAereaPassagem;
    private static javax.swing.JTextField tctNomePassageiro;
    private static javax.swing.JTextField tctNumeroPassagem;
    private static javax.swing.JTextField tctNumeroVoo;
    private static javax.swing.JTextField tctPassagemEscalas;
    private static javax.swing.JTextField tctPassagemNumeroAssento;
    private static javax.swing.JTextField tctPortaoAeroportoChegada;
    private static javax.swing.JTextField tctPortaoAeroportoPartida;
    private static javax.swing.JTextField tctSiglaAeroportoChegada;
    private static javax.swing.JTextField tctSiglaAeroportoPartida;
    private static javax.swing.JTextField tctStatus;
    private javax.swing.JFormattedTextField tftDataChegada;
    private javax.swing.JFormattedTextField tftDataPartida;
    private javax.swing.JFormattedTextField tftDataPassagem;
    private javax.swing.JFormattedTextField tftHoraChegada;
    private javax.swing.JFormattedTextField tftHoraPartida;
    private javax.swing.JFormattedTextField tftPassagemTarifaTotal;
    private javax.swing.JFormattedTextField tftRgPassagem;
    // End of variables declaration//GEN-END:variables

    
}
