/*
 * Este Software tem Objetivo Educacional
 * Para fins de aprendizagem e avaliacao na
 * Na Disciplina de Programacao Orientada a Objetos - Avancada
 * do Curso de Analise de Sistemas da Fatec - Ipiranga
 * Ano 2016 - Janeiro a Junho 
 * Aluno Decio Antonio de Carvalho  * 
 */
package view;

import Control.PassageiroCtrl;
import Control.PassagemCtrl;
import Control.Util;
import Control.ValidaCampos;
import Control.VooCtrl;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Passageiro;
import model.Passagem;
import model.Voo;

/**
 *
 * @author deciodecarvalho
 */
public class TelaNovaPassagem extends javax.swing.JInternalFrame {

    public static ArrayList<model.Passagem> arrayPass;
//Para ser utilizado em todas as partes do programa
    public static boolean temPassagemNova;

    private static String dataPassagem, dataHojePassagem;
    private static Date dataPs;
    private static Date hojePassagem;
    private static SimpleDateFormat sdfHojePassagem;
    private int idp = 0;
    public float valorPassagemE, valorPassagemB, valorPassagemF = 0;

    /**
     * Creates new form TelaVazia
     */
    public TelaNovaPassagem() {
        initComponents();
        //habilitar e desabilitar botões
        btnGerarNumeroPassagem.setEnabled(true);
        btnAlterarPassagem.setEnabled(false);
        btnSalvarPassagem.setEnabled(true);
        btnEditarPassagem.setEnabled(false);
        btnExcluirPassagem.setEnabled(false);
        btnCalcularTarifa.setEnabled(false);
        cbxClasse.setSelectedIndex(-1);
        //desabilitar elementos do formulario
        tctNumeroPassagem.setEditable(false);
        tctNumeroVoo.setText("");
        desabilitarPartidaChegada();
        if (!temPassagemNova) {
            arrayPass = new ArrayList<>();
            temPassagemNova = true;
        }

        jdpDataPassagem.setDate(Calendar.getInstance().getTime());
        jdpDataPassagem.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        hojePassagem = new Date();
        dataHojePassagem = Util.DataFormatada(hojePassagem);
        sdfHojePassagem = new SimpleDateFormat("dd/MM/yyyy");
        try {
            hojePassagem = sdfHojePassagem.parse(dataHojePassagem);
        } catch (ParseException ex) {
            Logger.getLogger(TelaNovaPassagem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgStatus = new javax.swing.ButtonGroup();
        PainelPassagemTitulo = new javax.swing.JPanel();
        lblTelaPassagem = new javax.swing.JLabel();
        lblTituloTelaPassagem = new javax.swing.JLabel();
        PainelGuiasPassagem = new javax.swing.JTabbedPane();
        PainelPassageiro = new javax.swing.JPanel();
        tctNomePassageiro = new javax.swing.JTextField();
        lblPassagemNome = new javax.swing.JLabel();
        lblRgPassagem = new javax.swing.JLabel();
        tftRgPassagem = new javax.swing.JFormattedTextField();
        tctNumeroPassagem = new javax.swing.JTextField();
        lblNumeroPassagem = new javax.swing.JLabel();
        lblDataPassagem = new javax.swing.JLabel();
        jdpDataPassagem = new org.jdesktop.swingx.JXDatePicker();
        btnPesquisarPassageiroRG = new javax.swing.JButton();
        btnGerarNumeroPassagem = new javax.swing.JButton();
        PainelPassagemTarifas = new javax.swing.JPanel();
        lblPassagemTarifaE = new javax.swing.JLabel();
        tftPassagemTarifaTotal = new javax.swing.JFormattedTextField();
        lblNumeroVooPassagem = new javax.swing.JLabel();
        tctNumeroVoo = new javax.swing.JTextField();
        lblCiaAereaPassagem = new javax.swing.JLabel();
        tctCiaAereaPassagem = new javax.swing.JTextField();
        lblPassagemAssentoNumero = new javax.swing.JLabel();
        tctPassagemNumeroAssento = new javax.swing.JTextField();
        lblPassagemTarifa = new javax.swing.JLabel();
        lblPassagemStatus = new javax.swing.JLabel();
        cbxClasse = new javax.swing.JComboBox();
        rbDisponivel = new javax.swing.JRadioButton();
        rbReservada = new javax.swing.JRadioButton();
        rbConfirmada = new javax.swing.JRadioButton();
        btnPesquisarVooNumero = new javax.swing.JButton();
        btnCalcularTarifa = new javax.swing.JButton();
        PainelPassagemPartida = new javax.swing.JPanel();
        lblHoraPartidaPassagem = new javax.swing.JLabel();
        tftHoraPartida = new javax.swing.JFormattedTextField();
        tftDataPartida = new javax.swing.JFormattedTextField();
        lblDataPartidaPassagem = new javax.swing.JLabel();
        lblAeroportoPartidaPassagem = new javax.swing.JLabel();
        tctAeroportoPartida = new javax.swing.JTextField();
        lblSiglaAeroportoPartidaPassagem = new javax.swing.JLabel();
        tctSiglaAeroportoPartida = new javax.swing.JTextField();
        lblPortaoPartidaPassagem = new javax.swing.JLabel();
        tctPortaoAeroportoPartida = new javax.swing.JTextField();
        PainelPassagemChegada = new javax.swing.JPanel();
        lblPassagemHoraChegada = new javax.swing.JLabel();
        tftHoraChegada = new javax.swing.JFormattedTextField();
        tftDataChegada = new javax.swing.JFormattedTextField();
        lblPassagemDataChegada = new javax.swing.JLabel();
        lblPassagemAeroportoChegada = new javax.swing.JLabel();
        tctAeroportoChegada = new javax.swing.JTextField();
        lblPassagemSiglaAeroportoChegada = new javax.swing.JLabel();
        tctSiglaAeroportoChegada = new javax.swing.JTextField();
        lblPassagemPortaoChegada = new javax.swing.JLabel();
        tctPortaoAeroportoChegada = new javax.swing.JTextField();
        PainelPassagemEscalas = new javax.swing.JPanel();
        lblPassagemEscalas = new javax.swing.JLabel();
        tctPassagemEscalas = new javax.swing.JTextField();
        lblPassagemEscalasObs = new javax.swing.JLabel();
        scrPassagemObservacao = new javax.swing.JScrollPane();
        tctPassagemObservacao = new javax.swing.JTextArea();
        PanelPassagemBotoes = new javax.swing.JPanel();
        btnSalvarPassagem = new javax.swing.JButton();
        btnPesquisarPassagem = new javax.swing.JButton();
        btnLimparPassagem = new javax.swing.JButton();
        btnExcluirPassagem = new javax.swing.JButton();
        btnEditarPassagem = new javax.swing.JButton();
        btnAlterarPassagem = new javax.swing.JButton();
        btnSairPassagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelPassagemTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTelaPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/passagem 40x40.jpg"))); // NOI18N

        lblTituloTelaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTituloTelaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloTelaPassagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTelaPassagem.setText("Passagem Aérea");

        javax.swing.GroupLayout PainelPassagemTituloLayout = new javax.swing.GroupLayout(PainelPassagemTitulo);
        PainelPassagemTitulo.setLayout(PainelPassagemTituloLayout);
        PainelPassagemTituloLayout.setHorizontalGroup(
            PainelPassagemTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemTituloLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(lblTelaPassagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloTelaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(390, Short.MAX_VALUE))
        );
        PainelPassagemTituloLayout.setVerticalGroup(
            PainelPassagemTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPassagemTituloLayout.createSequentialGroup()
                .addGroup(PainelPassagemTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelPassagemTituloLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTelaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassagemTituloLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblTituloTelaPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        PainelGuiasPassagem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        PainelPassageiro.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem Aérea - Passageiro"));

        tctNomePassageiro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctNomePassageiro.setForeground(new java.awt.Color(51, 51, 51));
        tctNomePassageiro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctNomePassageiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctNomePassageiroMouseReleased(evt);
            }
        });
        tctNomePassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tctNomePassageiroActionPerformed(evt);
            }
        });

        lblPassagemNome.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemNome.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemNome.setText("Passageiro :");

        lblRgPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblRgPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblRgPassagem.setText("RG :");

        try {
            tftRgPassagem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftRgPassagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftRgPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftRgPassagemActionPerformed(evt);
            }
        });

        tctNumeroPassagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctNumeroPassagem.setForeground(new java.awt.Color(51, 51, 51));
        tctNumeroPassagem.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctNumeroPassagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctNumeroPassagemMouseReleased(evt);
            }
        });

        lblNumeroPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumeroPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblNumeroPassagem.setText("Número Passagem : ");

        lblDataPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblDataPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblDataPassagem.setText("Data Passagem : ");

        jdpDataPassagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jdpDataPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdpDataPassagemActionPerformed(evt);
            }
        });

        btnPesquisarPassageiroRG.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPesquisarPassageiroRG.setText("Pesquisar em Passageiro");
        btnPesquisarPassageiroRG.setToolTipText("Pesquisar RG passageiro");
        btnPesquisarPassageiroRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPassageiroRGActionPerformed(evt);
            }
        });

        btnGerarNumeroPassagem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGerarNumeroPassagem.setText("Gerar Número Passagem");
        btnGerarNumeroPassagem.setToolTipText("Gerador automático número passagem");
        btnGerarNumeroPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarNumeroPassagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPassageiroLayout = new javax.swing.GroupLayout(PainelPassageiro);
        PainelPassageiro.setLayout(PainelPassageiroLayout);
        PainelPassageiroLayout.setHorizontalGroup(
            PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassageiroLayout.createSequentialGroup()
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassageiroLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblNumeroPassagem)
                        .addGap(30, 30, 30)
                        .addComponent(tctNumeroPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGerarNumeroPassagem))
                    .addGroup(PainelPassageiroLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDataPassagem)
                            .addComponent(lblRgPassagem)
                            .addComponent(lblPassagemNome))
                        .addGap(30, 30, 30)
                        .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelPassageiroLayout.createSequentialGroup()
                                .addComponent(tftRgPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisarPassageiroRG))
                            .addComponent(jdpDataPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tctNomePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        PainelPassageiroLayout.setVerticalGroup(
            PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassageiroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctNumeroPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroPassagem)
                    .addComponent(btnGerarNumeroPassagem))
                .addGap(18, 18, 18)
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdpDataPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataPassagem))
                .addGap(18, 18, 18)
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctNomePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemNome))
                .addGap(21, 21, 21)
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftRgPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRgPassagem)
                    .addComponent(btnPesquisarPassageiroRG))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        btnPesquisarPassageiroRG.getAccessibleContext().setAccessibleName("Pesquisar RG passageiro");
        btnGerarNumeroPassagem.getAccessibleContext().setAccessibleName("Gerador automático número passagem");

        PainelGuiasPassagem.addTab("Passageiro", PainelPassageiro);

        PainelPassagemTarifas.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem - Empresa / Tarifas Voos"));

        lblPassagemTarifaE.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemTarifaE.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemTarifaE.setText("Classe : ");

        tftPassagemTarifaTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        tftPassagemTarifaTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tftPassagemTarifaTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftPassagemTarifaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftPassagemTarifaTotalActionPerformed(evt);
            }
        });

        lblNumeroVooPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumeroVooPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblNumeroVooPassagem.setText("Número Voo:");

        tctNumeroVoo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctNumeroVoo.setForeground(new java.awt.Color(51, 51, 51));
        tctNumeroVoo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctNumeroVoo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctNumeroVooMouseReleased(evt);
            }
        });

        lblCiaAereaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblCiaAereaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblCiaAereaPassagem.setText("Cia Aérea: ");

        tctCiaAereaPassagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctCiaAereaPassagem.setForeground(new java.awt.Color(51, 51, 51));
        tctCiaAereaPassagem.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPassagemAssentoNumero.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemAssentoNumero.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemAssentoNumero.setText("Assento Número : ");

        tctPassagemNumeroAssento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPassagemNumeroAssento.setForeground(new java.awt.Color(51, 51, 51));
        tctPassagemNumeroAssento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctPassagemNumeroAssento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctPassagemNumeroAssentoMouseReleased(evt);
            }
        });

        lblPassagemTarifa.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemTarifa.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemTarifa.setText(" Tarifa Total R$ : ");

        lblPassagemStatus.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemStatus.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemStatus.setText("Status :");

        cbxClasse.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbxClasse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economica", "Empresarial", "Primeira" }));
        cbxClasse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxClasseItemStateChanged(evt);
            }
        });

        bgStatus.add(rbDisponivel);
        rbDisponivel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbDisponivel.setText("Disponível");

        bgStatus.add(rbReservada);
        rbReservada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbReservada.setText("Reservada");

        bgStatus.add(rbConfirmada);
        rbConfirmada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbConfirmada.setText("Confirmada");

        btnPesquisarVooNumero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPesquisarVooNumero.setText("Pesquisar um Voo");
        btnPesquisarVooNumero.setToolTipText("Pesquisar um Voo");
        btnPesquisarVooNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarVooNumeroActionPerformed(evt);
            }
        });

        btnCalcularTarifa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCalcularTarifa.setText("Cálculo da Tarifa");
        btnCalcularTarifa.setToolTipText("Cálculo da Tarifa");
        btnCalcularTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTarifaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPassagemTarifasLayout = new javax.swing.GroupLayout(PainelPassagemTarifas);
        PainelPassagemTarifas.setLayout(PainelPassagemTarifasLayout);
        PainelPassagemTarifasLayout.setHorizontalGroup(
            PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblNumeroVooPassagem)
                        .addGap(36, 36, 36)
                        .addComponent(tctNumeroVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarVooNumero))
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblCiaAereaPassagem)
                        .addGap(36, 36, 36)
                        .addComponent(tctCiaAereaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassagemTarifaE)
                            .addComponent(lblPassagemAssentoNumero)
                            .addComponent(lblPassagemTarifa))
                        .addGap(36, 36, 36)
                        .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tctPassagemNumeroAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                                .addComponent(tftPassagemTarifaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCalcularTarifa))
                            .addComponent(cbxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lblPassagemStatus)
                        .addGap(33, 33, 33)
                        .addComponent(rbDisponivel)
                        .addGap(31, 31, 31)
                        .addComponent(rbReservada)
                        .addGap(33, 33, 33)
                        .addComponent(rbConfirmada)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        PainelPassagemTarifasLayout.setVerticalGroup(
            PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctNumeroVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroVooPassagem)
                    .addComponent(btnPesquisarVooNumero))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tctCiaAereaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCiaAereaPassagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemTarifaE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassagemAssentoNumero)
                    .addComponent(tctPassagemNumeroAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassagemTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftPassagemTarifaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularTarifa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassagemStatus)
                    .addComponent(rbDisponivel)
                    .addComponent(rbReservada)
                    .addComponent(rbConfirmada))
                .addContainerGap())
        );

        PainelGuiasPassagem.addTab("Passagem", PainelPassagemTarifas);

        PainelPassagemPartida.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem - Voo Partida"));
        PainelPassagemPartida.setToolTipText("");

        lblHoraPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblHoraPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblHoraPartidaPassagem.setText("Hora Partida: ");

        tftHoraPartida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tftHoraPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        try {
            tftDataPartida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftDataPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftDataPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftDataPartidaActionPerformed(evt);
            }
        });

        lblDataPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblDataPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblDataPartidaPassagem.setText("Data Partida: ");

        lblAeroportoPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblAeroportoPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblAeroportoPartidaPassagem.setText("Aeroporto Partida: ");

        tctAeroportoPartida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tctAeroportoPartida.setForeground(new java.awt.Color(51, 51, 51));
        tctAeroportoPartida.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblSiglaAeroportoPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblSiglaAeroportoPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblSiglaAeroportoPartidaPassagem.setText("Sigla Aeroporto Partida: ");

        tctSiglaAeroportoPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctSiglaAeroportoPartida.setForeground(new java.awt.Color(51, 51, 51));
        tctSiglaAeroportoPartida.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPortaoPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPortaoPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblPortaoPartidaPassagem.setText("Gate / Portão:");

        tctPortaoAeroportoPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPortaoAeroportoPartida.setForeground(new java.awt.Color(51, 51, 51));
        tctPortaoAeroportoPartida.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout PainelPassagemPartidaLayout = new javax.swing.GroupLayout(PainelPassagemPartida);
        PainelPassagemPartida.setLayout(PainelPassagemPartidaLayout);
        PainelPassagemPartidaLayout.setHorizontalGroup(
            PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemPartidaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSiglaAeroportoPartidaPassagem)
                    .addComponent(lblPortaoPartidaPassagem)
                    .addComponent(lblAeroportoPartidaPassagem)
                    .addComponent(lblHoraPartidaPassagem)
                    .addComponent(lblDataPartidaPassagem))
                .addGap(35, 35, 35)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tctSiglaAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftHoraPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftDataPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tctPortaoAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tctAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        PainelPassagemPartidaLayout.setVerticalGroup(
            PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftDataPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataPartidaPassagem))
                .addGap(21, 21, 21)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftHoraPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraPartidaPassagem))
                .addGap(21, 21, 21)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAeroportoPartidaPassagem))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctSiglaAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSiglaAeroportoPartidaPassagem))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctPortaoAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPortaoPartidaPassagem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelGuiasPassagem.addTab("Partida", PainelPassagemPartida);

        PainelPassagemChegada.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem - Voo Chegada"));
        PainelPassagemChegada.setToolTipText("");

        lblPassagemHoraChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemHoraChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemHoraChegada.setText("Hora Chegada: ");

        tftHoraChegada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tftHoraChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        try {
            tftDataChegada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftDataChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftDataChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftDataChegadaActionPerformed(evt);
            }
        });

        lblPassagemDataChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemDataChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemDataChegada.setText("Data Chegada: ");

        lblPassagemAeroportoChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemAeroportoChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemAeroportoChegada.setText("Aeroporto Chegada: ");

        tctAeroportoChegada.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tctAeroportoChegada.setForeground(new java.awt.Color(51, 51, 51));
        tctAeroportoChegada.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPassagemSiglaAeroportoChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemSiglaAeroportoChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemSiglaAeroportoChegada.setText("Sigla Aeroporto Partida: ");

        tctSiglaAeroportoChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctSiglaAeroportoChegada.setForeground(new java.awt.Color(51, 51, 51));
        tctSiglaAeroportoChegada.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPassagemPortaoChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemPortaoChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemPortaoChegada.setText("Gate / Portão:");

        tctPortaoAeroportoChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPortaoAeroportoChegada.setForeground(new java.awt.Color(51, 51, 51));
        tctPortaoAeroportoChegada.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout PainelPassagemChegadaLayout = new javax.swing.GroupLayout(PainelPassagemChegada);
        PainelPassagemChegada.setLayout(PainelPassagemChegadaLayout);
        PainelPassagemChegadaLayout.setHorizontalGroup(
            PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemChegadaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassagemChegadaLayout.createSequentialGroup()
                        .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassagemSiglaAeroportoChegada)
                            .addComponent(lblPassagemPortaoChegada))
                        .addGap(38, 38, 38)
                        .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tctSiglaAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tctPortaoAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelPassagemChegadaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassagemHoraChegada)
                            .addComponent(lblPassagemDataChegada)
                            .addComponent(lblPassagemAeroportoChegada))
                        .addGap(38, 38, 38)
                        .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tftDataChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftHoraChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tctAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        PainelPassagemChegadaLayout.setVerticalGroup(
            PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemChegadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftDataChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemDataChegada))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassagemHoraChegada)
                    .addComponent(tftHoraChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassagemAeroportoChegada)
                    .addComponent(tctAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctSiglaAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemSiglaAeroportoChegada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tctPortaoAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemPortaoChegada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelGuiasPassagem.addTab("Chegada", PainelPassagemChegada);

        PainelPassagemEscalas.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem - Voo Escalas"));

        lblPassagemEscalas.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemEscalas.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemEscalas.setText("Escalas: ");

        tctPassagemEscalas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPassagemEscalas.setForeground(new java.awt.Color(51, 51, 51));
        tctPassagemEscalas.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPassagemEscalasObs.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemEscalasObs.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemEscalasObs.setText("Observações :");

        tctPassagemObservacao.setColumns(20);
        tctPassagemObservacao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tctPassagemObservacao.setRows(5);
        scrPassagemObservacao.setViewportView(tctPassagemObservacao);

        javax.swing.GroupLayout PainelPassagemEscalasLayout = new javax.swing.GroupLayout(PainelPassagemEscalas);
        PainelPassagemEscalas.setLayout(PainelPassagemEscalasLayout);
        PainelPassagemEscalasLayout.setHorizontalGroup(
            PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemEscalasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassagemEscalas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassagemEscalasObs, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrPassagemObservacao)
                    .addComponent(tctPassagemEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        PainelPassagemEscalasLayout.setVerticalGroup(
            PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemEscalasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassagemEscalas)
                    .addComponent(tctPassagemEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassagemEscalasObs)
                    .addComponent(scrPassagemObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        PainelGuiasPassagem.addTab("Escalas", PainelPassagemEscalas);

        PanelPassagemBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalvarPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvarPassagem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSalvarPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarGreen_1.png"))); // NOI18N
        btnSalvarPassagem.setText("Salvar");
        btnSalvarPassagem.setToolTipText("Salvar Alterações");
        btnSalvarPassagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalvarPassagem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvarPassagem.setIconTextGap(2);
        btnSalvarPassagem.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSalvarPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSalvarPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPassagemActionPerformed(evt);
            }
        });

        btnPesquisarPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnPesquisarPassagem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnPesquisarPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lupaVermelha 40x40.png"))); // NOI18N
        btnPesquisarPassagem.setText("Pesquisar");
        btnPesquisarPassagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPesquisarPassagem.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPesquisarPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnPesquisarPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPassagemActionPerformed(evt);
            }
        });

        btnLimparPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparPassagem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLimparPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/oopsRed.png"))); // NOI18N
        btnLimparPassagem.setText("Limpar");
        btnLimparPassagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimparPassagem.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLimparPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnLimparPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPassagemActionPerformed(evt);
            }
        });

        btnExcluirPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnExcluirPassagem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnExcluirPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/excluir 40x40 vermelho.png"))); // NOI18N
        btnExcluirPassagem.setText("Excluir");
        btnExcluirPassagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExcluirPassagem.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnExcluirPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnExcluirPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPassagemActionPerformed(evt);
            }
        });

        btnEditarPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnEditarPassagem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEditarPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inserir.png"))); // NOI18N
        btnEditarPassagem.setText("Editar");
        btnEditarPassagem.setToolTipText("Editar Alterações");
        btnEditarPassagem.setDefaultCapable(false);
        btnEditarPassagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarPassagem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditarPassagem.setIconTextGap(1);
        btnEditarPassagem.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnEditarPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnEditarPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPassagemActionPerformed(evt);
            }
        });

        btnAlterarPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnAlterarPassagem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAlterarPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarRed.png"))); // NOI18N
        btnAlterarPassagem.setText("Alterar");
        btnAlterarPassagem.setToolTipText("Alterar Dados");
        btnAlterarPassagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAlterarPassagem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAlterarPassagem.setIconTextGap(0);
        btnAlterarPassagem.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAlterarPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnAlterarPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPassagemActionPerformed(evt);
            }
        });

        btnSairPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnSairPassagem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSairPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairPassagem.setText("Voltar");
        btnSairPassagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSairPassagem.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSairPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairPassagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPassagemBotoesLayout = new javax.swing.GroupLayout(PanelPassagemBotoes);
        PanelPassagemBotoes.setLayout(PanelPassagemBotoesLayout);
        PanelPassagemBotoesLayout.setHorizontalGroup(
            PanelPassagemBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPassagemBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        PanelPassagemBotoesLayout.setVerticalGroup(
            PanelPassagemBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPassagemBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSalvarPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnExcluirPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnLimparPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnEditarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAlterarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSairPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelPassagemTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelPassagemBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(PainelGuiasPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPassagemTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelGuiasPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPassagemBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tctNomePassageiroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctNomePassageiroMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctNomePassageiroMouseReleased

    private void tftRgPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftRgPassagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftRgPassagemActionPerformed

    private void tctNumeroPassagemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctNumeroPassagemMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctNumeroPassagemMouseReleased

    private void tftPassagemTarifaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftPassagemTarifaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftPassagemTarifaTotalActionPerformed

    private void tctNumeroVooMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctNumeroVooMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctNumeroVooMouseReleased

    private void tctPassagemNumeroAssentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctPassagemNumeroAssentoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctPassagemNumeroAssentoMouseReleased

    private void tftDataPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftDataPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftDataPartidaActionPerformed

    private void tftDataChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftDataChegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftDataChegadaActionPerformed

    private void btnSalvarPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPassagemActionPerformed
        Passagem objPass;
        objPass = new Passagem();
        PassagemCtrl cPassagem = new PassagemCtrl();

        boolean flag = false;
        String msg = "";
        String tituloMsg = "";
        String reserva = "";
        String numeroPassagem = "";

        if (rbConfirmada.isSelected()) {
            reserva = "Confirmada";
        }

        if (rbReservada.isSelected()) {
            reserva = "Reservada";
        }

        if (rbDisponivel.isSelected()) {
            reserva = "Disponivel";
        }

        //int id1 = arrayPass.size();
        idp = cPassagem.receberIdAtual();
        idp++;
        String id = idp + "";

        //numeroPassagem 
        objPass.setIdPassagem(id);
        objPass.setNumeroPassagem(tctNumeroPassagem.getText());

        /**
         * DataPassagem
         */
        dataPassagem = jdpDataPassagem.getEditor().getText();
        objPass.setDataPassagem(dataPassagem);
        // objPass.setDataPassagem(tftDataPassagem.getText());

        objPass.setNomePassageiro(tctNomePassageiro.getText());
        objPass.setRgPassageiro(tftRgPassagem.getText());
        objPass.setReserva(reserva);
        objPass.setVooNumero(tctNumeroVoo.getText());
        objPass.setCiaAerea(tctCiaAereaPassagem.getText());
        objPass.setAssentoNumero(tctPassagemNumeroAssento.getText());

        /**
         * Tratamento para o ComboBox -1
         */
        if (cbxClasse.getSelectedIndex() == -1) {
        } else {
            objPass.setClasse(cbxClasse.getSelectedItem().toString());
        }

        objPass.setTarifa(tftPassagemTarifaTotal.getText());
        objPass.setPartidaAeroporto(tctAeroportoPartida.getText());
        objPass.setPartidaSiglaAeroporto(tctSiglaAeroportoPartida.getText());
        objPass.setPartidaData(tftDataPartida.getText());
        objPass.setPartidaHora(tftHoraPartida.getText());
        objPass.setPartidaPortao(tctPortaoAeroportoPartida.getText());

        objPass.setChegadaAeroporto(tctAeroportoChegada.getText());
        objPass.setChegadaSiglaAeroporto(tctSiglaAeroportoChegada.getText());
        objPass.setChegadaData(tftDataChegada.getText());
        objPass.setChegadaHora(tftHoraChegada.getText());
        objPass.setChegadaPortao(tctPortaoAeroportoChegada.getText());
        objPass.setEscalasVoo(tctPassagemEscalas.getText());
        objPass.setObservacaoPassagem(tctPassagemObservacao.getText());
        //String msg;
        //msg = "";

        boolean validaNumeroPassagem = ValidaCampos.validaVazio(tctNumeroPassagem.getText());
        boolean validaNomePassageiro = ValidaCampos.validaNome(tctNomePassageiro.getText());
        boolean validaRgPassageiro = ValidaCampos.validaRG(tftRgPassagem.getText());
        boolean validaNumeroVoo = ValidaCampos.validaVazio(tctNumeroVoo.getText());
        boolean validaNumeroAssento = ValidaCampos.validaVazio(tctPassagemNumeroAssento.getText());
        boolean validaTarifaTotal = ValidaCampos.validaStringNumero(tftPassagemTarifaTotal.getText());
        boolean validaStatusPassagem = ValidaCampos.validaStatus(rbDisponivel.isSelected(),
                rbReservada.isSelected(), rbConfirmada.isSelected());
        /**
         *
         * Validar Data Passagem
         *
         */
        try {
            dataPs = sdfHojePassagem.parse(dataPassagem);
        } catch (ParseException ex) {
            Logger.getLogger(TelaNovoVoo.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (dataPs.before(hojePassagem)) {
            msg = msg + "Campo Data Passagem inválido: " + dataPassagem + "\n";
            dataPassagem = null;
        } else {

        }
        //fim validacao dataPartida

        if (validaNumeroPassagem) {
        } else {
            msg = msg + "Campo Número Passagem Vazio" + "\n";
        }
        if (validaNomePassageiro) {
        } else {
            msg = msg + "Campo Nome Passageiro Menor que 5 Carácteres ou Inválido" + "\n";
        }

        if (validaRgPassageiro) {
        } else {
            msg = msg + "Campo Rg Passageiro inválido" + "\n";
        }

        if (validaNumeroVoo) {
        } else {
            msg = msg + "Campo Número Voo Vazio" + "\n";
        }

        if (cbxClasse.getSelectedIndex() == -1) {
            msg = msg + "Campo Classe da Passagem não selecionado: " + "\n";
            cbxClasse.setSelectedIndex(-1);
        }

        if (validaNumeroAssento) {
        } else {
            msg = msg + "Campo Número Assento Vazio" + "\n";
        }

        if (validaTarifaTotal) {
        } else {
            msg = msg + "Campo Tarifa Total Vazio" + "\n";
        }

        if (validaStatusPassagem) {

        } else {
            msg = msg + "Status da Passagem não selecionado! " + "\n";
        }

        if ("".equals(msg)) {

            if (btnSalvarPassagem.isEnabled()) {

                boolean resultadoPassagem = arrayPass.add(objPass);
                if (resultadoPassagem) {
                    cPassagem.enviarNovaPassagem(objPass);
                    tituloMsg = "Inclusão Passagem";
                    msg = "Dados Enviados ao banco de dados do sistema!";
                    flag = true;
                }

                btnLimparPassagem.doClick();

            } else { //Alteração Passagem
                cPassagem.alterarPassagemCtrl(objPass, numeroPassagem);
                tituloMsg = "Alteraçao Passagem";
                msg = "Dados da Passagem alterados com sucesso!";
                btnLimparPassagem.doClick();
                flag = true;
            }//fim alteração

            btnLimparPassagem.doClick();
            btnSairPassagem.doClick();
        } else {
            tituloMsg = "Campo Inválido ou vazio";
            flag = false;

        }

        if (flag == false) {
            JOptionPane.showMessageDialog(this, msg, tituloMsg, JOptionPane.ERROR_MESSAGE);
        }

        /**
         * final btnSalvarPassagemActionPerformed*
         */

    }//GEN-LAST:event_btnSalvarPassagemActionPerformed

    private void btnPesquisarPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPassagemActionPerformed

        //Status dos botões
        btnAlterarPassagem.setEnabled(false);
        btnSalvarPassagem.setEnabled(true);
        btnEditarPassagem.setEnabled(true);
        btnLimparPassagem.setEnabled(false);
        btnExcluirPassagem.setEnabled(true);
        btnCalcularTarifa.setEnabled(false);
        boolean flag = false;
        String msg = "";
        String tituloMsg = "";
        String vNumPassagem = tctNumeroPassagem.getText();
        tctNumeroPassagem.setEditable(true);
        PassagemCtrl cPassagem = new PassagemCtrl();
        Passagem passagem = new Passagem();

        passagem = PassagemCtrl.receberPassagemNumero(vNumPassagem);

        if (passagem != null) {

            if (passagem.getReserva().equals("Reservada")) {
                rbReservada.setSelected(true);
            }
            if (passagem.getReserva().equals("Confirmada")) {
                rbConfirmada.setSelected(true);
            }
            if (passagem.getReserva().equals("Disponivel")) {
                rbDisponivel.setSelected(true);
            }

            /**
             * Tratamento do campo tipo jDatePicker
             */
            String sdataPartida = passagem.getDataPassagem();
            // Date dtPartida = new Date();
            SimpleDateFormat sdf2 = new SimpleDateFormat("dd/MM/yyyyy");
            try {
                Date dtPartida = sdf2.parse(sdataPartida);
                jdpDataPassagem.setDate(dtPartida);
            } catch (ParseException ex) {
                Logger.getLogger(TelaNovoVoo.class.getName()).log(Level.SEVERE, null, ex);
            }
                //fim do tratamento campo JDatePicker 

            //jdpDataPassagem
            tctNumeroPassagem.setText(passagem.getNumeroPassagem());
            tctNomePassageiro.setText(passagem.getNomePassageiro());
            tftRgPassagem.setText(passagem.getRgPassageiro());
            tctNumeroVoo.setText(passagem.getVooNumero());
            tctPassagemNumeroAssento.setText(passagem.getAssentoNumero());
            cbxClasse.setSelectedItem(passagem.getClasse());
            cbxClasse.setEnabled(false);
            tctCiaAereaPassagem.setText(passagem.getCiaAerea());
            tftPassagemTarifaTotal.setText(passagem.getTarifa());
            tctAeroportoPartida.setText(passagem.getPartidaAeroporto());
            tctSiglaAeroportoPartida.setText(passagem.getPartidaSiglaAeroporto());

            tftDataPartida.setText(passagem.getPartidaData());
            tftHoraPartida.setText(passagem.getPartidaHora());
            tctPortaoAeroportoPartida.setText(passagem.getPartidaPortao());
            tctAeroportoChegada.setText(passagem.getChegadaAeroporto());
            tctSiglaAeroportoChegada.setText(passagem.getChegadaSiglaAeroporto());

            tftDataChegada.setText(passagem.getChegadaData());
            tftHoraChegada.setText(passagem.getChegadaHora());
            tctPortaoAeroportoChegada.setText(passagem.getChegadaPortao());
            tctPassagemEscalas.setText(passagem.getEscalasVoo());
            desabilitarPassagem();
            btnSalvarPassagem.setEnabled(false);
            flag = true;

        }//fim do if
        else {
            if (tctNumeroPassagem.isValid()) {
                msg = msg + "Passagem não encontrada!,\n Por favor Entre com outro número de passagem\n";
            }
            flag = true;
        }

        if (flag == false && tctNumeroPassagem.isValid()) {
            msg = msg + "Nenhum Passagem Cadastrada!\n";

            btnSalvarPassagem.setEnabled(true);
        }

        if (msg != "") {
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_btnPesquisarPassagemActionPerformed

    private void btnSairPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairPassagemActionPerformed
        this.PanelPassagemBotoes.setVisible(false);
        this.PainelGuiasPassagem.setVisible(false);

        this.dispose();
    }//GEN-LAST:event_btnSairPassagemActionPerformed

    private void btnLimparPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPassagemActionPerformed
        limparPassagem();

        /*
         tctNumeroPassagem.setText(null);
         tctNomePassageiro.setText(null);
         tftRgPassagem.setText(null);
        
         //carro.setBiCombustivel(rbBiCombustivelSim.isSelected() ? "sim": "não");
        
         //rbConfirmada.setSelected(false);
         //rbDisponivel.setSelected(false);
         //rbReservada.setSelected(false);
        
        
         bgStatus.clearSelection();
        
         tctNumeroVoo.setText(null);
         tctPassagemNumeroAssento.setText(null);
         cbxClasse.setSelectedIndex(-1);
         tctCiaAereaPassagem.setText(null);
         tftPassagemTarifaTotal.setText(null);
         tctAeroportoPartida.setText(null);
         tctSiglaAeroportoPartida.setText(null);
         tftDataPartida.setText(null);
         tftHoraPartida.setText(null);
         tctPortaoAeroportoPartida.setText(null);
         tctAeroportoChegada.setText(null);
         tctSiglaAeroportoChegada.setText(null);
         tftDataChegada.setText(null);
         tftHoraChegada.setText(null);
         tctPortaoAeroportoChegada.setText(null);
         tctPassagemEscalas.setText(null);
         */
    }//GEN-LAST:event_btnLimparPassagemActionPerformed

    private void btnExcluirPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPassagemActionPerformed
        boolean flag = false;

        for (int i = 0; i < arrayPass.size(); i++) {

            if (tctNumeroPassagem.getText().trim().equals(arrayPass.get(i).getNumeroPassagem())) {
                String removidaPassagem = arrayPass.get(i).getNumeroPassagem();
                Passagem removido = arrayPass.remove(i);

                JOptionPane.showMessageDialog(this, "Passagem nº: " + removidaPassagem + " Removida!");
                btnLimparPassagem.doClick(); //Limpar tela

                flag = true;

            }//fim do if
        }// fim do for

        if (arrayPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma Passagem Cadastrada!!");
        } else if (flag == false) {
            JOptionPane.showMessageDialog(this, "Número de Passagem não Encontrado!!!");
        }
    }//GEN-LAST:event_btnExcluirPassagemActionPerformed

    private void tctNomePassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tctNomePassageiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tctNomePassageiroActionPerformed

    private void jdpDataPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdpDataPassagemActionPerformed
        dataPassagem = jdpDataPassagem.getEditor().getText();

    }//GEN-LAST:event_jdpDataPassagemActionPerformed

    private void btnEditarPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPassagemActionPerformed
        // TODO add your handling code here:
        //Status dos botões
        btnAlterarPassagem.setEnabled(true);
        btnSalvarPassagem.setEnabled(false);
        btnEditarPassagem.setEnabled(false);
        habilitarPartidaChegada();
        if (!tctNomePassageiro.isEditable()) {
            //msg = "Pode realizar alterações agora";
            ////      habilitarDadosPassagem();
            //  JOptionPane.showMessageDialog(this, msg,"", JOptionPane.INFORMATION_MESSAGE );
        }
        btnAlterarPassagem.setEnabled(true);
        btnEditarPassagem.setEnabled(false);
    }//GEN-LAST:event_btnEditarPassagemActionPerformed

    private void btnAlterarPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPassagemActionPerformed
        // TODO add your handling code here:
        //btnSalvarPassageiro.doClick();
        btnSalvarPassagemActionPerformed(evt);

    }//GEN-LAST:event_btnAlterarPassagemActionPerformed

    private void btnPesquisarPassageiroRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPassageiroRGActionPerformed
        String msg = "";
        PassageiroCtrl cPassageiro = new PassageiroCtrl();
        Passageiro passageiroRG = new Passageiro();
        boolean flag = false;

        try {
            passageiroRG = PassageiroCtrl.receberPassageiroRG(tftRgPassagem.getText());
            int vCheck = Integer.parseInt(passageiroRG.getIdPassageiro());

            String vsCheck = passageiroRG.getIdPassageiro();

            if (vCheck > 0) {
                String vnome = passageiroRG.getNomePassageiro().trim();
                tctNomePassageiro.setText(vnome);

                flag = true;
            } else {
                JOptionPane.showMessageDialog(this, "Passageiro não encontrado!!!, Entre com outro RG");
                flag = true;
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaNovoPassageiro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaNovoPassageiro.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (flag == false) {
            JOptionPane.showMessageDialog(this, "Nenhum Passageiro Cadastrado!!");
            //JOptionPane.showMessageDialog(this, "Responsável não encontrado!!!, Entre com outro CPF");
        }
    }//GEN-LAST:event_btnPesquisarPassageiroRGActionPerformed

    private void btnPesquisarVooNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarVooNumeroActionPerformed
        String msg = "";
        VooCtrl cVoo = new VooCtrl();
        Voo vooPassagem = new Voo();

        boolean flag = false;

        vooPassagem = cVoo.receberVooNumero(tctNumeroVoo.getText());

        if (vooPassagem == null) {
            JOptionPane.showMessageDialog(this, "Voo não encontrado!!!, Entre com outro número");
            flag = true;
        } else {
            String vooCiaAerea = vooPassagem.getCiaAerea().trim();
            tctCiaAereaPassagem.setText(vooCiaAerea);

            //Dados Voo Partida
            String vooDataP = vooPassagem.getDataPartida().trim();
            tftDataPartida.setText(vooDataP);

            String vooHoraP = vooPassagem.getHoraPartida().trim();
            tftHoraPartida.setText(vooHoraP);

            String vooAeroportoP = vooPassagem.getAeroportoPartida().trim();
            tctAeroportoPartida.setText(vooAeroportoP);

            String vooAeroportoPSigla = vooPassagem.getAeroportoPartidaSigla().trim();
            tctSiglaAeroportoPartida.setText(vooAeroportoPSigla);

            String vooAeroportoPPortao = vooPassagem.getPortaoPartida().trim();
            tctPortaoAeroportoPartida.setText(vooAeroportoPPortao);

            //Dados Voo Chegada
            String vooDataC = vooPassagem.getDataChegada().trim();
            tftDataChegada.setText(vooDataC);

            String vooHoraC = vooPassagem.getHoraChegada().trim();
            tftHoraChegada.setText(vooHoraC);

            String vooAeroportoC = vooPassagem.getAeroportoChegada().trim();
            tctAeroportoChegada.setText(vooAeroportoC);

            String vooAeroportoCSigla = vooPassagem.getAeroportoChegadaSigla().trim();
            tctSiglaAeroportoChegada.setText(vooAeroportoCSigla);

            String vooAeroportoCPortao = vooPassagem.getPortaoChegada().trim();
            tctPortaoAeroportoChegada.setText(vooAeroportoCPortao);

            //Dados Voo Escala
            String vooEscalasPassagem = vooPassagem.getEscalasVoo().trim();
            tctPassagemEscalas.setText(vooEscalasPassagem);

            valorPassagemE = parseFloat(vooPassagem.getTarifaE());
            valorPassagemB = parseFloat(vooPassagem.getTarifaB());
            valorPassagemF = parseFloat(vooPassagem.getTarifaF());
            btnCalcularTarifa.setEnabled(true);
            flag = true;
        }

        if (flag == false) {
            JOptionPane.showMessageDialog(this, "Nenhum Voo Cadastrado!!");

        }

    }//GEN-LAST:event_btnPesquisarVooNumeroActionPerformed

    private void btnGerarNumeroPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarNumeroPassagemActionPerformed
        PassagemCtrl cPassagem = new PassagemCtrl();
        int numeroPassagem = cPassagem.receberNumeroPassagem() + 10;
        tctNumeroPassagem.setText("" + numeroPassagem);
    }//GEN-LAST:event_btnGerarNumeroPassagemActionPerformed

    private void btnCalcularTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTarifaActionPerformed
        //PassagemCtrl cPassagem = new PassagemCtrl();
        String msg = "";
        int vNumeroPassagem = 0;
        if (!tctNumeroVoo.equals("")) {
            vNumeroPassagem = parseInt(tctNumeroVoo.getText());
        }
        //float vlPassagem = 0;
        System.out.println("Numero da passagem atual: " + vNumeroPassagem);

        if (vNumeroPassagem != 0) {
            if (cbxClasse.getSelectedItem() == "Economica") {
                //vlPassagem = cPassagem.recebeValorClasseVoo("Disponivel");
                tftPassagemTarifaTotal.setText("" + valorPassagemE);
                //msg = "Preço da passagem Classe Economica = R$ " + valorPassagemE;
            } else if (cbxClasse.getSelectedItem() == "Empresarial") {
                //vlPassagem = cPassagem.recebeValorClasseVoo("Disponivel");
                tftPassagemTarifaTotal.setText("" + valorPassagemB);
                //msg = "Preço da passagem Classe Empresarial = R$ " + valorPassagemB;
            } else if (cbxClasse.getSelectedItem() == "Primeira") {
                //vlPassagem = cPassagem.recebeValorClasseVoo("Disponivel");
                tftPassagemTarifaTotal.setText("" + valorPassagemF);
                //msg = "Preço da passagem Primeira Classe = R$ " + valorPassagemF;
            } else {
                msg = "Escolha a classe da passagem!";
            }

        } else {
            msg = "Entre com um número de voo!";
        }
        if (msg != "") {
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_btnCalcularTarifaActionPerformed

    private void cbxClasseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxClasseItemStateChanged
        if (tctNumeroVoo.isValid()) {
            btnCalcularTarifa.doClick();
        }
    }//GEN-LAST:event_cbxClasseItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaNovaPassagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PainelGuiasPassagem;
    private javax.swing.JPanel PainelPassageiro;
    private javax.swing.JPanel PainelPassagemChegada;
    private javax.swing.JPanel PainelPassagemEscalas;
    private javax.swing.JPanel PainelPassagemPartida;
    private javax.swing.JPanel PainelPassagemTarifas;
    private javax.swing.JPanel PainelPassagemTitulo;
    private javax.swing.JPanel PanelPassagemBotoes;
    private javax.swing.ButtonGroup bgStatus;
    private static javax.swing.JButton btnAlterarPassagem;
    private static javax.swing.JButton btnCalcularTarifa;
    private javax.swing.JButton btnEditarPassagem;
    private javax.swing.JButton btnExcluirPassagem;
    private static javax.swing.JButton btnGerarNumeroPassagem;
    private javax.swing.JButton btnLimparPassagem;
    private static javax.swing.JButton btnPesquisarPassageiroRG;
    private javax.swing.JButton btnPesquisarPassagem;
    private static javax.swing.JButton btnPesquisarVooNumero;
    private javax.swing.JButton btnSairPassagem;
    private javax.swing.JButton btnSalvarPassagem;
    private javax.swing.JComboBox cbxClasse;
    private org.jdesktop.swingx.JXDatePicker jdpDataPassagem;
    private javax.swing.JLabel lblAeroportoPartidaPassagem;
    private javax.swing.JLabel lblCiaAereaPassagem;
    private javax.swing.JLabel lblDataPartidaPassagem;
    private javax.swing.JLabel lblDataPassagem;
    private javax.swing.JLabel lblHoraPartidaPassagem;
    private javax.swing.JLabel lblNumeroPassagem;
    private javax.swing.JLabel lblNumeroVooPassagem;
    private javax.swing.JLabel lblPassagemAeroportoChegada;
    private javax.swing.JLabel lblPassagemAssentoNumero;
    private javax.swing.JLabel lblPassagemDataChegada;
    private javax.swing.JLabel lblPassagemEscalas;
    private javax.swing.JLabel lblPassagemEscalasObs;
    private javax.swing.JLabel lblPassagemHoraChegada;
    private javax.swing.JLabel lblPassagemNome;
    private javax.swing.JLabel lblPassagemPortaoChegada;
    private javax.swing.JLabel lblPassagemSiglaAeroportoChegada;
    private javax.swing.JLabel lblPassagemStatus;
    private javax.swing.JLabel lblPassagemTarifa;
    private javax.swing.JLabel lblPassagemTarifaE;
    private javax.swing.JLabel lblPortaoPartidaPassagem;
    private javax.swing.JLabel lblRgPassagem;
    private javax.swing.JLabel lblSiglaAeroportoPartidaPassagem;
    private javax.swing.JLabel lblTelaPassagem;
    private javax.swing.JLabel lblTituloTelaPassagem;
    private javax.swing.JRadioButton rbConfirmada;
    private javax.swing.JRadioButton rbDisponivel;
    private javax.swing.JRadioButton rbReservada;
    private javax.swing.JScrollPane scrPassagemObservacao;
    private static javax.swing.JTextField tctAeroportoChegada;
    private static javax.swing.JTextField tctAeroportoPartida;
    private static javax.swing.JTextField tctCiaAereaPassagem;
    private static javax.swing.JTextField tctNomePassageiro;
    private static javax.swing.JTextField tctNumeroPassagem;
    private static javax.swing.JTextField tctNumeroVoo;
    private static javax.swing.JTextField tctPassagemEscalas;
    private static javax.swing.JTextField tctPassagemNumeroAssento;
    private javax.swing.JTextArea tctPassagemObservacao;
    private static javax.swing.JTextField tctPortaoAeroportoChegada;
    private static javax.swing.JTextField tctPortaoAeroportoPartida;
    private static javax.swing.JTextField tctSiglaAeroportoChegada;
    private static javax.swing.JTextField tctSiglaAeroportoPartida;
    private javax.swing.JFormattedTextField tftDataChegada;
    private javax.swing.JFormattedTextField tftDataPartida;
    private javax.swing.JFormattedTextField tftHoraChegada;
    private javax.swing.JFormattedTextField tftHoraPartida;
    private javax.swing.JFormattedTextField tftPassagemTarifaTotal;
    private javax.swing.JFormattedTextField tftRgPassagem;
    // End of variables declaration//GEN-END:variables

    private void limparPassagem() {
        tctNumeroPassagem.setText(null);
        tctNomePassageiro.setText(null);
        tftRgPassagem.setText(null);

        //carro.setBiCombustivel(rbBiCombustivelSim.isSelected() ? "sim": "não");
        //rbConfirmada.setSelected(false);
        //rbDisponivel.setSelected(false);
        //rbReservada.setSelected(false);
        bgStatus.clearSelection();

        tctNumeroVoo.setText(null);
        tctPassagemNumeroAssento.setText(null);
        cbxClasse.setSelectedIndex(-1);
        tctCiaAereaPassagem.setText(null);
        tftPassagemTarifaTotal.setText(null);
        tctAeroportoPartida.setText(null);
        tctSiglaAeroportoPartida.setText(null);
        tftDataPartida.setText(null);
        tftHoraPartida.setText(null);
        tctPortaoAeroportoPartida.setText(null);
        tctAeroportoChegada.setText(null);
        tctSiglaAeroportoChegada.setText(null);
        tftDataChegada.setText(null);
        tftHoraChegada.setText(null);
        tctPortaoAeroportoChegada.setText(null);
        tctPassagemEscalas.setText(null);

    }

    private void habilitarPassagem() {
        tctNumeroPassagem.setEditable(true);
        jdpDataPassagem.setEditable(true);
        tctNomePassageiro.setEditable(true);
        tftRgPassagem.setEditable(true);

        //carro.setBiCombustivel(rbBiCombustivelSim.isSelected() ? "sim": "não");
        //rbConfirmada.setSelected(false);
        //rbDisponivel.setSelected(false);
        //rbReservada.setSelected(false);
        rbDisponivel.setEnabled(true);
        rbReservada.setEnabled(true);
        rbConfirmada.setEnabled(true);

        tctNumeroVoo.setEditable(true);
        tctPassagemNumeroAssento.setEditable(true);
        //cbxClasse.setSelectedIndex(-1);
        cbxClasse.setEditable(true);
        tctCiaAereaPassagem.setEditable(true);
        tftPassagemTarifaTotal.setEditable(true);
        tctAeroportoPartida.setEditable(true);
        tctSiglaAeroportoPartida.setEditable(true);
        tftDataPartida.setEditable(true);
        tftHoraPartida.setEditable(true);
        tctPortaoAeroportoPartida.setEditable(true);
        tctAeroportoChegada.setEditable(true);
        tctSiglaAeroportoChegada.setEditable(true);
        tftDataChegada.setEditable(true);
        tftHoraChegada.setEditable(true);
        tctPortaoAeroportoChegada.setEditable(true);
        tctPassagemEscalas.setEditable(true);
    }

    private void desabilitarPassagem() {
        tctNumeroPassagem.setEditable(false);
        jdpDataPassagem.setEditable(false);
        tctNomePassageiro.setEditable(false);
        tftRgPassagem.setEditable(false);

        //carro.setBiCombustivel(rbBiCombustivelSim.isSelected() ? "sim": "não");
        //rbConfirmada.setSelected(false);
        //rbDisponivel.setSelected(false);
        //rbReservada.setSelected(false);
        rbDisponivel.setEnabled(false);
        rbReservada.setEnabled(false);
        rbConfirmada.setEnabled(false);

        tctNumeroVoo.setEditable(false);
        tctPassagemNumeroAssento.setEditable(false);
        //cbxClasse.setSelectedIndex(-1);
        cbxClasse.setEditable(false);
        tctCiaAereaPassagem.setEditable(false);
        tftPassagemTarifaTotal.setEditable(false);
        tctAeroportoPartida.setEditable(false);
        tctSiglaAeroportoPartida.setEditable(false);
        tftDataPartida.setEditable(false);
        tftHoraPartida.setEditable(false);
        tctPortaoAeroportoPartida.setEditable(false);
        tctAeroportoChegada.setEditable(false);
        tctSiglaAeroportoChegada.setEditable(false);
        tftDataChegada.setEditable(false);
        tftHoraChegada.setEditable(false);
        tctPortaoAeroportoChegada.setEditable(false);
        tctPassagemEscalas.setEditable(false);
        tctPassagemEscalas.setEditable(false);
    }

    private void desabilitarPartidaChegada() {
        //VooPassagem
        //btnPesquisarVooNumero.setEnabled(false);
        btnCalcularTarifa.setEnabled(false);
        tctCiaAereaPassagem.setEditable(false);
        //btnPesquisarPassageiroRG.setEnabled(false);
        //btnGerarNumeroPassagem.setEnabled(false);
        tctNumeroPassagem.setEditable(false);
        tctNomePassageiro.setEditable(false);

        //Partida
        tctAeroportoPartida.setEditable(false);
        tctSiglaAeroportoPartida.setEditable(false);
        tftDataPartida.setEditable(false);
        tftHoraPartida.setEditable(false);
        tctPortaoAeroportoPartida.setEditable(false);
        //Chegada
        tctAeroportoChegada.setEditable(false);
        tctSiglaAeroportoChegada.setEditable(false);
        tftDataChegada.setEditable(false);
        tftHoraChegada.setEditable(false);
        tctPortaoAeroportoChegada.setEditable(false);
        //Escalas
        tctPassagemEscalas.setEditable(false);
        tctPassagemObservacao.setEditable(true);
    }

    private void habilitarPartidaChegada() {
        //VooPassagem
        btnPesquisarVooNumero.setEnabled(true);
        btnCalcularTarifa.setEnabled(true);
        //tctCiaAereaPassagem.setEditable(true);
        btnPesquisarPassageiroRG.setEnabled(true);
        btnGerarNumeroPassagem.setEnabled(true);
        tctNumeroVoo.setEditable(true);
        jdpDataPassagem.setEditable(true);
        tftRgPassagem.setEditable(true);
        cbxClasse.setEnabled(true);
        tctPassagemNumeroAssento.setEditable(true);
        tftPassagemTarifaTotal.setEditable(true);
        rbDisponivel.setEnabled(true);
        rbReservada.setEnabled(true);
        rbConfirmada.setEnabled(true);

        //Escalas
        tctPassagemObservacao.setEditable(true);

    }

}
