/*
 * Este Software tem Objetivo Educacional
 * Para fins de aprendizagem e avaliacao na
 * Na Disciplina de Programacao Orientada a Objetos - Avancada
 *  do Curso de Analise de Sistemas da Fatec - Ipiranga
 * Ano 2016 - Janeiro a Junho 
 * Aluno Decio Antonio de Carvalho  * 
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Aeronave;
import Control.ValidaCampos;
/**
 *
 * @author deciodecarvalho
 */
public class TelaAeronave extends javax.swing.JInternalFrame {

    public static ArrayList<model.Aeronave> arrayAero;
    public static boolean temAero;
    
    /**
    * Instanciando objeto Cliente
    */
    
    
    /**
     * Creates new form TelaCliente
     */
       public TelaAeronave() {
        
        
        initComponents();
        if (!temAero){
            arrayAero = new ArrayList<>();
            temAero = true;
        }
        
        //inicalizando valores de variáveis de tela
        tftClasseEconomica.setText("0");
        tftClasseEmpresarial.setText("0");
        tftPrimeiraClasse.setText("0");
               
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelClienteTitulo = new javax.swing.JPanel();
        lblTituloTelaPassageiro = new javax.swing.JLabel();
        lblTelaAeronave = new javax.swing.JLabel();
        JPanelClienteBotoes = new javax.swing.JPanel();
        btnSalvarAeronave = new javax.swing.JButton();
        btnPesquisarAeronave = new javax.swing.JButton();
        btnSairPassageiro = new javax.swing.JButton();
        btnLimparAeronave = new javax.swing.JButton();
        btnExcluirAeronave = new javax.swing.JButton();
        btnEditarAeronave = new javax.swing.JButton();
        btnAlterarAeronave = new javax.swing.JButton();
        PainelAeronaveVoo = new javax.swing.JPanel();
        lblModeloAeronave = new javax.swing.JLabel();
        tctModeloAeronave = new javax.swing.JTextField();
        lblPrefixoAeronave = new javax.swing.JLabel();
        lblFabricanteAeronave = new javax.swing.JLabel();
        tctFabricanteAeronave = new javax.swing.JTextField();
        lblClasse1 = new javax.swing.JLabel();
        tftClasseEconomica = new javax.swing.JFormattedTextField();
        lblClasse2 = new javax.swing.JLabel();
        tftClasseEmpresarial = new javax.swing.JFormattedTextField();
        lblClasse3 = new javax.swing.JLabel();
        tftPrimeiraClasse = new javax.swing.JFormattedTextField();
        tftPrefixoAeronave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelClienteTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTituloTelaPassageiro.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTituloTelaPassageiro.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloTelaPassageiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTelaPassageiro.setText("Aeronave");

        lblTelaAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voo 40x40.png"))); // NOI18N

        javax.swing.GroupLayout JPanelClienteTituloLayout = new javax.swing.GroupLayout(JPanelClienteTitulo);
        JPanelClienteTitulo.setLayout(JPanelClienteTituloLayout);
        JPanelClienteTituloLayout.setHorizontalGroup(
            JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteTituloLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(lblTelaAeronave)
                .addGap(31, 31, 31)
                .addComponent(lblTituloTelaPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        JPanelClienteTituloLayout.setVerticalGroup(
            JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelaAeronave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteTituloLayout.createSequentialGroup()
                        .addComponent(lblTituloTelaPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        JPanelClienteBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalvarAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvarAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSalvarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarGreen_1.png"))); // NOI18N
        btnSalvarAeronave.setText("Salvar");
        btnSalvarAeronave.setToolTipText("Salvar Alterações");
        btnSalvarAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalvarAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvarAeronave.setIconTextGap(2);
        btnSalvarAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSalvarAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSalvarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAeronaveActionPerformed(evt);
            }
        });

        btnPesquisarAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnPesquisarAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnPesquisarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lupaVermelha 40x40.png"))); // NOI18N
        btnPesquisarAeronave.setText("Pesquisar");
        btnPesquisarAeronave.setToolTipText("Entre com prefixo da Aeronave para pesquisar.");
        btnPesquisarAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPesquisarAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPesquisarAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPesquisarAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnPesquisarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarAeronaveActionPerformed(evt);
            }
        });

        btnSairPassageiro.setBackground(new java.awt.Color(204, 204, 204));
        btnSairPassageiro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSairPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairPassageiro.setText("Voltar");
        btnSairPassageiro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSairPassageiro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSairPassageiro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSairPassageiro.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairPassageiroActionPerformed(evt);
            }
        });

        btnLimparAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLimparAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/oopsRed.png"))); // NOI18N
        btnLimparAeronave.setText("Limpar");
        btnLimparAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimparAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLimparAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLimparAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnLimparAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparAeronaveActionPerformed(evt);
            }
        });

        btnExcluirAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnExcluirAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnExcluirAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/excluir 40x40 vermelho.png"))); // NOI18N
        btnExcluirAeronave.setText("Excluir");
        btnExcluirAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExcluirAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnExcluirAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnExcluirAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnExcluirAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAeronaveActionPerformed(evt);
            }
        });

        btnEditarAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnEditarAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEditarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inserir.png"))); // NOI18N
        btnEditarAeronave.setText("Editar");
        btnEditarAeronave.setToolTipText("Editar Alterações");
        btnEditarAeronave.setDefaultCapable(false);
        btnEditarAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditarAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditarAeronave.setIconTextGap(1);
        btnEditarAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnEditarAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnEditarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAeronaveActionPerformed(evt);
            }
        });

        btnAlterarAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnAlterarAeronave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAlterarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarRed.png"))); // NOI18N
        btnAlterarAeronave.setText("Alterar");
        btnAlterarAeronave.setToolTipText("Alterar Dados");
        btnAlterarAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAlterarAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAlterarAeronave.setIconTextGap(0);
        btnAlterarAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAlterarAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnAlterarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarAeronaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelClienteBotoesLayout = new javax.swing.GroupLayout(JPanelClienteBotoes);
        JPanelClienteBotoes.setLayout(JPanelClienteBotoesLayout);
        JPanelClienteBotoesLayout.setHorizontalGroup(
            JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarAeronave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSairPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JPanelClienteBotoesLayout.setVerticalGroup(
            JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSairPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PainelAeronaveVoo.setBorder(javax.swing.BorderFactory.createTitledBorder("Aeronave - Voo"));
        PainelAeronaveVoo.setToolTipText("");

        lblModeloAeronave.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblModeloAeronave.setForeground(new java.awt.Color(102, 102, 102));
        lblModeloAeronave.setText("Modelo:");

        tctModeloAeronave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctModeloAeronave.setForeground(new java.awt.Color(51, 51, 51));
        tctModeloAeronave.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPrefixoAeronave.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPrefixoAeronave.setForeground(new java.awt.Color(102, 102, 102));
        lblPrefixoAeronave.setText("Prefixo :");

        lblFabricanteAeronave.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblFabricanteAeronave.setForeground(new java.awt.Color(102, 102, 102));
        lblFabricanteAeronave.setText("Fabricante: ");

        tctFabricanteAeronave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctFabricanteAeronave.setForeground(new java.awt.Color(51, 51, 51));
        tctFabricanteAeronave.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblClasse1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblClasse1.setForeground(new java.awt.Color(102, 102, 102));
        lblClasse1.setText("Classe Economica: ");

        tftClasseEconomica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##0"))));
        tftClasseEconomica.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftClasseEconomica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftClasseEconomicaActionPerformed(evt);
            }
        });

        lblClasse2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblClasse2.setForeground(new java.awt.Color(102, 102, 102));
        lblClasse2.setText("Classe Empresarial:  ");

        tftClasseEmpresarial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        tftClasseEmpresarial.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftClasseEmpresarial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftClasseEmpresarialActionPerformed(evt);
            }
        });

        lblClasse3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblClasse3.setForeground(new java.awt.Color(102, 102, 102));
        lblClasse3.setText("Classe Primeira: ");

        tftPrimeiraClasse.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##0"))));
        tftPrimeiraClasse.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftPrimeiraClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftPrimeiraClasseActionPerformed(evt);
            }
        });

        tftPrefixoAeronave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftPrefixoAeronave.setForeground(new java.awt.Color(51, 51, 51));
        tftPrefixoAeronave.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout PainelAeronaveVooLayout = new javax.swing.GroupLayout(PainelAeronaveVoo);
        PainelAeronaveVoo.setLayout(PainelAeronaveVooLayout);
        PainelAeronaveVooLayout.setHorizontalGroup(
            PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAeronaveVooLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModeloAeronave)
                    .addComponent(lblClasse1)
                    .addComponent(lblClasse2)
                    .addComponent(lblClasse3)
                    .addComponent(lblFabricanteAeronave)
                    .addComponent(lblPrefixoAeronave))
                .addGap(18, 18, 18)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tftPrefixoAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tctModeloAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftClasseEconomica, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftClasseEmpresarial, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftPrimeiraClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tctFabricanteAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        PainelAeronaveVooLayout.setVerticalGroup(
            PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAeronaveVooLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModeloAeronave)
                    .addComponent(tctModeloAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFabricanteAeronave)
                    .addComponent(tctFabricanteAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrefixoAeronave)
                    .addComponent(tftPrefixoAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClasse1)
                    .addComponent(tftClasseEconomica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClasse2)
                    .addComponent(tftClasseEmpresarial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelAeronaveVooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClasse3)
                    .addComponent(tftPrimeiraClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PainelAeronaveVoo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPanelClienteBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanelClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelAeronaveVoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelClienteBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairPassageiroActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairPassageiroActionPerformed

    private void btnPesquisarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarAeronaveActionPerformed
        boolean flag = false;
        
       for(int i = 0; i < arrayAero.size(); i++){
       System.out.println("Estou no for da Aeronave \n"
               + "Este é o valor de tela do modelo:"+tftPrefixoAeronave.getText().trim()
               + "\n"
               + "Este é o valor dentro do Array:"+arrayAero.get(i).getPrefixo()
               + "");
       if(tftPrefixoAeronave.getText().trim().equals(arrayAero.get(i).getPrefixo())){
       //if(tctModeloAeronave.getText().trim().equals(arrayAero.get(i).getModelo())){
       tctModeloAeronave.setText(arrayAero.get(i).getModelo());
       tftPrefixoAeronave.setText(arrayAero.get(i).getPrefixo());
       tftClasseEconomica.setText(arrayAero.get(i).getSeatEconomyClasse()+"");
       tftClasseEmpresarial.setText(arrayAero.get(i).getSeatBusinesClasse()+"");
       tftPrimeiraClasse.setText(arrayAero.get(i).getSeatFirstClasse()+"");
       tctFabricanteAeronave.setText(arrayAero.get(i).getFabricante());
       
       flag = true;
       
        }//fim do if
       }// fim do for
       
       if(arrayAero.isEmpty())
            JOptionPane.showMessageDialog(this,"Nenhum Aeronave Cadastrada!!");
       else if (flag == false)
            JOptionPane.showMessageDialog(this, "Aeronave não encontrada!!!");   
       
    }//GEN-LAST:event_btnPesquisarAeronaveActionPerformed

    private void btnSalvarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAeronaveActionPerformed

        int id1 = arrayAero.size();
        id1++;
        String id = id1+"";
        Aeronave objAero;
        objAero = new Aeronave();

        /**
         * Preenchimento objeto objAero (Aeronave)
         */
        objAero.setIdAeronave(id);
        objAero.setPrefixo(tftPrefixoAeronave.getText());
        objAero.setSeatEconomyClasse(Integer.parseInt(tftClasseEconomica.getText()));
        objAero.setSeatFirstClasse(Integer.parseInt(tftPrimeiraClasse.getText()));
        objAero.setSeatBusinesClasse(Integer.parseInt(tftClasseEmpresarial.getText()));
        objAero.setModelo(tctModeloAeronave.getText());
        objAero.setFabricante(tctFabricanteAeronave.getText());
        
        String msg;
        msg = "";

        /**
         * 
         * Validações para o Form Aeronave (objAero)
         * 
         */
        boolean validaModelo = ValidaCampos.validaVazio(tctModeloAeronave.getText().trim());
        boolean validaPrefixo = ValidaCampos.validaVazio(tftPrefixoAeronave.getText().trim());
        boolean validaClasseE = ValidaCampos.validaNumeroVazio(Integer.parseInt(tftClasseEconomica.getText().trim()));
        boolean validaClasseP = ValidaCampos.validaNumeroVazio(Integer.parseInt(tftPrimeiraClasse.getText().trim()));
        boolean validaClasseB = ValidaCampos.validaNumeroVazio(Integer.parseInt(tftClasseEmpresarial.getText().trim()));
        boolean validaFabricante = ValidaCampos.validaVazio(tctFabricanteAeronave.getText());
        

        if (validaModelo) {
        } else {
            msg = msg + "Campo Modelo Vazio" + "\n";
        }

        if (validaPrefixo) {
        } else {
            msg = msg + "Campo Prefixo Vazio" + "\n";
        }
        
        if (validaClasseE) {
        } else {
            msg = msg + "Campo Classe Economica invalido: "+ tftClasseEconomica.getText() + "\n";
            this.tftClasseEconomica.setText(null);
        }
        
        if (validaClasseP) {
        } else {
            msg = msg + "Campo Classe Primeira invalido: "+ tftPrimeiraClasse.getText() + "\n";
            this.tftPrimeiraClasse.setText(null);
        }
        
        if (validaClasseB) {
        } else {
            msg = msg + "Campo Classe Empresarial invalido: "+ tftClasseEmpresarial.getText() + "\n";
            this.tftClasseEmpresarial.setText(null);
        }
        
        if (validaFabricante) {
        } else {
            msg = msg + "Campo Fabricante Vazio" + "\n";
        }
        
                
        if ("".equals(msg)){
            msg = "Dados Enviados ao banco de dados do sistema!";
            boolean resultadoAeronave = arrayAero.add(objAero);
            JOptionPane.showMessageDialog(this, msg,"Dados Enviados", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Resposta se adcionou nova Aeronave? "+resultadoAeronave+" id:"+id);
            btnLimparAeronave.doClick();
        }
        else{
            JOptionPane.showMessageDialog(this, msg,"Campo Inválido ou vazio", JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_btnSalvarAeronaveActionPerformed

    private void tftClasseEconomicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftClasseEconomicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftClasseEconomicaActionPerformed

    private void btnLimparAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparAeronaveActionPerformed
       tctModeloAeronave.setText(null);
       tftPrefixoAeronave.setText(null);
       tctFabricanteAeronave.setText(null);
       tftClasseEconomica.setText("0");
       tftClasseEmpresarial.setText("0");
       tftPrimeiraClasse.setText("0");
    }//GEN-LAST:event_btnLimparAeronaveActionPerformed

    private void tftClasseEmpresarialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftClasseEmpresarialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftClasseEmpresarialActionPerformed

    private void tftPrimeiraClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftPrimeiraClasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftPrimeiraClasseActionPerformed

    private void btnExcluirAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAeronaveActionPerformed
       boolean flag = false;
        
       for(int i = 0; i < arrayAero.size(); i++){
       
       if(tftPrefixoAeronave.getText().trim().equals(arrayAero.get(i).getPrefixo())){
           String removidaAeronave = arrayAero.get(i).getPrefixo();
           Aeronave removida = arrayAero.remove(i);
           
       JOptionPane.showMessageDialog(this,"Aeronave: "+removidaAeronave+" Removida!");
       btnLimparAeronave.doClick(); //Limpar tela
            
       flag = true;
       
        }//fim do if
       }// fim do for
       
       if(arrayAero.isEmpty())
            JOptionPane.showMessageDialog(this,"Nenhum Aeronave Cadastrada!!");
       else if (flag == false)
            JOptionPane.showMessageDialog(this, "Aeronave não encontrada!!!, Entre com outro prefixo.");   
    }//GEN-LAST:event_btnExcluirAeronaveActionPerformed

    private void btnEditarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAeronaveActionPerformed
        // TODO add your handling code here:
        //Status dos botões
        btnAlterarAeronave.setEnabled(true);
        btnSalvarAeronave.setEnabled(false);
        btnEditarAeronave.setEnabled(false);

        if (!tctModeloAeronave.isEditable()) {
            //msg = "Pode realizar alterações agora";
            ////habilitarDadosAeronave();
            //  JOptionPane.showMessageDialog(this, msg,"", JOptionPane.INFORMATION_MESSAGE );
        }
        btnAlterarAeronave.setEnabled(true);
        btnEditarAeronave.setEnabled(false);
    }//GEN-LAST:event_btnEditarAeronaveActionPerformed

    private void btnAlterarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarAeronaveActionPerformed
        // TODO add your handling code here:
        //btnSalvarPassageiro.doClick();
        btnSalvarAeronaveActionPerformed(evt);
    }//GEN-LAST:event_btnAlterarAeronaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaAeronave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelClienteBotoes;
    private javax.swing.JPanel JPanelClienteTitulo;
    private javax.swing.JPanel PainelAeronaveVoo;
    private static javax.swing.JButton btnAlterarAeronave;
    private javax.swing.JButton btnEditarAeronave;
    private javax.swing.JButton btnExcluirAeronave;
    private javax.swing.JButton btnLimparAeronave;
    private javax.swing.JButton btnPesquisarAeronave;
    private javax.swing.JButton btnSairPassageiro;
    private javax.swing.JButton btnSalvarAeronave;
    private javax.swing.JLabel lblClasse1;
    private javax.swing.JLabel lblClasse2;
    private javax.swing.JLabel lblClasse3;
    private javax.swing.JLabel lblFabricanteAeronave;
    private javax.swing.JLabel lblModeloAeronave;
    private javax.swing.JLabel lblPrefixoAeronave;
    private javax.swing.JLabel lblTelaAeronave;
    private javax.swing.JLabel lblTituloTelaPassageiro;
    private static javax.swing.JTextField tctFabricanteAeronave;
    private static javax.swing.JTextField tctModeloAeronave;
    private javax.swing.JFormattedTextField tftClasseEconomica;
    private javax.swing.JFormattedTextField tftClasseEmpresarial;
    private static javax.swing.JTextField tftPrefixoAeronave;
    private javax.swing.JFormattedTextField tftPrimeiraClasse;
    // End of variables declaration//GEN-END:variables

    
}
