/*
 * Este Software tem Objetivo Educacional
 * Para fins de aprendizagem e avaliacao na
 * Na Disciplina de Programacao Orientada a Objetos - Avancada
 *  do Curso de Analise de Sistemas da Fatec - Ipiranga
 * Ano 2016 - Janeiro a Junho 
 * Aluno Decio Antonio de Carvalho  * 
 */
package view;

import Control.ClienteCtrl;
import Control.Util;
import Control.ValidaCampos;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import model.Cliente;

/**
 *
 * @author deciodecarvalho
 */
public class TelaCliente extends javax.swing.JFrame {

    public static ArrayList<model.Cliente> arrayCli;
    public static boolean temCliente;
    private static String dataNascimentoCliente, dataHojeCliente;
    private static Date dataNasc, dataInit, dtCliente;
    private static Date hojeCliente;
    private static Date calNascimentoCliente;
    private static SimpleDateFormat sdfNascimentoCliente;
    private int dataIntNascimentoCliente;
    
  
    /**
    * Instanciando objeto Cliente
    */
    
    
    /**
     * Creates new form TelaCliente
     */
       public TelaCliente() {
        
        
        initComponents();
        tftCep.setText(null);
                              
        if(!temCliente){
            arrayCli = new ArrayList<>();
            temCliente = true;
        }
        
       //inicalizando valores de variáveis de tela
        cbxUF.setSelectedIndex(-1);
        btnAlterarCliente.setEnabled(false);
        dtCliente = new Date();
        
        jspNascimento.setValue(dtCliente);    
        hojeCliente = new Date();
        dataHojeCliente = Util.DataFormatada(hojeCliente);
        sdfNascimentoCliente = new SimpleDateFormat("dd/MM/yyyy");
    try { 
        hojeCliente = sdfNascimentoCliente.parse(dataHojeCliente);
    } catch (ParseException ex) {
        Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelClienteTitulo = new javax.swing.JPanel();
        lblTituloTelaClientes = new javax.swing.JLabel();
        lblTelaNomesTitulo = new javax.swing.JLabel();
        JPanelClienteCadastro = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        lblRG = new javax.swing.JLabel();
        lblNascimento = new javax.swing.JLabel();
        Date dtIntegradaNP = new Date();

        SpinnerDateModel smIntegradaNP = new 
        SpinnerDateModel(dtIntegradaNP,null,null,Calendar.MONTH + Calendar.DAY_OF_MONTH 
            + Calendar.YEAR );
        jspNascimento = 
        jspNascimento = new javax.swing.JSpinner(smIntegradaNP);
        JSpinner.DateEditor deIntegradaNP = new 
        JSpinner.DateEditor(jspNascimento,"dd/MM/yyyy");
        jspNascimento.setEditor(deIntegradaNP);
        lblEmail = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        tftCPF = new javax.swing.JFormattedTextField();
        tftEmail = new javax.swing.JFormattedTextField();
        tctNome = new javax.swing.JTextField();
        tftRG = new javax.swing.JFormattedTextField();
        tctEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        tctBairro = new javax.swing.JTextField();
        lblBairro1 = new javax.swing.JLabel();
        tctCidade = new javax.swing.JTextField();
        lblRG1 = new javax.swing.JLabel();
        tftCep = new javax.swing.JFormattedTextField();
        lblBairro2 = new javax.swing.JLabel();
        cbxUF = new javax.swing.JComboBox();
        lblTelefone = new javax.swing.JLabel();
        tftTelefone = new javax.swing.JFormattedTextField();
        lblNumero = new javax.swing.JLabel();
        tctNumeroEndCliente = new javax.swing.JTextField();
        btnPesquisarCep = new javax.swing.JButton();
        JPanelClienteBotoes = new javax.swing.JPanel();
        btnLimparCliente = new javax.swing.JButton();
        btnSairCliente = new javax.swing.JButton();
        btnPesquisarCliente = new javax.swing.JButton();
        btnSalvarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelClienteTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTituloTelaClientes.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTituloTelaClientes.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloTelaClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTelaClientes.setText("Cliente");

        lblTelaNomesTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cliente 80x80.jpg"))); // NOI18N

        javax.swing.GroupLayout JPanelClienteTituloLayout = new javax.swing.GroupLayout(JPanelClienteTitulo);
        JPanelClienteTitulo.setLayout(JPanelClienteTituloLayout);
        JPanelClienteTituloLayout.setHorizontalGroup(
            JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTelaNomesTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloTelaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(350, 350, 350))
        );
        JPanelClienteTituloLayout.setVerticalGroup(
            JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloTelaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteTituloLayout.createSequentialGroup()
                .addComponent(lblTelaNomesTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPanelClienteCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblNome.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(102, 102, 102));
        lblNome.setText("Nome:");

        lblEnd.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblEnd.setForeground(new java.awt.Color(102, 102, 102));
        lblEnd.setText("Endereço:");

        lblRG.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblRG.setForeground(new java.awt.Color(102, 102, 102));
        lblRG.setText("RG:");

        lblNascimento.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNascimento.setForeground(new java.awt.Color(102, 102, 102));
        lblNascimento.setText("Nascimento:");

        jspNascimento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jspNascimento.setToolTipText("Escolha Dia, Mês e Ano");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(102, 102, 102));
        lblEmail.setText("Email:");

        lblCpf.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(102, 102, 102));
        lblCpf.setText("CPF:");

        try {
            tftCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftCPF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        tftEmail.setForeground(new java.awt.Color(51, 51, 51));
        tftEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tftEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        tctNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctNome.setForeground(new java.awt.Color(51, 51, 51));
        tctNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        try {
            tftRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftRG.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        tctEndereco.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctEndereco.setForeground(new java.awt.Color(51, 51, 51));
        tctEndereco.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblBairro.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(102, 102, 102));
        lblBairro.setText("Bairro");

        tctBairro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctBairro.setForeground(new java.awt.Color(51, 51, 51));
        tctBairro.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblBairro1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblBairro1.setForeground(new java.awt.Color(102, 102, 102));
        lblBairro1.setText("Cidade:");

        tctCidade.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctCidade.setForeground(new java.awt.Color(51, 51, 51));
        tctCidade.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblRG1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblRG1.setForeground(new java.awt.Color(102, 102, 102));
        lblRG1.setText("CEP: ");

        try {
            tftCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftCep.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        lblBairro2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblBairro2.setForeground(new java.awt.Color(102, 102, 102));
        lblBairro2.setText("UF: ");

        cbxUF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbxUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));

        lblTelefone.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(102, 102, 102));
        lblTelefone.setText("Telefone: ");

        try {
            tftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftTelefone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        lblNumero.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(102, 102, 102));
        lblNumero.setText("Número:");

        tctNumeroEndCliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        btnPesquisarCep.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        btnPesquisarCep.setText("<html><span style=\"font-size:10px;\" color=Green\">Pesquisar</span></html>\n");
        btnPesquisarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelClienteCadastroLayout = new javax.swing.GroupLayout(JPanelClienteCadastro);
        JPanelClienteCadastro.setLayout(JPanelClienteCadastroLayout);
        JPanelClienteCadastroLayout.setHorizontalGroup(
            JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                        .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                                .addComponent(lblBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tctBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                                .addComponent(lblBairro1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tctCidade)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addGap(18, 18, 18)
                                .addComponent(tftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                                .addComponent(lblBairro2)
                                .addGap(18, 18, 18)
                                .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblRG1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tftCep, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarCep, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelClienteCadastroLayout.createSequentialGroup()
                        .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelClienteCadastroLayout.createSequentialGroup()
                                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail)
                                    .addComponent(lblRG, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tftRG, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tftEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelClienteCadastroLayout.createSequentialGroup()
                                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelClienteCadastroLayout.createSequentialGroup()
                                        .addComponent(lblEnd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tctEndereco))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelClienteCadastroLayout.createSequentialGroup()
                                        .addComponent(lblNome)
                                        .addGap(18, 18, 18)
                                        .addComponent(tctNome, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                                        .addComponent(lblNascimento)
                                        .addGap(18, 18, 18)
                                        .addComponent(jspNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                                        .addComponent(lblNumero)
                                        .addGap(18, 18, 18)
                                        .addComponent(tctNumeroEndCliente)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JPanelClienteCadastroLayout.setVerticalGroup(
            JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblNascimento)
                    .addComponent(tctNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnd)
                    .addComponent(tctEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero)
                    .addComponent(tctNumeroEndCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(tctBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRG1)
                    .addComponent(tftCep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro1)
                    .addComponent(tctCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro2)
                    .addComponent(cbxUF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tftEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTelefone)
                        .addComponent(tftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCpf))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRG)
                        .addComponent(tftRG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        JPanelClienteBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnLimparCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLimparCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/oopsRed.png"))); // NOI18N
        btnLimparCliente.setText("Limpar");
        btnLimparCliente.setIconTextGap(0);
        btnLimparCliente.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLimparCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btnLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparClienteActionPerformed(evt);
            }
        });

        btnSairCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnSairCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSairCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairCliente.setText("Voltar");
        btnSairCliente.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSairCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairClienteActionPerformed(evt);
            }
        });

        btnPesquisarCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnPesquisarCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lupaVermelha 40x40.png"))); // NOI18N
        btnPesquisarCliente.setText("Pesquisar");
        btnPesquisarCliente.setToolTipText("Entre com CPF do Cliente para pesquisar");
        btnPesquisarCliente.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPesquisarCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });

        btnSalvarCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvarCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSalvarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarGreen_1.png"))); // NOI18N
        btnSalvarCliente.setText("Salvar");
        btnSalvarCliente.setToolTipText("Salvar Alterações");
        btnSalvarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvarCliente.setIconTextGap(0);
        btnSalvarCliente.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSalvarCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });

        btnExcluirCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnExcluirCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/excluir 40x40 vermelho.png"))); // NOI18N
        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnExcluirCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        btnAlterarCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnAlterarCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarRed.png"))); // NOI18N
        btnAlterarCliente.setText("Alterar");
        btnAlterarCliente.setToolTipText("Alterar Dados");
        btnAlterarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAlterarCliente.setIconTextGap(2);
        btnAlterarCliente.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAlterarCliente.setPreferredSize(new java.awt.Dimension(100, 50));
        btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelClienteBotoesLayout = new javax.swing.GroupLayout(JPanelClienteBotoes);
        JPanelClienteBotoes.setLayout(JPanelClienteBotoesLayout);
        JPanelClienteBotoesLayout.setHorizontalGroup(
            JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimparCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnSairCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPanelClienteBotoesLayout.setVerticalGroup(
            JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLimparCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSairCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JPanelClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 847, Short.MAX_VALUE)
                    .addComponent(JPanelClienteBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelClienteTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelClienteBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairClienteActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairClienteActionPerformed

    private void btnLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparClienteActionPerformed
      
      tctBairro.setText(null);
      tftCep.setText(null);
      tctCidade.setText(null);
      cbxUF.setSelectedIndex(-1);
      tftCPF.setText(null);
      tftRG.setText(null);
      tftEmail.setText(null);
      tftTelefone.setText(null);
      //tftNascimento.setText(null);
      tctNome.setText(null);
      tctNumeroEndCliente.setText(null);
      tctEndereco.setText(null);
      
    }//GEN-LAST:event_btnLimparClienteActionPerformed

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
      ClienteCtrl cCliente = new ClienteCtrl();
      Cliente objCli;
      objCli = new Cliente();
      
      /**
      * Serializar o idCliente Provisório
      * 
      */
      int idCliente = arrayCli.size();
      idCliente++;
      String id = idCliente+"";
      
      /**
       * Preenchimento do objCli com os valores de tela
       * 
      */
      objCli.setNome(tctNome.getText().trim());
      dataNascimentoCliente = Util.DataFormatadaS(jspNascimento.getValue().toString());
      dataIntNascimentoCliente = Util.DtAmericana(jspNascimento.getValue().toString());
      objCli.setNascimento(dataNascimentoCliente);

      //objCli.setNascimento(tftNascimento.getText());
      objCli.setEndereco(tctEndereco.getText().trim());
      objCli.setNumero(tctNumeroEndCliente.getText());
      objCli.setBairro(tctBairro.getText().trim());
      objCli.setEmail(tftEmail.getText().trim());
      objCli.setCep(tftCep.getText());
      objCli.setTelefone(tftTelefone.getText());
      objCli.setRg(tftRG.getText());
      objCli.setCpf(tftCPF.getText());
      objCli.setCidade(tctCidade.getText().trim());
      
      //objCli.setUf(Arrays.toString(cbxUF.getSelectedObjects()));
      objCli.setUf((String)cbxUF.getSelectedItem());
      //objCli.setUf(cbxUF.getSelectedObjects());
      
      String nome = tctNome.getText().trim();
      //String nasc = tftNascimento.getText();
      String end = tctEndereco.getText().trim();
      String numero = tctNumeroEndCliente.getText();
      String bairro = tctBairro.getText().trim();
      String email = tftEmail.getText().trim();
      
      String telefone = tftTelefone.getText();
      String rg = tftRG.getText();
      String cpf = tftCPF.getText();
      String cep = tftCep.getText();
      String cidade = tctCidade.getText().trim();
      String uf = Arrays.toString(cbxUF.getSelectedObjects());
       
      //int i = arrayCli.indexOf(tctNome.getText ());

      String msg;
        msg = "";
              
        boolean validaNome = ValidaCampos.validaVazio(nome); 
        //boolean validaData = ValidaCampos.validaData(nasc);
        boolean validaDatajsp = ValidaCampos.validaDataNascimento(dataIntNascimentoCliente);
        boolean validaEndereco = ValidaCampos.validaVazio(end);
        boolean validaNumeroEnd = ValidaCampos.validaVazio(numero);
        boolean validaBairro = ValidaCampos.validaVazio(bairro);
        boolean validaRG = ValidaCampos.validaRG(rg);
        boolean validaCPF = ValidaCampos.validaCPF(cpf);
        boolean validaEmail = ValidaCampos.validaEmail(email);
        boolean validaTelefone = ValidaCampos.validaTelefone(telefone);
        boolean validaCep = ValidaCampos.validaCEP(cep);
        boolean validaCidade = ValidaCampos.validaVazio(cidade);
        boolean validaUF = ValidaCampos.validaVazioComboBox(uf);    
        
        if (validaNome) {
            } else {
              msg = msg + "Campo Nome Vazio" + "\n";
            }
        
         if (validaDatajsp) {
        } else {
            msg = msg + "Campo Nascimento Inválido" + "\n";
        }
         
        
         /*if (validaData) {
            } else {
              msg = msg + "Campo Nascimento inválido: "+ nasc + "\n";
              this.tftNascimento.setText(null);
            }
        */
         
         
        if (validaEndereco) {
            } else {
              msg = msg + "Campo Endereço Vazio" + "\n";
            }
        
        if (validaNumeroEnd) {
            } else {
              msg = msg + "Campo Número Endereço Vazio" + "\n";
            }
        
        if (validaBairro){
            }else{
            msg = msg + "Campo Bairro Vazio" + "\n";
        }
         
        if (validaCep) {
            } else {
              msg = msg + "Campo CEP inválido: "+ cep + "\n";
              this.tftCep.setText(null);
            }
        
        if (validaCidade) {
            } else {
              msg = msg + "Campo Cidade Vazio" + "\n";
            }
              
        if (validaUF) {
            } else {
              msg = msg + "Campo UF Vazio" + "\n";
            }
        
        if (validaEmail) {
            } else {
              msg = msg +"Campo E-mail inválido: "+ email + "\n";
              this.tftEmail.setText(null);
            }
        
        if (validaTelefone) {
            } else {
              msg = msg +"Campo Telefone inválido: "+ telefone + "\n";
              this.tftTelefone.setText(null);
            }
        if (validaRG) {
            } else {
              msg = msg + "Campo RG inválido: "+ rg + "\n";
              this.tftRG.setText(null);
            }  
        
        if (validaCPF) {
            } else {
              msg = msg + "Campo CPF inválido: "+ cpf + "\n";
              this.tftCPF.setText(null);
            }
          
          
        if ("".equals(msg)){
            msg = "Dados Enviados ao banco de dados do sistema!";
            
        if (btnSalvarCliente.isEnabled()){
                 boolean resultadoCliente = arrayCli.add(objCli);
                try {
            cCliente.receberCliente(objCli);
            } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
// System.out.println("Resposta se adicionou novo Passageiro? "+resultadoPassageiro+" id:"+id);
            }
            else{
            
                boolean flag = false;

                for(int i = 0; i < arrayCli.size(); i++){

                    if(tftCPF.getText().trim().equals(arrayCli.get(i).getCpf())){
                        String removidoCliente = arrayCli.get(i).getNome();
                        Cliente removido = arrayCli.remove(i);

                        //JOptionPane.showMessageDialog(this,"Passageiro de RG: "+removidoPassageiro+" Removido!");
                        boolean resultadoAlterouCliente = arrayCli.add(objCli);
                        btnLimparCliente.doClick(); //Limpar tela

                        flag = true;

                    }//fim do if
                }// fim do for
           
        }
            JOptionPane.showMessageDialog(this, msg,"Dados Enviados", JOptionPane.INFORMATION_MESSAGE);
            //PainelCliente.requestFocus(true); 
            btnLimparCliente.doClick();
            btnSairCliente.doClick();
        
         }
        else{
            JOptionPane.showMessageDialog(this, msg,"Campo Inválido ou vazio", JOptionPane.ERROR_MESSAGE );
        }
         
         
    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
        btnSalvarCliente.setEnabled(false);
        btnAlterarCliente.setEnabled(true);
        boolean flag = false;
        
        for(int i = 0; i < arrayCli.size(); i++){
          
                /**
                 * Tratamento do campo tipo jSpinner
                 */
                String sdataNascimento = arrayCli.get(i).getNascimento();
                
                try {
                    calNascimentoCliente = Util.retornaData(sdataNascimento);
                } catch (Exception ex) {
                    Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                jspNascimento.setValue(calNascimentoCliente);
            
            
            /*
            System.out.println("Estou no for do Cliente \n"
               + "Este é o valor de tela do CPF:"+tftCPF.getText().trim()
               + "\n"
               + "Este é o valor dentro do Array:"+arrayCli.get(i).getCpf()
               + "\n"
               + "Este é o valor dentro do Array UF:"+arrayCli.get(i).getUf()
               + "");
            */
            
            if(tftCPF.getText().equals(arrayCli.get(i).getCpf())){
            System.out.println(""+i);
              
            tctBairro.setText(arrayCli.get(i).getBairro() );
            tftCep.setText(arrayCli.get(i).getCep());
            tctCidade.setText(arrayCli.get(i).getCidade());
            
            //Como pesquisar comboBox
            cbxUF.setSelectedItem(arrayCli.get(i).getUf());
           
            tftCPF.setText(arrayCli.get(i).getCpf());
            tftRG.setText(arrayCli.get(i).getRg());
            tftEmail.setText(arrayCli.get(i).getEmail());
            //tftNascimento.setText(arrayCli.get(i).getNascimento());
            tftTelefone.setText(arrayCli.get(i).getTelefone());
            tctNome.setText(arrayCli.get(i).getNome());
            tctEndereco.setText(arrayCli.get(i).getEndereco());
            tctNumeroEndCliente.setText(arrayCli.get(i).getNumero());
              flag = true;
          }  
        }
        
        if(arrayCli.isEmpty()){
            JOptionPane.showMessageDialog(this,"Nenhum Cliente Cadastrado!!");
            btnAlterarCliente.setEnabled(false);
            btnSalvarCliente.setEnabled(true);
        }
       else if (flag == false){
            JOptionPane.showMessageDialog(this, "Cliente não encontrado!!!, Entre com outro CPF"); 
            btnAlterarCliente.setEnabled(false);
            btnSalvarCliente.setEnabled(true);
       }
                  
    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        boolean flag = false;

        for(int i = 0; i < arrayCli.size(); i++){

            if(tftCPF.getText().trim().equals(arrayCli.get(i).getCpf())){
                String removidoCliente = arrayCli.get(i).getCpf();
                Cliente removido = arrayCli.remove(i);

                JOptionPane.showMessageDialog(this,"Cliente: "+removidoCliente+" Removido!");
                btnLimparCliente.doClick(); //Limpar tela

                flag = true;

            }//fim do if
        }// fim do for

        if(arrayCli.isEmpty()){
        JOptionPane.showMessageDialog(this,"Nenhum Cliente Cadastrado!!");
        }
        else if (flag == false){
        JOptionPane.showMessageDialog(this, "Cliente não Encontrado!!!");
        }
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClienteActionPerformed
        // TODO add your handling code here:
        //btnSalvarPassageiro.doClick();
        btnSalvarClienteActionPerformed(evt);
    }//GEN-LAST:event_btnAlterarClienteActionPerformed

    private void btnPesquisarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCepActionPerformed
        // TODO add your handling code here:
        if(Util.VerificaEndereco(tftCep.getText())){
            tctEndereco.setText(Util.vEnd);
            tctBairro.setText(Util.vBairro);
            tctCidade.setText(Util.vCidade);
            cbxUF.setSelectedItem(Util.vUf);
            tctNumeroEndCliente.grabFocus(); //coloca foco no campo numero endereço após buscar cep.
        }
        
    }//GEN-LAST:event_btnPesquisarCepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelClienteBotoes;
    private javax.swing.JPanel JPanelClienteCadastro;
    private javax.swing.JPanel JPanelClienteTitulo;
    private static javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnLimparCliente;
    private javax.swing.JButton btnPesquisarCep;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JButton btnSairCliente;
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.JComboBox cbxUF;
    private javax.swing.JSpinner jspNascimento;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblBairro1;
    private javax.swing.JLabel lblBairro2;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblRG1;
    private javax.swing.JLabel lblTelaNomesTitulo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTituloTelaClientes;
    private javax.swing.JTextField tctBairro;
    private javax.swing.JTextField tctCidade;
    private javax.swing.JTextField tctEndereco;
    private static javax.swing.JTextField tctNome;
    private javax.swing.JTextField tctNumeroEndCliente;
    private javax.swing.JFormattedTextField tftCPF;
    private javax.swing.JFormattedTextField tftCep;
    private javax.swing.JFormattedTextField tftEmail;
    private javax.swing.JFormattedTextField tftRG;
    private javax.swing.JFormattedTextField tftTelefone;
    // End of variables declaration//GEN-END:variables

    
}
