/*
 * Este Software tem Objetivo Educacional
 * Para fins de aprendizagem e avaliacao na
 * Na Disciplina de Programacao Orientada a Objetos - Avancada
 * do Curso de Analise de Sistemas da Fatec - Ipiranga
 * Ano 2016 - Janeiro a Junho 
 * Aluno Decio Antonio de Carvalho  * 
 */
package view;
import java.util.ArrayList;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Passagem;
import Control.Util;
import Control.ValidaCampos;
//import static view.TelaPassagem.arrayPass;


/**
 *
 * @author deciodecarvalho
 */
public class TelaNovaPassagem extends javax.swing.JFrame {
    
public static ArrayList<model.Passagem> arrayPass;  
//Para ser utilizado em todas as partes do programa
public static boolean temPassagemNova; 

private static String dataPassagem, dataHojePassagem;
private static Date dataPs;
private static Date hojePassagem;
private static SimpleDateFormat sdfHojePassagem;

        

    /**
     * Creates new form TelaVazia
     */
    public TelaNovaPassagem() {
        initComponents();
        cbxClasse.setSelectedIndex(-1);
        if (!temPassagemNova){
        arrayPass = new ArrayList<>();
        temPassagemNova = true;
        }
        
        jdpDataPassagem.setDate(Calendar.getInstance().getTime());
        jdpDataPassagem.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        hojePassagem = new Date();
        dataHojePassagem = Util.DataFormatada(hojePassagem);
        sdfHojePassagem = new SimpleDateFormat("dd/MM/yyyy");
    try { 
        hojePassagem = sdfHojePassagem.parse(dataHojePassagem);
    } catch (ParseException ex) {
        Logger.getLogger(TelaNovaPassagem.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgStatus = new javax.swing.ButtonGroup();
        PainelPassagemTitulo = new javax.swing.JPanel();
        lblTelaPassagem = new javax.swing.JLabel();
        lblTituloTelaPassagem = new javax.swing.JLabel();
        PainelGuiasPassagem = new javax.swing.JTabbedPane();
        PainelPassageiro = new javax.swing.JPanel();
        tctNomePassageiro = new javax.swing.JTextField();
        lblPassagemNome = new javax.swing.JLabel();
        lblRgPassagem = new javax.swing.JLabel();
        tftRgPassagem = new javax.swing.JFormattedTextField();
        tctNumeroPassagem = new javax.swing.JTextField();
        lblNumeroPassagem = new javax.swing.JLabel();
        lblDataPassagem = new javax.swing.JLabel();
        jdpDataPassagem = new org.jdesktop.swingx.JXDatePicker();
        PainelPassagemTarifas = new javax.swing.JPanel();
        lblPassagemTarifaE = new javax.swing.JLabel();
        tftPassagemTarifaTotal = new javax.swing.JFormattedTextField();
        lblNumeroVooPassagem = new javax.swing.JLabel();
        tctNumeroVoo = new javax.swing.JTextField();
        lblCiaAereaPassagem = new javax.swing.JLabel();
        tctCiaAereaPassagem = new javax.swing.JTextField();
        lblPassagemAssentoNumero = new javax.swing.JLabel();
        tctPassagemNumeroAssento = new javax.swing.JTextField();
        lblPassagemTarifa = new javax.swing.JLabel();
        lblPassagemStatus = new javax.swing.JLabel();
        cbxClasse = new javax.swing.JComboBox();
        rbDisponivel = new javax.swing.JRadioButton();
        rbReservada = new javax.swing.JRadioButton();
        rbConfirmada = new javax.swing.JRadioButton();
        PainelPassagemPartida = new javax.swing.JPanel();
        lblHoraPartidaPassagem = new javax.swing.JLabel();
        tftHoraPartida = new javax.swing.JFormattedTextField();
        tftDataPartida = new javax.swing.JFormattedTextField();
        lblDataPartidaPassagem = new javax.swing.JLabel();
        lblAeroportoPartidaPassagem = new javax.swing.JLabel();
        tctAeroportoPartida = new javax.swing.JTextField();
        lblSiglaAeroportoPartidaPassagem = new javax.swing.JLabel();
        tctSiglaAeroportoPartida = new javax.swing.JTextField();
        lblPortaoPartidaPassagem = new javax.swing.JLabel();
        tctPortaoAeroportoPartida = new javax.swing.JTextField();
        PainelPassagemChegada = new javax.swing.JPanel();
        lblPassagemHoraChegada = new javax.swing.JLabel();
        tftHoraChegada = new javax.swing.JFormattedTextField();
        tftDataChegada = new javax.swing.JFormattedTextField();
        lblPassagemDataChegada = new javax.swing.JLabel();
        lblPassagemAeroportoChegada = new javax.swing.JLabel();
        tctAeroportoChegada = new javax.swing.JTextField();
        lblPassagemSiglaAeroportoChegada = new javax.swing.JLabel();
        tctSiglaAeroportoChegada = new javax.swing.JTextField();
        lblPassagemPortaoChegada = new javax.swing.JLabel();
        tctPortaoAeroportoChegada = new javax.swing.JTextField();
        PainelPassagemEscalas = new javax.swing.JPanel();
        lblPassagemEscalas = new javax.swing.JLabel();
        tctPassagemEscalas = new javax.swing.JTextField();
        lblPassagemEscalasObs = new javax.swing.JLabel();
        scrPassagemObservacao = new javax.swing.JScrollPane();
        txtPassagemObservacao = new javax.swing.JTextArea();
        PanelPassagemBotoes = new javax.swing.JPanel();
        btnSalvarPassagem = new javax.swing.JButton();
        btnPesquisarPassagem = new javax.swing.JButton();
        btnSairPassagem = new javax.swing.JButton();
        btnLimparPassagem = new javax.swing.JButton();
        btnExcluirPassagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelPassagemTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTelaPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/passagem 40x40.jpg"))); // NOI18N

        lblTituloTelaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTituloTelaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloTelaPassagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTelaPassagem.setText("Passagem Aérea");

        javax.swing.GroupLayout PainelPassagemTituloLayout = new javax.swing.GroupLayout(PainelPassagemTitulo);
        PainelPassagemTitulo.setLayout(PainelPassagemTituloLayout);
        PainelPassagemTituloLayout.setHorizontalGroup(
            PainelPassagemTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemTituloLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(lblTelaPassagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloTelaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        PainelPassagemTituloLayout.setVerticalGroup(
            PainelPassagemTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPassagemTituloLayout.createSequentialGroup()
                .addGroup(PainelPassagemTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelPassagemTituloLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTelaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassagemTituloLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblTituloTelaPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        PainelGuiasPassagem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        PainelPassageiro.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem Aérea - Passageiro"));

        tctNomePassageiro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctNomePassageiro.setForeground(new java.awt.Color(51, 51, 51));
        tctNomePassageiro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctNomePassageiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctNomePassageiroMouseReleased(evt);
            }
        });
        tctNomePassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tctNomePassageiroActionPerformed(evt);
            }
        });

        lblPassagemNome.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemNome.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemNome.setText("Passageiro :");

        lblRgPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblRgPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblRgPassagem.setText("RG :");

        try {
            tftRgPassagem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftRgPassagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftRgPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftRgPassagemActionPerformed(evt);
            }
        });

        tctNumeroPassagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctNumeroPassagem.setForeground(new java.awt.Color(51, 51, 51));
        tctNumeroPassagem.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctNumeroPassagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctNumeroPassagemMouseReleased(evt);
            }
        });

        lblNumeroPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumeroPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblNumeroPassagem.setText("Número Passagem : ");

        lblDataPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblDataPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblDataPassagem.setText("Data Passagem : ");

        jdpDataPassagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jdpDataPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdpDataPassagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPassageiroLayout = new javax.swing.GroupLayout(PainelPassageiro);
        PainelPassageiro.setLayout(PainelPassageiroLayout);
        PainelPassageiroLayout.setHorizontalGroup(
            PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassageiroLayout.createSequentialGroup()
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassageiroLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblNumeroPassagem)
                        .addGap(30, 30, 30)
                        .addComponent(tctNumeroPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassageiroLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDataPassagem)
                            .addComponent(lblRgPassagem)
                            .addComponent(lblPassagemNome))
                        .addGap(30, 30, 30)
                        .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tftRgPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdpDataPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tctNomePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        PainelPassageiroLayout.setVerticalGroup(
            PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassageiroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctNumeroPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroPassagem))
                .addGap(18, 18, 18)
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdpDataPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataPassagem))
                .addGap(18, 18, 18)
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctNomePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemNome))
                .addGap(21, 21, 21)
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftRgPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRgPassagem))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        PainelGuiasPassagem.addTab("Passageiro", PainelPassageiro);

        PainelPassagemTarifas.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem - Empresa / Tarifas Voos"));

        lblPassagemTarifaE.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemTarifaE.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemTarifaE.setText("Classe : ");

        tftPassagemTarifaTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        tftPassagemTarifaTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tftPassagemTarifaTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftPassagemTarifaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftPassagemTarifaTotalActionPerformed(evt);
            }
        });

        lblNumeroVooPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumeroVooPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblNumeroVooPassagem.setText("Número Voo:");

        tctNumeroVoo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctNumeroVoo.setForeground(new java.awt.Color(51, 51, 51));
        tctNumeroVoo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctNumeroVoo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctNumeroVooMouseReleased(evt);
            }
        });

        lblCiaAereaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblCiaAereaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblCiaAereaPassagem.setText("Cia Aérea: ");

        tctCiaAereaPassagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctCiaAereaPassagem.setForeground(new java.awt.Color(51, 51, 51));
        tctCiaAereaPassagem.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPassagemAssentoNumero.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemAssentoNumero.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemAssentoNumero.setText("Assento Número : ");

        tctPassagemNumeroAssento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPassagemNumeroAssento.setForeground(new java.awt.Color(51, 51, 51));
        tctPassagemNumeroAssento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tctPassagemNumeroAssento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tctPassagemNumeroAssentoMouseReleased(evt);
            }
        });

        lblPassagemTarifa.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemTarifa.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemTarifa.setText(" Tarifa Total R$ : ");

        lblPassagemStatus.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemStatus.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemStatus.setText("Status :");

        cbxClasse.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbxClasse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economica", "Empresarial", "Primeira" }));

        bgStatus.add(rbDisponivel);
        rbDisponivel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbDisponivel.setText("Disponível");

        bgStatus.add(rbReservada);
        rbReservada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbReservada.setText("Reservada");

        bgStatus.add(rbConfirmada);
        rbConfirmada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbConfirmada.setText("Confirmada");

        javax.swing.GroupLayout PainelPassagemTarifasLayout = new javax.swing.GroupLayout(PainelPassagemTarifas);
        PainelPassagemTarifas.setLayout(PainelPassagemTarifasLayout);
        PainelPassagemTarifasLayout.setHorizontalGroup(
            PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblNumeroVooPassagem)
                        .addGap(36, 36, 36)
                        .addComponent(tctNumeroVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblCiaAereaPassagem)
                        .addGap(36, 36, 36)
                        .addComponent(tctCiaAereaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassagemTarifaE)
                            .addComponent(lblPassagemAssentoNumero)
                            .addComponent(lblPassagemTarifa))
                        .addGap(36, 36, 36)
                        .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tctPassagemNumeroAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftPassagemTarifaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lblPassagemStatus)
                        .addGap(33, 33, 33)
                        .addComponent(rbDisponivel)
                        .addGap(31, 31, 31)
                        .addComponent(rbReservada)
                        .addGap(33, 33, 33)
                        .addComponent(rbConfirmada)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        PainelPassagemTarifasLayout.setVerticalGroup(
            PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemTarifasLayout.createSequentialGroup()
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctNumeroVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroVooPassagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tctCiaAereaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCiaAereaPassagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemTarifaE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassagemAssentoNumero)
                    .addComponent(tctPassagemNumeroAssento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassagemTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftPassagemTarifaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(PainelPassagemTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassagemStatus)
                    .addComponent(rbDisponivel)
                    .addComponent(rbReservada)
                    .addComponent(rbConfirmada))
                .addContainerGap())
        );

        PainelGuiasPassagem.addTab("Passagem", PainelPassagemTarifas);

        PainelPassagemPartida.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem - Voo Partida"));
        PainelPassagemPartida.setToolTipText("");

        lblHoraPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblHoraPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblHoraPartidaPassagem.setText("Hora Partida: ");

        tftHoraPartida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tftHoraPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        try {
            tftDataPartida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftDataPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftDataPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftDataPartidaActionPerformed(evt);
            }
        });

        lblDataPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblDataPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblDataPartidaPassagem.setText("Data Partida: ");

        lblAeroportoPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblAeroportoPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblAeroportoPartidaPassagem.setText("Aeroporto Partida: ");

        tctAeroportoPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctAeroportoPartida.setForeground(new java.awt.Color(51, 51, 51));
        tctAeroportoPartida.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblSiglaAeroportoPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblSiglaAeroportoPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblSiglaAeroportoPartidaPassagem.setText("Sigla Aeroporto Partida: ");

        tctSiglaAeroportoPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctSiglaAeroportoPartida.setForeground(new java.awt.Color(51, 51, 51));
        tctSiglaAeroportoPartida.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPortaoPartidaPassagem.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPortaoPartidaPassagem.setForeground(new java.awt.Color(102, 102, 102));
        lblPortaoPartidaPassagem.setText("Gate / Portão:");

        tctPortaoAeroportoPartida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPortaoAeroportoPartida.setForeground(new java.awt.Color(51, 51, 51));
        tctPortaoAeroportoPartida.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout PainelPassagemPartidaLayout = new javax.swing.GroupLayout(PainelPassagemPartida);
        PainelPassagemPartida.setLayout(PainelPassagemPartidaLayout);
        PainelPassagemPartidaLayout.setHorizontalGroup(
            PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemPartidaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSiglaAeroportoPartidaPassagem)
                    .addComponent(lblPortaoPartidaPassagem)
                    .addComponent(lblAeroportoPartidaPassagem)
                    .addComponent(lblHoraPartidaPassagem)
                    .addComponent(lblDataPartidaPassagem))
                .addGap(35, 35, 35)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tctSiglaAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftHoraPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftDataPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tctPortaoAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tctAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        PainelPassagemPartidaLayout.setVerticalGroup(
            PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftDataPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataPartidaPassagem))
                .addGap(21, 21, 21)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftHoraPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraPartidaPassagem))
                .addGap(21, 21, 21)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAeroportoPartidaPassagem))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctSiglaAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSiglaAeroportoPartidaPassagem))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctPortaoAeroportoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPortaoPartidaPassagem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelGuiasPassagem.addTab("Partida", PainelPassagemPartida);

        PainelPassagemChegada.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem - Voo Chegada"));
        PainelPassagemChegada.setToolTipText("");

        lblPassagemHoraChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemHoraChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemHoraChegada.setText("Hora Chegada: ");

        tftHoraChegada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        tftHoraChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        try {
            tftDataChegada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftDataChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftDataChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftDataChegadaActionPerformed(evt);
            }
        });

        lblPassagemDataChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemDataChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemDataChegada.setText("Data Chegada: ");

        lblPassagemAeroportoChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemAeroportoChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemAeroportoChegada.setText("Aeroporto Chegada: ");

        tctAeroportoChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctAeroportoChegada.setForeground(new java.awt.Color(51, 51, 51));
        tctAeroportoChegada.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPassagemSiglaAeroportoChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemSiglaAeroportoChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemSiglaAeroportoChegada.setText("Sigla Aeroporto Partida: ");

        tctSiglaAeroportoChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctSiglaAeroportoChegada.setForeground(new java.awt.Color(51, 51, 51));
        tctSiglaAeroportoChegada.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPassagemPortaoChegada.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemPortaoChegada.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemPortaoChegada.setText("Gate / Portão:");

        tctPortaoAeroportoChegada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPortaoAeroportoChegada.setForeground(new java.awt.Color(51, 51, 51));
        tctPortaoAeroportoChegada.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout PainelPassagemChegadaLayout = new javax.swing.GroupLayout(PainelPassagemChegada);
        PainelPassagemChegada.setLayout(PainelPassagemChegadaLayout);
        PainelPassagemChegadaLayout.setHorizontalGroup(
            PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemChegadaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassagemChegadaLayout.createSequentialGroup()
                        .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassagemSiglaAeroportoChegada)
                            .addComponent(lblPassagemPortaoChegada))
                        .addGap(38, 38, 38)
                        .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tctSiglaAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tctPortaoAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelPassagemChegadaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassagemHoraChegada)
                            .addComponent(lblPassagemDataChegada)
                            .addComponent(lblPassagemAeroportoChegada))
                        .addGap(38, 38, 38)
                        .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tftDataChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftHoraChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tctAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        PainelPassagemChegadaLayout.setVerticalGroup(
            PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemChegadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftDataChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemDataChegada))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassagemHoraChegada)
                    .addComponent(tftHoraChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassagemAeroportoChegada)
                    .addComponent(tctAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tctSiglaAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemSiglaAeroportoChegada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPassagemChegadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tctPortaoAeroportoChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassagemPortaoChegada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelGuiasPassagem.addTab("Chegada", PainelPassagemChegada);

        PainelPassagemEscalas.setBorder(javax.swing.BorderFactory.createTitledBorder("Passagem - Voo Escalas"));

        lblPassagemEscalas.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemEscalas.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemEscalas.setText("Escalas: ");

        tctPassagemEscalas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPassagemEscalas.setForeground(new java.awt.Color(51, 51, 51));
        tctPassagemEscalas.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblPassagemEscalasObs.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassagemEscalasObs.setForeground(new java.awt.Color(102, 102, 102));
        lblPassagemEscalasObs.setText("Observações :");

        txtPassagemObservacao.setColumns(20);
        txtPassagemObservacao.setRows(5);
        scrPassagemObservacao.setViewportView(txtPassagemObservacao);

        javax.swing.GroupLayout PainelPassagemEscalasLayout = new javax.swing.GroupLayout(PainelPassagemEscalas);
        PainelPassagemEscalas.setLayout(PainelPassagemEscalasLayout);
        PainelPassagemEscalasLayout.setHorizontalGroup(
            PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemEscalasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassagemEscalas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassagemEscalasObs, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrPassagemObservacao)
                    .addComponent(tctPassagemEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        PainelPassagemEscalasLayout.setVerticalGroup(
            PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassagemEscalasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassagemEscalas)
                    .addComponent(tctPassagemEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPassagemEscalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassagemEscalasObs)
                    .addComponent(scrPassagemObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        PainelGuiasPassagem.addTab("Escalas", PainelPassagemEscalas);

        PanelPassagemBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalvarPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvarPassagem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSalvarPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarGreen_1.png"))); // NOI18N
        btnSalvarPassagem.setText("Salvar");
        btnSalvarPassagem.setToolTipText("Salvar Alterações");
        btnSalvarPassagem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvarPassagem.setIconTextGap(2);
        btnSalvarPassagem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSalvarPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSalvarPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPassagemActionPerformed(evt);
            }
        });

        btnPesquisarPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnPesquisarPassagem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPesquisarPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lupaVermelha 40x40.png"))); // NOI18N
        btnPesquisarPassagem.setText("Pesquisar");
        btnPesquisarPassagem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnPesquisarPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnPesquisarPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPassagemActionPerformed(evt);
            }
        });

        btnSairPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnSairPassagem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSairPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairPassagem.setText("Voltar");
        btnSairPassagem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSairPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairPassagemActionPerformed(evt);
            }
        });

        btnLimparPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparPassagem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLimparPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/oopsRed.png"))); // NOI18N
        btnLimparPassagem.setText("Limpar");
        btnLimparPassagem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnLimparPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnLimparPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPassagemActionPerformed(evt);
            }
        });

        btnExcluirPassagem.setBackground(new java.awt.Color(204, 204, 204));
        btnExcluirPassagem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnExcluirPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/excluir 40x40 vermelho.png"))); // NOI18N
        btnExcluirPassagem.setText("Excluir");
        btnExcluirPassagem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnExcluirPassagem.setPreferredSize(new java.awt.Dimension(100, 50));
        btnExcluirPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPassagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPassagemBotoesLayout = new javax.swing.GroupLayout(PanelPassagemBotoes);
        PanelPassagemBotoes.setLayout(PanelPassagemBotoesLayout);
        PanelPassagemBotoesLayout.setHorizontalGroup(
            PanelPassagemBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPassagemBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnExcluirPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimparPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSairPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPassagemBotoesLayout.setVerticalGroup(
            PanelPassagemBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPassagemBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSalvarPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesquisarPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnExcluirPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnLimparPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSairPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PanelPassagemBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelGuiasPassagem, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelPassagemTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(PainelPassagemTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelGuiasPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelPassagemBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tctNomePassageiroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctNomePassageiroMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctNomePassageiroMouseReleased

    private void tftRgPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftRgPassagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftRgPassagemActionPerformed

    private void tctNumeroPassagemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctNumeroPassagemMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctNumeroPassagemMouseReleased

    private void tftPassagemTarifaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftPassagemTarifaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftPassagemTarifaTotalActionPerformed

    private void tctNumeroVooMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctNumeroVooMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctNumeroVooMouseReleased

    private void tctPassagemNumeroAssentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tctPassagemNumeroAssentoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tctPassagemNumeroAssentoMouseReleased

    private void tftDataPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftDataPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftDataPartidaActionPerformed

    private void tftDataChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftDataChegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftDataChegadaActionPerformed

    private void btnSalvarPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPassagemActionPerformed
        Passagem objPass;
        objPass = new Passagem();
        
        String msg = "";
        String reserva = "";
                
        if (rbConfirmada.isSelected()){
        reserva = "Confirmada";
        }
        
        if (rbReservada.isSelected()){
         reserva = "Reservada";
        }
        
        if (rbDisponivel.isSelected()){
         reserva = "Disponivel";
        }
        
        
        int id1 = arrayPass.size();
        id1++;
        String id = id1+"";

        objPass.setIdPassagem(id);
        objPass.setNumeroPassagem(tctNumeroPassagem.getText());
        
        /**
         * DataPassagem
         */
        dataPassagem = jdpDataPassagem.getEditor().getText();
        objPass.setDataPassagem(dataPassagem);
        // objPass.setDataPassagem(tftDataPassagem.getText());
        
        
        objPass.setNomePassageiro(tctNomePassageiro.getText());
        objPass.setRgPassageiro(tftRgPassagem.getText());
        objPass.setReserva(reserva);
        objPass.setVooNumero(tctNumeroVoo.getText());
        objPass.setCiaAerea(tctCiaAereaPassagem.getText());
        objPass.setAssentoNumero(tctPassagemNumeroAssento.getText());
        
        /**
         * Tratamento para o ComboBox -1
         */
        if (cbxClasse.getSelectedIndex()==-1){  
        }
        else{
        objPass.setClasse(cbxClasse.getSelectedItem().toString());
        }
        
        
        objPass.setTarifa(tftPassagemTarifaTotal.getText());
        objPass.setPartidaAeroporto(tctAeroportoPartida.getText());
        objPass.setPartidaSiglaAeroporto(tctSiglaAeroportoPartida.getText());
        objPass.setPartidaData(tftDataPartida.getText());
        objPass.setPartidaHora(tftHoraPartida.getText());
        objPass.setPartidaPortao(tctPortaoAeroportoPartida.getText());

        objPass.setChegadaAeroporto(tctAeroportoChegada.getText());
        objPass.setChegadaSiglaAeroporto(tctSiglaAeroportoChegada.getText());
        objPass.setChegadaData(tftDataChegada.getText());
        objPass.setChegadaHora(tftHoraChegada.getText());
        objPass.setChegadaPortao(tctPortaoAeroportoChegada.getText());
        objPass.setEscalasVoo(tctPassagemEscalas.getText());

        //String msg;
        //msg = "";
       
        
        boolean validaNumeroPassagem = ValidaCampos.validaVazio(tctNumeroPassagem.getText());
        boolean validaNomePassageiro = ValidaCampos.validaNome(tctNomePassageiro.getText());
        boolean validaRgPassageiro = ValidaCampos.validaRG(tftRgPassagem.getText());
        boolean validaNumeroVoo = ValidaCampos.validaVazio(tctNumeroVoo.getText());
        boolean validaNumeroAssento = ValidaCampos.validaVazio(tctPassagemNumeroAssento.getText());
        boolean validaTarifaTotal = ValidaCampos.validaStringNumero(tftPassagemTarifaTotal.getText());
        boolean validaStatusPassagem = ValidaCampos.validaStatus(rbDisponivel.isSelected(),
                rbReservada.isSelected(),rbConfirmada.isSelected());
        /**
         * 
         * Validar Data Passagem
         * 
         */
        try {
            dataPs = sdfHojePassagem.parse(dataPassagem);
        } catch (ParseException ex) {
            Logger.getLogger(TelaNovoVoo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (dataPs.before(hojePassagem)) {
        msg = msg + "Campo Data Passagem inválido: "+ dataPassagem + "\n";
            dataPassagem = null;
        } else {
            
        }
        //fim validacao dataPartida
        
        if (validaNumeroPassagem) {
        } else {
            msg = msg + "Campo Número Passagem Vazio" + "\n";
        }
        if (validaNomePassageiro) {
        } else {
            msg = msg + "Campo Nome Passageiro Menor que 5 Carácteres ou Inválido" + "\n";
        }

        if (validaRgPassageiro) {
        } else {
            msg = msg + "Campo Rg Passageiro inválido" + "\n";
        }
        
        if (validaNumeroVoo) {
        } else {
            msg = msg + "Campo Número Voo Vazio" + "\n";
        }
        
        if (cbxClasse.getSelectedIndex()==-1){
         msg = msg + "Campo Classe da Passagem não selecionado: "+ "\n";
            cbxClasse.setSelectedIndex(-1);    
        }
        
        if (validaNumeroAssento) {
        } else {
            msg = msg + "Campo Número Assento Vazio" + "\n";
        }
        
        if (validaTarifaTotal) {
        } else {
            msg = msg + "Campo Tarifa Total Vazio" + "\n";
        }
        
        if (validaStatusPassagem){
            
        }else{
            msg = msg + "Status da Passagem não selecionado! "+"\n";
        }
        
        
        if ("".equals(msg)){
            msg = "Dados Enviados ao banco de dados do sistema!";
            boolean resultadoPassagem = arrayPass.add(objPass);
            JOptionPane.showMessageDialog(this, msg,"Dados Enviados", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Resposta se adcionou nova Passagem? "+resultadoPassagem+" id:"+id);
            btnLimparPassagem.doClick();
        }
        else{
            JOptionPane.showMessageDialog(this, msg,"Campo Inválido ou vazio", JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_btnSalvarPassagemActionPerformed

    private void btnPesquisarPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPassagemActionPerformed
        boolean flag = false;

        for(int i = 0; i < arrayPass.size(); i++){
            
            if(tftRgPassagem.getText().equals(arrayPass.get(i).getRgPassageiro())){

                if(arrayPass.get(i).getReserva().equals("Reservada")){
                   rbReservada.setSelected(true);
                }
                if(arrayPass.get(i).getReserva().equals("Confirmada")){
                   rbConfirmada.setSelected(true); 
                }
                if(arrayPass.get(i).getReserva().equals("Disponivel")){
                   rbDisponivel.setSelected(true); 
                }
                
                /**
                 * Tratamento do campo tipo jDatePicker
                 */
                String sdataPartida = arrayPass.get(i).getDataPassagem();
               // Date dtPartida = new Date();
                SimpleDateFormat sdf2 = new SimpleDateFormat("dd/MM/yyyyy");
                try {
                 Date dtPartida = sdf2.parse(sdataPartida);
                    jdpDataPassagem.setDate(dtPartida);
                } catch (ParseException ex) {
                    Logger.getLogger(TelaNovoVoo.class.getName()).log(Level.SEVERE, null, ex);
                }
                //fim do tratamento campo JDatePicker 




                //jdpDataPassagem
                tctNumeroPassagem.setText(arrayPass.get(i).getNumeroPassagem());
                tctNomePassageiro.setText(arrayPass.get(i).getNomePassageiro());
                tftRgPassagem.setText(arrayPass.get(i).getRgPassageiro());
                tctNumeroVoo.setText(arrayPass.get(i).getVooNumero());
                tctPassagemNumeroAssento.setText(arrayPass.get(i).getAssentoNumero());
                cbxClasse.setSelectedItem(arrayPass.get(i).getClasse());
                tctCiaAereaPassagem.setText(arrayPass.get(i).getCiaAerea());
                tftPassagemTarifaTotal.setText(arrayPass.get(i).getTarifa());
                tctAeroportoPartida.setText(arrayPass.get(i).getPartidaAeroporto());
                tctSiglaAeroportoPartida.setText(arrayPass.get(i).getPartidaSiglaAeroporto());
                
                
                tftDataPartida.setText(arrayPass.get(i).getPartidaData());
                tftHoraPartida.setText(arrayPass.get(i).getPartidaHora());
                tctPortaoAeroportoPartida.setText(arrayPass.get(i).getPartidaPortao());
                tctAeroportoChegada.setText(arrayPass.get(i).getChegadaAeroporto());
                tctSiglaAeroportoChegada.setText(arrayPass.get(i).getChegadaSiglaAeroporto());
                
                
                
                tftDataChegada.setText(arrayPass.get(i).getChegadaData());
                tftHoraChegada.setText(arrayPass.get(i).getChegadaHora());
                tctPortaoAeroportoChegada.setText(arrayPass.get(i).getChegadaPortao());
                tctPassagemEscalas.setText(arrayPass.get(i).getEscalasVoo());

                flag = true;
            }//fim do if
        }// fim do for

        if(arrayPass.isEmpty())
        JOptionPane.showMessageDialog(this,"Nenhuma Passagem Cadastrada!!");
        else if (flag == false)
        JOptionPane.showMessageDialog(this, "Passagem não encontrada!!!");
    }//GEN-LAST:event_btnPesquisarPassagemActionPerformed

    private void btnSairPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairPassagemActionPerformed
        this.PanelPassagemBotoes.setVisible(false);
        this.PainelGuiasPassagem.setVisible(false);
        
        this.dispose();
    }//GEN-LAST:event_btnSairPassagemActionPerformed

    private void btnLimparPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPassagemActionPerformed
        tctNumeroPassagem.setText(null);
        tctNomePassageiro.setText(null);
        tftRgPassagem.setText(null);
        
        //carro.setBiCombustivel(rbBiCombustivelSim.isSelected() ? "sim": "não");
        
        //rbConfirmada.setSelected(false);
        //rbDisponivel.setSelected(false);
        //rbReservada.setSelected(false);
        
        
        bgStatus.clearSelection();
        
        tctNumeroVoo.setText(null);
        tctPassagemNumeroAssento.setText(null);
        cbxClasse.setSelectedIndex(-1);
        tctCiaAereaPassagem.setText(null);
        tftPassagemTarifaTotal.setText(null);
        tctAeroportoPartida.setText(null);
        tctSiglaAeroportoPartida.setText(null);
        tftDataPartida.setText(null);
        tftHoraPartida.setText(null);
        tctPortaoAeroportoPartida.setText(null);
        tctAeroportoChegada.setText(null);
        tctSiglaAeroportoChegada.setText(null);
        tftDataChegada.setText(null);
        tftHoraChegada.setText(null);
        tctPortaoAeroportoChegada.setText(null);
        tctPassagemEscalas.setText(null);
    }//GEN-LAST:event_btnLimparPassagemActionPerformed

    private void btnExcluirPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPassagemActionPerformed
        boolean flag = false;

        for(int i = 0; i < arrayPass.size(); i++){

            if(tctNumeroPassagem.getText().trim().equals(arrayPass.get(i).getNumeroPassagem())){
                String removidaPassagem = arrayPass.get(i).getNumeroPassagem();
                Passagem removido = arrayPass.remove(i);

                JOptionPane.showMessageDialog(this,"Passagem nº: "+removidaPassagem+" Removida!");
                btnLimparPassagem.doClick(); //Limpar tela

                flag = true;

            }//fim do if
        }// fim do for

        if(arrayPass.isEmpty())
        JOptionPane.showMessageDialog(this,"Nenhuma Passagem Cadastrada!!");
        else if (flag == false)
        JOptionPane.showMessageDialog(this, "Número de Passagem não Encontrado!!!");
    }//GEN-LAST:event_btnExcluirPassagemActionPerformed

    private void tctNomePassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tctNomePassageiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tctNomePassageiroActionPerformed

    private void jdpDataPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdpDataPassagemActionPerformed
        dataPassagem = jdpDataPassagem.getEditor().getText();

    }//GEN-LAST:event_jdpDataPassagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovaPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaNovaPassagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PainelGuiasPassagem;
    private javax.swing.JPanel PainelPassageiro;
    private javax.swing.JPanel PainelPassagemChegada;
    private javax.swing.JPanel PainelPassagemEscalas;
    private javax.swing.JPanel PainelPassagemPartida;
    private javax.swing.JPanel PainelPassagemTarifas;
    private javax.swing.JPanel PainelPassagemTitulo;
    private javax.swing.JPanel PanelPassagemBotoes;
    private javax.swing.ButtonGroup bgStatus;
    private javax.swing.JButton btnExcluirPassagem;
    private javax.swing.JButton btnLimparPassagem;
    private javax.swing.JButton btnPesquisarPassagem;
    private javax.swing.JButton btnSairPassagem;
    private javax.swing.JButton btnSalvarPassagem;
    private javax.swing.JComboBox cbxClasse;
    private org.jdesktop.swingx.JXDatePicker jdpDataPassagem;
    private javax.swing.JLabel lblAeroportoPartidaPassagem;
    private javax.swing.JLabel lblCiaAereaPassagem;
    private javax.swing.JLabel lblDataPartidaPassagem;
    private javax.swing.JLabel lblDataPassagem;
    private javax.swing.JLabel lblHoraPartidaPassagem;
    private javax.swing.JLabel lblNumeroPassagem;
    private javax.swing.JLabel lblNumeroVooPassagem;
    private javax.swing.JLabel lblPassagemAeroportoChegada;
    private javax.swing.JLabel lblPassagemAssentoNumero;
    private javax.swing.JLabel lblPassagemDataChegada;
    private javax.swing.JLabel lblPassagemEscalas;
    private javax.swing.JLabel lblPassagemEscalasObs;
    private javax.swing.JLabel lblPassagemHoraChegada;
    private javax.swing.JLabel lblPassagemNome;
    private javax.swing.JLabel lblPassagemPortaoChegada;
    private javax.swing.JLabel lblPassagemSiglaAeroportoChegada;
    private javax.swing.JLabel lblPassagemStatus;
    private javax.swing.JLabel lblPassagemTarifa;
    private javax.swing.JLabel lblPassagemTarifaE;
    private javax.swing.JLabel lblPortaoPartidaPassagem;
    private javax.swing.JLabel lblRgPassagem;
    private javax.swing.JLabel lblSiglaAeroportoPartidaPassagem;
    private javax.swing.JLabel lblTelaPassagem;
    private javax.swing.JLabel lblTituloTelaPassagem;
    private javax.swing.JRadioButton rbConfirmada;
    private javax.swing.JRadioButton rbDisponivel;
    private javax.swing.JRadioButton rbReservada;
    private javax.swing.JScrollPane scrPassagemObservacao;
    private static javax.swing.JTextField tctAeroportoChegada;
    private static javax.swing.JTextField tctAeroportoPartida;
    private static javax.swing.JTextField tctCiaAereaPassagem;
    private static javax.swing.JTextField tctNomePassageiro;
    private static javax.swing.JTextField tctNumeroPassagem;
    private static javax.swing.JTextField tctNumeroVoo;
    private static javax.swing.JTextField tctPassagemEscalas;
    private static javax.swing.JTextField tctPassagemNumeroAssento;
    private static javax.swing.JTextField tctPortaoAeroportoChegada;
    private static javax.swing.JTextField tctPortaoAeroportoPartida;
    private static javax.swing.JTextField tctSiglaAeroportoChegada;
    private static javax.swing.JTextField tctSiglaAeroportoPartida;
    private javax.swing.JFormattedTextField tftDataChegada;
    private javax.swing.JFormattedTextField tftDataPartida;
    private javax.swing.JFormattedTextField tftHoraChegada;
    private javax.swing.JFormattedTextField tftHoraPartida;
    private javax.swing.JFormattedTextField tftPassagemTarifaTotal;
    private javax.swing.JFormattedTextField tftRgPassagem;
    private javax.swing.JTextArea txtPassagemObservacao;
    // End of variables declaration//GEN-END:variables
}
