/*
 * Este Software tem Objetivo Educacional
 * Para fins de aprendizagem e avaliacao na
 * Na Disciplina de Programa��o Orientada a Objetos - Avan�ada
 *  do Curso de Analise de Sistemas da Fatec - Ipiranga
 * Ano 2016 - Janeiro a Junho 
 * Aluno Decio Antonio de Carvalho  * 
 */
package view;

import Control.AeronaveCtrl;
import static Control.Util.reduzString;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import model.Aeronave;

/**
 *
 * @author Décio
 */
public class TelaRelatorioAeronave extends javax.swing.JInternalFrame {

    public static String prefixoAeronave;

    /**
     * Creates new form TelaRelatorioAeronave
     */
    public TelaRelatorioAeronave() {
        initComponents();
        populaJComboBoxAeronavePrefixo();
        cbxPrefixoAeronave.setSelectedIndex(-1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaneRelAeronaveBotoes = new javax.swing.JPanel();
        btnLimparRelAeronave = new javax.swing.JButton();
        btnSairRelAeronave = new javax.swing.JButton();
        btnImprimirRelatorioAeronave = new javax.swing.JButton();
        PanelRelAeronave = new javax.swing.JTabbedPane();
        PainelRelAeronave = new javax.swing.JPanel();
        lblNumeroPrefixoAeronave = new javax.swing.JLabel();
        cbxPrefixoAeronave = new javax.swing.JComboBox();
        btnListarRelAeronave = new javax.swing.JButton();
        btnListarRelAeronavesTodas = new javax.swing.JButton();
        lblRelFotoAeronave = new javax.swing.JLabel();
        PainelRelImpressoAeronaves = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAeronave = new javax.swing.JTextArea();
        PaineRelAeronaveTitulo = new javax.swing.JPanel();
        lblTelaRelAeronave = new javax.swing.JLabel();
        lblTituloTelaRelAeronave = new javax.swing.JLabel();

        PaneRelAeronaveBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnLimparRelAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparRelAeronave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLimparRelAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/oopsRed.png"))); // NOI18N
        btnLimparRelAeronave.setText("Limpar");
        btnLimparRelAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimparRelAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLimparRelAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnLimparRelAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparRelAeronaveActionPerformed(evt);
            }
        });

        btnSairRelAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnSairRelAeronave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSairRelAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairRelAeronave.setText("Voltar");
        btnSairRelAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSairRelAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSairRelAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairRelAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairRelAeronaveActionPerformed(evt);
            }
        });

        btnImprimirRelatorioAeronave.setBackground(new java.awt.Color(204, 204, 204));
        btnImprimirRelatorioAeronave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnImprimirRelatorioAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/infraero/pdf2.png"))); // NOI18N
        btnImprimirRelatorioAeronave.setText("Imprimir em PDF");
        btnImprimirRelatorioAeronave.setToolTipText("Salvar Alterações");
        btnImprimirRelatorioAeronave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImprimirRelatorioAeronave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnImprimirRelatorioAeronave.setIconTextGap(2);
        btnImprimirRelatorioAeronave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnImprimirRelatorioAeronave.setPreferredSize(new java.awt.Dimension(100, 50));
        btnImprimirRelatorioAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirRelatorioAeronaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaneRelAeronaveBotoesLayout = new javax.swing.GroupLayout(PaneRelAeronaveBotoes);
        PaneRelAeronaveBotoes.setLayout(PaneRelAeronaveBotoesLayout);
        PaneRelAeronaveBotoesLayout.setHorizontalGroup(
            PaneRelAeronaveBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneRelAeronaveBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLimparRelAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnImprimirRelatorioAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                .addComponent(btnSairRelAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        PaneRelAeronaveBotoesLayout.setVerticalGroup(
            PaneRelAeronaveBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneRelAeronaveBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneRelAeronaveBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparRelAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimirRelatorioAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSairRelAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PainelRelAeronave.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PainelRelAeronave.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumeroPrefixoAeronave.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNumeroPrefixoAeronave.setForeground(new java.awt.Color(102, 102, 102));
        lblNumeroPrefixoAeronave.setText("Prefixo Aeronave:");
        PainelRelAeronave.add(lblNumeroPrefixoAeronave, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        cbxPrefixoAeronave.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        cbxPrefixoAeronave.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPrefixoAeronaveItemStateChanged(evt);
            }
        });
        PainelRelAeronave.add(cbxPrefixoAeronave, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 160, 30));

        btnListarRelAeronave.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnListarRelAeronave.setText("mostrar Aeronave");
        btnListarRelAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarRelAeronaveActionPerformed(evt);
            }
        });
        PainelRelAeronave.add(btnListarRelAeronave, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, 30));

        btnListarRelAeronavesTodas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnListarRelAeronavesTodas.setText("Listar todas Aeronaves");
        btnListarRelAeronavesTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarRelAeronavesTodasActionPerformed(evt);
            }
        });
        PainelRelAeronave.add(btnListarRelAeronavesTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 190, 30));

        lblRelFotoAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/aeronavesBoeing.jpg"))); // NOI18N
        PainelRelAeronave.add(lblRelFotoAeronave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 260));

        PanelRelAeronave.addTab("Relatório Aeronaves", PainelRelAeronave);

        txtAeronave.setEditable(false);
        txtAeronave.setBackground(new java.awt.Color(250, 250, 250));
        txtAeronave.setColumns(20);
        txtAeronave.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtAeronave.setRows(7);
        txtAeronave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));
        jScrollPane1.setViewportView(txtAeronave);

        javax.swing.GroupLayout PainelRelImpressoAeronavesLayout = new javax.swing.GroupLayout(PainelRelImpressoAeronaves);
        PainelRelImpressoAeronaves.setLayout(PainelRelImpressoAeronavesLayout);
        PainelRelImpressoAeronavesLayout.setHorizontalGroup(
            PainelRelImpressoAeronavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
        );
        PainelRelImpressoAeronavesLayout.setVerticalGroup(
            PainelRelImpressoAeronavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        PanelRelAeronave.addTab("Relatório Aeronaves", PainelRelImpressoAeronaves);

        PaineRelAeronaveTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTelaRelAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voo 40x40.png"))); // NOI18N

        lblTituloTelaRelAeronave.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTituloTelaRelAeronave.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloTelaRelAeronave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTelaRelAeronave.setText("Aeronaves AeroFast");

        javax.swing.GroupLayout PaineRelAeronaveTituloLayout = new javax.swing.GroupLayout(PaineRelAeronaveTitulo);
        PaineRelAeronaveTitulo.setLayout(PaineRelAeronaveTituloLayout);
        PaineRelAeronaveTituloLayout.setHorizontalGroup(
            PaineRelAeronaveTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineRelAeronaveTituloLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(lblTelaRelAeronave)
                .addGap(78, 78, 78)
                .addComponent(lblTituloTelaRelAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        PaineRelAeronaveTituloLayout.setVerticalGroup(
            PaineRelAeronaveTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaineRelAeronaveTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PaineRelAeronaveTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloTelaRelAeronave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTelaRelAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PaneRelAeronaveBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PaineRelAeronaveTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelRelAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PaineRelAeronaveTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(PaneRelAeronaveBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 75, Short.MAX_VALUE)
                    .addComponent(PanelRelAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 76, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparRelAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparRelAeronaveActionPerformed
        cbxPrefixoAeronave.setSelectedIndex(-1);
        // cbxDataPassagem.setSelectedIndex(-1);
        cbxPrefixoAeronave.setSelectedIndex(-1);
        // cbxRgPassageiroPassagem.setSelectedIndex(-1);
        txtAeronave.setText("");
    }//GEN-LAST:event_btnLimparRelAeronaveActionPerformed

    private void btnSairRelAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairRelAeronaveActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairRelAeronaveActionPerformed

    private void btnImprimirRelatorioAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirRelatorioAeronaveActionPerformed
        //criamos um documento vazio
        String msg = "";
        String tituloMsg = "Relatório PDF";
        String passagemTexto = txtAeronave.getText();
        Document documento = new Document();

        try {
            //criar o documento no diretório do projeto Netbeans AeroFast
            PdfWriter.getInstance(documento, new FileOutputStream("documentoAeroFastAeronave.pdf"));

            //abrir o documento criado.
            documento.open();

            //ajustar o tamanho da pagina
            documento.setPageSize(PageSize.A4);

            //Adicionar um paragrafo
            documento.add(new Paragraph(passagemTexto));

        } catch (DocumentException | FileNotFoundException ex) {
            msg = msg + ex;
            msg = reduzString(msg);

        } finally {
            documento.close();

            if (!"".equals(msg)) {
                JOptionPane.showMessageDialog(this, msg, tituloMsg, JOptionPane.WARNING_MESSAGE);
                msg = "";
            } else {
                msg = "Relatório criado em PDF com sucesso";
                JOptionPane.showMessageDialog(this, msg, tituloMsg, JOptionPane.WARNING_MESSAGE);
                msg = "";
            }
        }
    }//GEN-LAST:event_btnImprimirRelatorioAeronaveActionPerformed

    private void cbxPrefixoAeronaveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPrefixoAeronaveItemStateChanged

    }//GEN-LAST:event_cbxPrefixoAeronaveItemStateChanged

    private void btnListarRelAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarRelAeronaveActionPerformed
        String title = "Relatórios Aeronaves - Aerofast";
        prefixoAeronave = cbxPrefixoAeronave.getSelectedItem().toString();
        AeronaveCtrl cAeronave = new AeronaveCtrl();
        PanelRelAeronave.setSelectedIndex(1);
        List aeronave = cAeronave.listarAeronavePrefixo(prefixoAeronave);
        this.carregarLista(aeronave);

    }//GEN-LAST:event_btnListarRelAeronaveActionPerformed

    private void btnListarRelAeronavesTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarRelAeronavesTodasActionPerformed
        String title = "Relatórios Aeronaves - Aerofast";
        AeronaveCtrl cAeronave = new AeronaveCtrl();
        PanelRelAeronave.setSelectedIndex(1);
        List aeronave = cAeronave.listarAeronavesTodas();
        this.carregarLista(aeronave);
    }//GEN-LAST:event_btnListarRelAeronavesTodasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaineRelAeronaveTitulo;
    private javax.swing.JPanel PainelRelAeronave;
    private javax.swing.JPanel PainelRelImpressoAeronaves;
    private javax.swing.JPanel PaneRelAeronaveBotoes;
    private javax.swing.JTabbedPane PanelRelAeronave;
    private javax.swing.JButton btnImprimirRelatorioAeronave;
    private javax.swing.JButton btnLimparRelAeronave;
    private javax.swing.JButton btnListarRelAeronave;
    private javax.swing.JButton btnListarRelAeronavesTodas;
    private javax.swing.JButton btnSairRelAeronave;
    private javax.swing.JComboBox cbxPrefixoAeronave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumeroPrefixoAeronave;
    private javax.swing.JLabel lblRelFotoAeronave;
    private javax.swing.JLabel lblTelaRelAeronave;
    private javax.swing.JLabel lblTituloTelaRelAeronave;
    private javax.swing.JTextArea txtAeronave;
    // End of variables declaration//GEN-END:variables

    private void populaJComboBoxAeronavePrefixo() {
        AeronaveCtrl cAeronave = new AeronaveCtrl();
        cbxPrefixoAeronave.removeAllItems(); //remove os itens atuais do comboBox.
        ArrayList lista = cAeronave.populaComboPrefixoAeronave(); //retorna os prefixos das aeronaves.
        Iterator i = lista.iterator();
        while (i.hasNext()) {
            cbxPrefixoAeronave.addItem(String.valueOf(i.next()));
        }

    }

    private void carregarLista(List<Aeronave> ListaAeronaves) {

        String newline = System.getProperty("line.separator");
        String resultado = "";

        for (Aeronave a : ListaAeronaves) {
            resultado += ""
                    + "\n\tId Aeronave: " + a.getIdAeronave() + "\n"
                    + "\n\tPrefixo Aeronave: " + a.getPrefixo() + "\n"
                    + "\n\tQuantidade Assentos: \tClasse Economica \tClasse Empresarial \tPrimeira Classe"
                    + "\n\t\t\t " + a.getSeatEconomyClasse() + "\t\t"
                    + a.getSeatBusinesClasse()
                    + "\t\t" + a.getSeatFirstClasse() + "\n"
                    + "\tModelo: " + a.getModelo() + "\n"
                    + "\tFabricante: " + a.getFabricante() + "\n"
                    + "\tOperadora: " + a.getOperadora() + "\n"
                    + "\t------------------------------------------------------------------------------------------------------------------------";
            resultado += newline;

        }

        resultado = "\n\n\t\t\t Lista Aeronaves Sistema AeroFast\n" + resultado;
        txtAeronave.setText(resultado);
        txtAeronave.setEditable(false);

    }
}
