/*
 * Este Software tem Objetivo Educacional
 * Para fins de aprendizagem e avaliacao na
 * Na Disciplina de Programacao Orientada a Objetos - Avancada
 *  do Curso de Analise de Sistemas da Fatec - Ipiranga
 * Ano 2016 - Janeiro a Junho 
 * Aluno Decio Antonio de Carvalho  * 
 */
package view;

import Control.Util;
import Control.ValidaCampos;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import model.Passageiro;

/**
 *
 * @author Dac
 */
public class TelaNovoPassageiro extends javax.swing.JInternalFrame {
public static ArrayList<model.Passageiro> arrayPass;
public static boolean temPassageiro;
/**
 * data nascimento
 * 
 */
private static String dataNascimento, dataHojePassageiro;
private static Date dataNasc, dt;
private static Date hojePassageiro;
private static Date calNascimento;
private static SimpleDateFormat sdfNascimentoPassageiro;
private int dataAtual, dataIntNascimento;

/**
     * Creates new form TelaNovoPassageiro
     */
    public TelaNovoPassageiro() {
        initComponents();
    if(!temPassageiro){
            arrayPass = new ArrayList<>();
            temPassageiro = true;
        }
        btnAlterarPassageiro.setEnabled(false);
        dt = new Date();
        jspNascimentoPassageiro.setValue(dt);    
        hojePassageiro = new Date();
        dataHojePassageiro = Util.DataFormatada(hojePassageiro);
        sdfNascimentoPassageiro = new SimpleDateFormat("dd/MM/yyyy");
    try { 
        hojePassageiro = sdfNascimentoPassageiro.parse(dataHojePassageiro);
    } catch (ParseException ex) {
        Logger.getLogger(TelaNovoPassageiro.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelClienteTitulo = new javax.swing.JPanel();
        lblTituloTelaPassageiro = new javax.swing.JLabel();
        lblTelaPassageiro = new javax.swing.JLabel();
        jTabPassageiro = new javax.swing.JTabbedPane();
        PainelPassageiro = new javax.swing.JPanel();
        lblPassageiro = new javax.swing.JLabel();
        tctPassageiro = new javax.swing.JTextField();
        lblNascimentoPassageiro = new javax.swing.JLabel();
        lblTelefonePassageiro = new javax.swing.JLabel();
        tftTelefonePassageiro = new javax.swing.JFormattedTextField();
        lblEmailPassageiro = new javax.swing.JLabel();
        tftEmail = new javax.swing.JFormattedTextField();
        tftRGPassageiro = new javax.swing.JFormattedTextField();
        lblRGPassageiro = new javax.swing.JLabel();
        Date dtIntegradaNP = new Date();
        SpinnerDateModel smIntegradaNP = new 
        SpinnerDateModel(dtIntegradaNP,null,null,Calendar.MONTH + Calendar.DAY_OF_MONTH 
            + Calendar.YEAR );
        jspNascimentoPassageiro = 
        jspNascimentoPassageiro = new javax.swing.JSpinner(smIntegradaNP);
        JSpinner.DateEditor deIntegradaNP = new 
        JSpinner.DateEditor(jspNascimentoPassageiro,"dd/MM/yyyy");
        jspNascimentoPassageiro.setEditor(deIntegradaNP);
        btnPesquisarRG = new javax.swing.JButton();
        PainelPassageiroContato = new javax.swing.JPanel();
        lblContato = new javax.swing.JLabel();
        tctContato = new javax.swing.JTextField();
        lblTelefoneContato = new javax.swing.JLabel();
        tftTelefoneContato = new javax.swing.JFormattedTextField();
        PainelResponsavelFinanceiro = new javax.swing.JPanel();
        lblResponsavelFinanceiro = new javax.swing.JLabel();
        tctResponsavelFinanceiro = new javax.swing.JTextField();
        lblCpfResponsável = new javax.swing.JLabel();
        tftCPFResponsavel = new javax.swing.JFormattedTextField();
        btnPesquisarCPF = new javax.swing.JButton();
        JPanelClienteBotoes = new javax.swing.JPanel();
        btnSalvarPassageiro = new javax.swing.JButton();
        btnPesquisarPassageiro = new javax.swing.JButton();
        btnSairPassageiro = new javax.swing.JButton();
        btnLimparPassageiro = new javax.swing.JButton();
        btnExcluirPassageiro = new javax.swing.JButton();
        btnAlterarPassageiro = new javax.swing.JButton();
        btnEditarPassageiro = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        JPanelClienteTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTituloTelaPassageiro.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTituloTelaPassageiro.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloTelaPassageiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTelaPassageiro.setText("Passageiro");

        lblTelaPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cliente verde 40x40.jpg"))); // NOI18N

        javax.swing.GroupLayout JPanelClienteTituloLayout = new javax.swing.GroupLayout(JPanelClienteTitulo);
        JPanelClienteTitulo.setLayout(JPanelClienteTituloLayout);
        JPanelClienteTituloLayout.setHorizontalGroup(
            JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteTituloLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(lblTelaPassageiro)
                .addGap(58, 58, 58)
                .addComponent(lblTituloTelaPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelClienteTituloLayout.setVerticalGroup(
            JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelClienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelaPassageiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPanelClienteTituloLayout.createSequentialGroup()
                        .addComponent(lblTituloTelaPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );

        jTabPassageiro.setToolTipText("Pessoal responsável financeiramente pelo passageiro");
        jTabPassageiro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabPassageiro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        PainelPassageiro.setBorder(javax.swing.BorderFactory.createTitledBorder("Passageiro"));
        PainelPassageiro.setToolTipText("Dados do Passageiros");

        lblPassageiro.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassageiro.setForeground(new java.awt.Color(102, 102, 102));
        lblPassageiro.setText("Nome:");

        tctPassageiro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctPassageiro.setForeground(new java.awt.Color(51, 51, 51));
        tctPassageiro.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNascimentoPassageiro.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNascimentoPassageiro.setForeground(new java.awt.Color(102, 102, 102));
        lblNascimentoPassageiro.setText("Nascimento:");

        lblTelefonePassageiro.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelefonePassageiro.setForeground(new java.awt.Color(102, 102, 102));
        lblTelefonePassageiro.setText("Telefone: ");

        try {
            tftTelefonePassageiro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftTelefonePassageiro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        lblEmailPassageiro.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblEmailPassageiro.setForeground(new java.awt.Color(102, 102, 102));
        lblEmailPassageiro.setText("Email:");

        tftEmail.setForeground(new java.awt.Color(51, 51, 51));
        tftEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tftEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        try {
            tftRGPassageiro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftRGPassageiro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftRGPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftRGPassageiroActionPerformed(evt);
            }
        });

        lblRGPassageiro.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblRGPassageiro.setForeground(new java.awt.Color(102, 102, 102));
        lblRGPassageiro.setText("RG:");

        jspNascimentoPassageiro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jspNascimentoPassageiro.setToolTipText("Escolha Dia, Mês e Ano");

        btnPesquisarRG.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPesquisarRG.setText("Pesquisar em Clientes");
        btnPesquisarRG.setToolTipText("Pesquisar CPF");
        btnPesquisarRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarRGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPassageiroLayout = new javax.swing.GroupLayout(PainelPassageiro);
        PainelPassageiro.setLayout(PainelPassageiroLayout);
        PainelPassageiroLayout.setHorizontalGroup(
            PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassageiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPassageiroLayout.createSequentialGroup()
                        .addComponent(lblPassageiro)
                        .addGap(44, 44, 44)
                        .addComponent(tctPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPassageiroLayout.createSequentialGroup()
                        .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNascimentoPassageiro)
                            .addComponent(lblEmailPassageiro)
                            .addComponent(lblTelefonePassageiro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tftTelefonePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelPassageiroLayout.createSequentialGroup()
                                .addComponent(jspNascimentoPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(lblRGPassageiro)
                                .addGap(18, 18, 18)
                                .addComponent(tftRGPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisarRG))
                            .addComponent(tftEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 190, Short.MAX_VALUE))
        );
        PainelPassageiroLayout.setVerticalGroup(
            PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassageiroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassageiro)
                    .addComponent(tctPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNascimentoPassageiro)
                    .addComponent(jspNascimentoPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRGPassageiro)
                    .addComponent(tftRGPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarRG))
                .addGap(28, 28, 28)
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonePassageiro)
                    .addComponent(tftTelefonePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(PainelPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailPassageiro)
                    .addComponent(tftEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabPassageiro.addTab("Passageiro", PainelPassageiro);

        PainelPassageiroContato.setBorder(javax.swing.BorderFactory.createTitledBorder("Passageiro - Contato"));
        PainelPassageiroContato.setToolTipText("Dados Pessoa a ser contactada em caso de emergência");

        lblContato.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblContato.setForeground(new java.awt.Color(102, 102, 102));
        lblContato.setText("Nome Contato :");

        tctContato.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctContato.setForeground(new java.awt.Color(51, 51, 51));
        tctContato.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblTelefoneContato.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTelefoneContato.setForeground(new java.awt.Color(102, 102, 102));
        lblTelefoneContato.setText("Telefone: ");

        try {
            tftTelefoneContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftTelefoneContato.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tftTelefoneContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftTelefoneContatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPassageiroContatoLayout = new javax.swing.GroupLayout(PainelPassageiroContato);
        PainelPassageiroContato.setLayout(PainelPassageiroContatoLayout);
        PainelPassageiroContatoLayout.setHorizontalGroup(
            PainelPassageiroContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassageiroContatoLayout.createSequentialGroup()
                .addGroup(PainelPassageiroContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContato)
                    .addComponent(lblTelefoneContato))
                .addGap(32, 32, 32)
                .addGroup(PainelPassageiroContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tftTelefoneContato, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tctContato, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 130, Short.MAX_VALUE))
        );
        PainelPassageiroContatoLayout.setVerticalGroup(
            PainelPassageiroContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPassageiroContatoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PainelPassageiroContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContato)
                    .addComponent(tctContato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPassageiroContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneContato)
                    .addComponent(tftTelefoneContato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabPassageiro.addTab("Contato", PainelPassageiroContato);

        PainelResponsavelFinanceiro.setBorder(javax.swing.BorderFactory.createTitledBorder("Responsável Financeiro"));

        lblResponsavelFinanceiro.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblResponsavelFinanceiro.setForeground(new java.awt.Color(102, 102, 102));
        lblResponsavelFinanceiro.setText("Nome Responsável :");

        tctResponsavelFinanceiro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tctResponsavelFinanceiro.setForeground(new java.awt.Color(51, 51, 51));
        tctResponsavelFinanceiro.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblCpfResponsável.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblCpfResponsável.setForeground(new java.awt.Color(102, 102, 102));
        lblCpfResponsável.setText("CPF:");

        try {
            tftCPFResponsavel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tftCPFResponsavel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        btnPesquisarCPF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPesquisarCPF.setText("Pesquisar");
        btnPesquisarCPF.setToolTipText("Pesquisar CPF");
        btnPesquisarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelResponsavelFinanceiroLayout = new javax.swing.GroupLayout(PainelResponsavelFinanceiro);
        PainelResponsavelFinanceiro.setLayout(PainelResponsavelFinanceiroLayout);
        PainelResponsavelFinanceiroLayout.setHorizontalGroup(
            PainelResponsavelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelResponsavelFinanceiroLayout.createSequentialGroup()
                .addGroup(PainelResponsavelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCpfResponsável)
                    .addComponent(lblResponsavelFinanceiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelResponsavelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelResponsavelFinanceiroLayout.createSequentialGroup()
                        .addComponent(tftCPFResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnPesquisarCPF))
                    .addComponent(tctResponsavelFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainelResponsavelFinanceiroLayout.setVerticalGroup(
            PainelResponsavelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelResponsavelFinanceiroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PainelResponsavelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResponsavelFinanceiro)
                    .addComponent(tctResponsavelFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelResponsavelFinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfResponsável)
                    .addComponent(tftCPFResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCPF))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabPassageiro.addTab("Responsável Financeiro", PainelResponsavelFinanceiro);

        JPanelClienteBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalvarPassageiro.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvarPassageiro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSalvarPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarGreen_1.png"))); // NOI18N
        btnSalvarPassageiro.setText("Salvar");
        btnSalvarPassageiro.setToolTipText("Salvar Alterações");
        btnSalvarPassageiro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalvarPassageiro.setIconTextGap(2);
        btnSalvarPassageiro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSalvarPassageiro.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSalvarPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPassageiroActionPerformed(evt);
            }
        });

        btnPesquisarPassageiro.setBackground(new java.awt.Color(204, 204, 204));
        btnPesquisarPassageiro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPesquisarPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lupaVermelha 40x40.png"))); // NOI18N
        btnPesquisarPassageiro.setText("Pesquisar");
        btnPesquisarPassageiro.setToolTipText("Entre com o RG do Passageiro");
        btnPesquisarPassageiro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPesquisarPassageiro.setPreferredSize(new java.awt.Dimension(100, 50));
        btnPesquisarPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPassageiroActionPerformed(evt);
            }
        });

        btnSairPassageiro.setBackground(new java.awt.Color(204, 204, 204));
        btnSairPassageiro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSairPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairPassageiro.setText("Voltar");
        btnSairPassageiro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSairPassageiro.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairPassageiroActionPerformed(evt);
            }
        });

        btnLimparPassageiro.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparPassageiro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLimparPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/oopsRed.png"))); // NOI18N
        btnLimparPassageiro.setText("Limpar");
        btnLimparPassageiro.setToolTipText("Limpar preenchimento");
        btnLimparPassageiro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLimparPassageiro.setPreferredSize(new java.awt.Dimension(100, 50));
        btnLimparPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPassageiroActionPerformed(evt);
            }
        });

        btnExcluirPassageiro.setBackground(new java.awt.Color(204, 204, 204));
        btnExcluirPassageiro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExcluirPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/excluir 40x40 vermelho.png"))); // NOI18N
        btnExcluirPassageiro.setText("Excluir");
        btnExcluirPassageiro.setToolTipText("Excluir Passageiro");
        btnExcluirPassageiro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnExcluirPassageiro.setPreferredSize(new java.awt.Dimension(100, 50));
        btnExcluirPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPassageiroActionPerformed(evt);
            }
        });

        btnAlterarPassageiro.setBackground(new java.awt.Color(204, 204, 204));
        btnAlterarPassageiro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAlterarPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ticarRed.png"))); // NOI18N
        btnAlterarPassageiro.setText("Alterar");
        btnAlterarPassageiro.setToolTipText("Alterar Dados");
        btnAlterarPassageiro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAlterarPassageiro.setIconTextGap(0);
        btnAlterarPassageiro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAlterarPassageiro.setPreferredSize(new java.awt.Dimension(100, 50));
        btnAlterarPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPassageiroActionPerformed(evt);
            }
        });

        btnEditarPassageiro.setBackground(new java.awt.Color(204, 204, 204));
        btnEditarPassageiro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEditarPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inserir.png"))); // NOI18N
        btnEditarPassageiro.setText("Editar");
        btnEditarPassageiro.setToolTipText("Editar Alterações");
        btnEditarPassageiro.setDefaultCapable(false);
        btnEditarPassageiro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditarPassageiro.setIconTextGap(1);
        btnEditarPassageiro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnEditarPassageiro.setPreferredSize(new java.awt.Dimension(100, 50));
        btnEditarPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPassageiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelClienteBotoesLayout = new javax.swing.GroupLayout(JPanelClienteBotoes);
        JPanelClienteBotoes.setLayout(JPanelClienteBotoesLayout);
        JPanelClienteBotoesLayout.setHorizontalGroup(
            JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvarPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterarPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JPanelClienteBotoesLayout.setVerticalGroup(
            JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelClienteBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSairPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanelClienteBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelClienteTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabPassageiro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(JPanelClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelClienteBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tftRGPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftRGPassageiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftRGPassageiroActionPerformed

    private void tftTelefoneContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftTelefoneContatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftTelefoneContatoActionPerformed

    private void btnSalvarPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPassageiroActionPerformed
        Passageiro objPass;
        objPass = new Passageiro();
        
        String msg = "";
        
        int id1 = arrayPass.size();
        id1++;
        String id = id1+"";
        
        
        objPass.setIdPassageiro(id);
        objPass.setNomePassageiro(tctPassageiro.getText());
        
        
        /**
         * DataNascimento
         */
        dataNascimento = Util.DataFormatadaS(jspNascimentoPassageiro.getValue().toString());
        dataIntNascimento = Util.DtAmericana(jspNascimentoPassageiro.getValue().toString());

        objPass.setNascimentoPassageiro(dataNascimento);
        objPass.setRgPassageiro(tftRGPassageiro.getText());
        objPass.setTelefonePassageiro(tftTelefonePassageiro.getText());
        objPass.setEmailPassageiro(tftEmail.getText());
        objPass.setContatoNome(tctContato.getText());
        objPass.setContatoTelefone(tftTelefoneContato.getText());
        objPass.setResponsavelFinanceiro(tctResponsavelFinanceiro.getText());
        objPass.setResponsavelCPF(tftCPFResponsavel.getText());
               
        boolean validaNomePassageiro = ValidaCampos.validaNome(tctPassageiro.getText());
        boolean validaDtNascimento = ValidaCampos.validaDataNascimento(dataIntNascimento);
        boolean validaRG = ValidaCampos.validaRG(tftRGPassageiro.getText());
        boolean validaTelefonePassageiro = ValidaCampos.validaTelefone(tftTelefonePassageiro.getText());
        boolean validaEmail = ValidaCampos.validaEmail(tftEmail.getText());
        boolean validaContato = ValidaCampos.validaNome(tctContato.getText());
        boolean validaTelefoneContato = ValidaCampos.validaTelefone(tftTelefoneContato.getText());
        boolean validaResponsavel = ValidaCampos.validaNome(tctResponsavelFinanceiro.getText());
        boolean validaCPF = ValidaCampos.validaCPF(tftCPFResponsavel.getText());

        if (validaNomePassageiro) {
        } else {
            msg = msg + "Campo Passageiro Vazio" + "\n";
        }
        
        if (validaDtNascimento) {
        } else {
            msg = msg + "Campo Nascimento Inválido" + "\n";
        }
        
        if (validaRG) {
        } else {
            msg = msg + "Campo RG invalido: "+ tftRGPassageiro.getText() + "\n";
            this.tftRGPassageiro.setText(null);
        }
        if (validaTelefonePassageiro){

        }else{
            msg = msg + "Campo Telefone Passageiro inválido: "+ tftTelefonePassageiro.getText() + "\n";
            this.tftTelefonePassageiro.setText(null);
        }
        if (validaEmail) {
        } else {
            msg = msg +"Campo E-mail invalido: "+ tftEmail.getText() + "\n";
            this.tftEmail.setText(null);
        }

        if (validaContato) {
        } else {
            msg = msg + "Campo Contato vazio: "+ tctContato.getText() + "\n";
        }

        if (validaTelefoneContato){

        }else{
            msg = msg + "Campo Telefone Contato inválido: "+ tftTelefoneContato.getText() + "\n";
            this.tftTelefoneContato.setText(null);
        }

        if (validaResponsavel) {
        } else {
            msg = msg + "Campo Responsável Financeiro vazio: "+ tctResponsavelFinanceiro.getText() + "\n";
        }

        if (validaCPF) {
        } else {
            msg = msg + "Campo CPF invalido: "+ tftCPFResponsavel.getText() + "\n";
            this.tftCPFResponsavel.setText(null);
        }

        //msg = msg +"oi oi oi \n";

        if ("".equals(msg)){
            msg = "Dados Enviados ao banco de dados do sistema!";
            if (btnSalvarPassageiro.isEnabled()){
                 boolean resultadoPassageiro = arrayPass.add(objPass);
                // System.out.println("Resposta se adicionou novo Passageiro? "+resultadoPassageiro+" id:"+id);
            }
            else{
            
                boolean flag = false;

                for(int i = 0; i < arrayPass.size(); i++){

                    if(tftRGPassageiro.getText().trim().equals(arrayPass.get(i).getRgPassageiro())){
                        String removidoPassageiro = arrayPass.get(i).getRgPassageiro();
                        Passageiro removido = arrayPass.remove(i);

                        //JOptionPane.showMessageDialog(this,"Passageiro de RG: "+removidoPassageiro+" Removido!");
                        boolean resultadoAlterouPassageiro = arrayPass.add(objPass);
                        btnLimparPassageiro.doClick(); //Limpar tela

                        flag = true;

                    }//fim do if
                }// fim do for
             
            }
            JOptionPane.showMessageDialog(this, msg,"Dados Enviados", JOptionPane.INFORMATION_MESSAGE);
            PainelPassageiro.requestFocus(true); 
            btnLimparPassageiro.doClick();
            btnSairPassageiro.doClick();
            
        }
        else{
            JOptionPane.showMessageDialog(this, msg,"Campo Inválido ou vazio", JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_btnSalvarPassageiroActionPerformed

    private void btnPesquisarPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPassageiroActionPerformed
        btnSalvarPassageiro.setEnabled(false);
        btnAlterarPassageiro.setEnabled(true);
        boolean flag = false;

        for(int i = 0; i < arrayPass.size(); i++){
            if(tftRGPassageiro.getText().equals(arrayPass.get(i).getRgPassageiro())){

                tctPassageiro.setText(arrayPass.get(i).getNomePassageiro());
                
                /**
                 * Tratamento do campo tipo jSpinner
                 */
                
                String sdataNascimento = arrayPass.get(i).getNascimentoPassageiro();
                
                try {
                    calNascimento = Util.retornaData(sdataNascimento);
                } catch (Exception ex) {
                    Logger.getLogger(TelaNovoPassageiro.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                jspNascimentoPassageiro.setValue(calNascimento);
               
                //jspNascimentoPassageiro.getEditor();
                
                tftRGPassageiro.setText(arrayPass.get(i).getRgPassageiro());
                tftTelefonePassageiro.setText(arrayPass.get(i).getTelefonePassageiro());
                tftEmail.setText(arrayPass.get(i).getEmailPassageiro());
                tctContato.setText(arrayPass.get(i).getContatoNome());
                tftTelefoneContato.setText(arrayPass.get(i).getContatoTelefone());
                tctResponsavelFinanceiro.setText(arrayPass.get(i).getResponsavelFinanceiro());
                tftCPFResponsavel.setText(arrayPass.get(i).getResponsavelCPF());
                flag = true;
            }//fim do if
        }// fim do for
        if(arrayPass.isEmpty()){
        JOptionPane.showMessageDialog(this,"Nenhum Passageiro Cadastrado!!");
        btnSalvarPassageiro.setEnabled(true);
        btnAlterarPassageiro.setEnabled(false);
        }
        else if (flag == false){
        JOptionPane.showMessageDialog(this, "Passageiro não encontrado!!!, Entre com outro RG");
        btnSalvarPassageiro.setEnabled(true);
        btnAlterarPassageiro.setEnabled(false);
        }
    }//GEN-LAST:event_btnPesquisarPassageiroActionPerformed

    private void btnSairPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairPassageiroActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairPassageiroActionPerformed

    private void btnLimparPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPassageiroActionPerformed
        tctPassageiro.setText(null);
        tftRGPassageiro.setText(null);
        tftTelefonePassageiro.setText(null);
        tftEmail.setText(null);
        tctContato.setText(null);
        tftTelefoneContato.setText(null);
        tctResponsavelFinanceiro.setText(null);
        tftCPFResponsavel.setText(null);
    }//GEN-LAST:event_btnLimparPassageiroActionPerformed

    private void btnExcluirPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPassageiroActionPerformed

        boolean flag = false;

        for(int i = 0; i < arrayPass.size(); i++){

            if(tftRGPassageiro.getText().trim().equals(arrayPass.get(i).getRgPassageiro())){
                String removidoPassageiro = arrayPass.get(i).getRgPassageiro();
                Passageiro removido = arrayPass.remove(i);

                JOptionPane.showMessageDialog(this,"Passageiro de RG: "+removidoPassageiro+" Removido!");
                btnLimparPassageiro.doClick(); //Limpar tela

                flag = true;

            }//fim do if
        }// fim do for

        if(arrayPass.isEmpty())
        JOptionPane.showMessageDialog(this,"Nenhum Passageiro Cadastrado!!");
        else if (flag == false)
        JOptionPane.showMessageDialog(this, "Passageiro não encontrado!!!");

    }//GEN-LAST:event_btnExcluirPassageiroActionPerformed

    private void btnAlterarPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPassageiroActionPerformed
        // TODO add your handling code here:
        //btnSalvarPassageiro.doClick();
        btnSalvarPassageiroActionPerformed(evt);
    }//GEN-LAST:event_btnAlterarPassageiroActionPerformed

    private void btnPesquisarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCPFActionPerformed
      
        boolean flag = false;
        
        for(int i = 0; i < TelaCliente.arrayCli.size(); i++){
                      
            if(tftCPFResponsavel.getText().equals(TelaCliente.arrayCli.get(i).getCpf())){
                         
            tctResponsavelFinanceiro.setText(TelaCliente.arrayCli.get(i).getNome() );
            
              flag = true;
          }  
        }
        
        if(TelaCliente.arrayCli.isEmpty())
            JOptionPane.showMessageDialog(this,"Nenhum Responsável Financeiro Cadastrado!!");
       else if (flag == false)
            JOptionPane.showMessageDialog(this, "Responsável não encontrado!!!, Entre com outro CPF"); 
        
        
    }//GEN-LAST:event_btnPesquisarCPFActionPerformed

    private void btnPesquisarRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarRGActionPerformed
        // TODO add your handling code here:
        
        boolean flag = false;
        
        for(int i = 0; i < TelaCliente.arrayCli.size(); i++){
                      
            if(tftRGPassageiro.getText().equals(TelaCliente.arrayCli.get(i).getRg())){
                         
            tctPassageiro.setText(TelaCliente.arrayCli.get(i).getNome() );
            
            /**
            * Tratamento do campo tipo jSpinner
            */
            String sdataNascimento = TelaCliente.arrayCli.get(i).getNascimento();
            
            SimpleDateFormat sdfNascimento = new SimpleDateFormat("dd/MM/yyyyy");
            try {
                    calNascimento = Util.retornaData(sdataNascimento);
                } catch (Exception ex) {
                    Logger.getLogger(TelaNovoPassageiro.class.getName()).log(Level.SEVERE, null, ex);
                }
            jspNascimentoPassageiro.setValue(calNascimento);
            /*Final do tratamento do campo tipo jSpinner*/
            
            
            tftRGPassageiro.setText(TelaCliente.arrayCli.get(i).getRg() );
            System.out.println(TelaCliente.arrayCli.get(i).getTelefone());
            tftTelefonePassageiro.setText(TelaCliente.arrayCli.get(i).getTelefone() );
            tftEmail.setText(TelaCliente.arrayCli.get(i).getEmail() );
              flag = true;
          }  
        }
        
        if(TelaCliente.arrayCli.isEmpty())
            JOptionPane.showMessageDialog(this,"Nenhum Cliente Cadastrado!!");
       else if (flag == false)
            JOptionPane.showMessageDialog(this, "Cliente não encontrado!!!, Entre com outro RG"); 
        
    }//GEN-LAST:event_btnPesquisarRGActionPerformed

    private void btnEditarPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPassageiroActionPerformed
        // TODO add your handling code here:
        if (!tctPassageiro.isEditable()){
            //msg = "Pode realizar alterações agora";
            //habilitarDadosPassageiro();
            //  JOptionPane.showMessageDialog(this, msg,"", JOptionPane.INFORMATION_MESSAGE );
        }
        btnAlterarPassageiro.setEnabled(true);
        btnEditarPassageiro.setEnabled(false);
    }//GEN-LAST:event_btnEditarPassageiroActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
      this.moveToFront();
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoPassageiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelClienteBotoes;
    private javax.swing.JPanel JPanelClienteTitulo;
    private javax.swing.JPanel PainelPassageiro;
    private javax.swing.JPanel PainelPassageiroContato;
    private javax.swing.JPanel PainelResponsavelFinanceiro;
    private static javax.swing.JButton btnAlterarPassageiro;
    private javax.swing.JButton btnEditarPassageiro;
    private javax.swing.JButton btnExcluirPassageiro;
    private javax.swing.JButton btnLimparPassageiro;
    private static javax.swing.JButton btnPesquisarCPF;
    private javax.swing.JButton btnPesquisarPassageiro;
    private static javax.swing.JButton btnPesquisarRG;
    private javax.swing.JButton btnSairPassageiro;
    private static javax.swing.JButton btnSalvarPassageiro;
    private javax.swing.JTabbedPane jTabPassageiro;
    private javax.swing.JSpinner jspNascimentoPassageiro;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblCpfResponsável;
    private javax.swing.JLabel lblEmailPassageiro;
    private javax.swing.JLabel lblNascimentoPassageiro;
    private javax.swing.JLabel lblPassageiro;
    private javax.swing.JLabel lblRGPassageiro;
    private javax.swing.JLabel lblResponsavelFinanceiro;
    private javax.swing.JLabel lblTelaPassageiro;
    private javax.swing.JLabel lblTelefoneContato;
    private javax.swing.JLabel lblTelefonePassageiro;
    private javax.swing.JLabel lblTituloTelaPassageiro;
    private static javax.swing.JTextField tctContato;
    private static javax.swing.JTextField tctPassageiro;
    private static javax.swing.JTextField tctResponsavelFinanceiro;
    private javax.swing.JFormattedTextField tftCPFResponsavel;
    private javax.swing.JFormattedTextField tftEmail;
    private javax.swing.JFormattedTextField tftRGPassageiro;
    private javax.swing.JFormattedTextField tftTelefoneContato;
    private javax.swing.JFormattedTextField tftTelefonePassageiro;
    // End of variables declaration//GEN-END:variables
}
