/*
 * Este Software tem Objetivo Educacional
 * Para fins de aprendizagem e avaliacao na
  * Na Disciplina de Programa��o Orientada a Objetos - Avan�ada
  *  do Curso de Analise de Sistemas da Fatec - Ipiranga
  * Ano 2016 - Janeiro a Junho 
  * Aluno Decio Antonio de Carvalho  * 
 */
package view;

import Control.PassageiroCtrl;
import static Control.Util.reduzString;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Passageiro;
/**
 *
 * @author deciocarvalho
 */
public class TelaRelatorioPassageiro extends javax.swing.JInternalFrame {

        public static String rgPassageiro, nomePassageiro;
    
    /**
     * Creates new form TelaRelatorioPassageiro
     */
    public TelaRelatorioPassageiro() {
        initComponents();
        populaJComboBoxPassageirosNome();
        btnListarPassageiro.setEnabled(false);
        
        //Limpar ComBox
        cbxNomePassageiro.setSelectedItem(-1);
        
    }
    
    private void populaJComboBoxPassageirosNome() {
        PassageiroCtrl cPassageiro = new PassageiroCtrl();
        cbxNomePassageiro.removeAllItems(); //remove os itens atuais do comboBox.
        ArrayList lista = cPassageiro.populaComboPassageiroNome(); //retorna os nomes dos clientes do banco.
        Iterator i = lista.iterator();
        while (i.hasNext()) {
            cbxNomePassageiro.addItem(String.valueOf(i.next()));
            cbxNomePassageiro.setSelectedItem(-1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelRelTituloPassageiro = new javax.swing.JPanel();
        lblTituloRelatorioPassageiro = new javax.swing.JLabel();
        lblTelaRelatorioPassageiro = new javax.swing.JLabel();
        PanelRelPassageiroBotoes = new javax.swing.JPanel();
        btnLimparRelPassageiro = new javax.swing.JButton();
        btnSairRelPassageiro = new javax.swing.JButton();
        btnImprimirRelatorioPassageiro = new javax.swing.JButton();
        lblRelatorioClientesFundo = new javax.swing.JLabel();
        PanelTabRelPassageirosImpresso = new javax.swing.JTabbedPane();
        PainelRelOpcoesPassageiro = new javax.swing.JPanel();
        lblNomePassageiro = new javax.swing.JLabel();
        cbxNomePassageiro = new javax.swing.JComboBox();
        btnListarPassageiro = new javax.swing.JButton();
        btnListarPassageiroTodos = new javax.swing.JButton();
        PainelRelImpressoPassageiro = new javax.swing.JPanel();
        jScrollPane1RelPassageirio = new javax.swing.JScrollPane();
        txtRelPassageiro = new javax.swing.JTextArea();

        PainelRelTituloPassageiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblTituloRelatorioPassageiro.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTituloRelatorioPassageiro.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloRelatorioPassageiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRelatorioPassageiro.setText("Aerofast - Passageiros");

        lblTelaRelatorioPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cliente 80x80.jpg"))); // NOI18N

        javax.swing.GroupLayout PainelRelTituloPassageiroLayout = new javax.swing.GroupLayout(PainelRelTituloPassageiro);
        PainelRelTituloPassageiro.setLayout(PainelRelTituloPassageiroLayout);
        PainelRelTituloPassageiroLayout.setHorizontalGroup(
            PainelRelTituloPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelTituloPassageiroLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(lblTelaRelatorioPassageiro)
                .addGap(31, 31, 31)
                .addComponent(lblTituloRelatorioPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        PainelRelTituloPassageiroLayout.setVerticalGroup(
            PainelRelTituloPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRelTituloPassageiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelRelTituloPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTelaRelatorioPassageiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloRelatorioPassageiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        PanelRelPassageiroBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnLimparRelPassageiro.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparRelPassageiro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLimparRelPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/oopsRed.png"))); // NOI18N
        btnLimparRelPassageiro.setText("Limpar");
        btnLimparRelPassageiro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimparRelPassageiro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLimparRelPassageiro.setPreferredSize(new java.awt.Dimension(100, 50));
        btnLimparRelPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparRelPassageiroActionPerformed(evt);
            }
        });

        btnSairRelPassageiro.setBackground(new java.awt.Color(204, 204, 204));
        btnSairRelPassageiro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSairRelPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairRelPassageiro.setText("Voltar");
        btnSairRelPassageiro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSairRelPassageiro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSairRelPassageiro.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairRelPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairRelPassageiroActionPerformed(evt);
            }
        });

        btnImprimirRelatorioPassageiro.setBackground(new java.awt.Color(204, 204, 204));
        btnImprimirRelatorioPassageiro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnImprimirRelatorioPassageiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/infraero/pdf2.png"))); // NOI18N
        btnImprimirRelatorioPassageiro.setText("Imprimir em PDF");
        btnImprimirRelatorioPassageiro.setToolTipText("Salvar Alterações");
        btnImprimirRelatorioPassageiro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImprimirRelatorioPassageiro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnImprimirRelatorioPassageiro.setIconTextGap(2);
        btnImprimirRelatorioPassageiro.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnImprimirRelatorioPassageiro.setPreferredSize(new java.awt.Dimension(100, 50));
        btnImprimirRelatorioPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirRelatorioPassageiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRelPassageiroBotoesLayout = new javax.swing.GroupLayout(PanelRelPassageiroBotoes);
        PanelRelPassageiroBotoes.setLayout(PanelRelPassageiroBotoesLayout);
        PanelRelPassageiroBotoesLayout.setHorizontalGroup(
            PanelRelPassageiroBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRelPassageiroBotoesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnLimparRelPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(btnImprimirRelatorioPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnSairRelPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelRelPassageiroBotoesLayout.setVerticalGroup(
            PanelRelPassageiroBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRelPassageiroBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRelPassageiroBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSairRelPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimirRelatorioPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparRelPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblRelatorioClientesFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/relClientes.jpg"))); // NOI18N

        PainelRelOpcoesPassageiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblNomePassageiro.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNomePassageiro.setForeground(new java.awt.Color(102, 102, 102));
        lblNomePassageiro.setText("Nome Passageiro: ");

        cbxNomePassageiro.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        cbxNomePassageiro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNomePassageiroItemStateChanged(evt);
            }
        });
        cbxNomePassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNomePassageiroActionPerformed(evt);
            }
        });

        btnListarPassageiro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnListarPassageiro.setMnemonic('E');
        btnListarPassageiro.setText("Mostrar Passageiro");
        btnListarPassageiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPassageiroActionPerformed(evt);
            }
        });

        btnListarPassageiroTodos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnListarPassageiroTodos.setText("Listar todos Passageiros");
        btnListarPassageiroTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPassageiroTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelRelOpcoesPassageiroLayout = new javax.swing.GroupLayout(PainelRelOpcoesPassageiro);
        PainelRelOpcoesPassageiro.setLayout(PainelRelOpcoesPassageiroLayout);
        PainelRelOpcoesPassageiroLayout.setHorizontalGroup(
            PainelRelOpcoesPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelOpcoesPassageiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelRelOpcoesPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelRelOpcoesPassageiroLayout.createSequentialGroup()
                        .addComponent(lblNomePassageiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxNomePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnListarPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnListarPassageiroTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelRelOpcoesPassageiroLayout.setVerticalGroup(
            PainelRelOpcoesPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelOpcoesPassageiroLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PainelRelOpcoesPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNomePassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomePassageiro)
                    .addComponent(btnListarPassageiro))
                .addGap(26, 26, 26)
                .addComponent(btnListarPassageiroTodos)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        PanelTabRelPassageirosImpresso.addTab("Relatórios Passageiros", PainelRelOpcoesPassageiro);

        txtRelPassageiro.setEditable(false);
        txtRelPassageiro.setBackground(new java.awt.Color(20, 230, 89));
        txtRelPassageiro.setColumns(20);
        txtRelPassageiro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtRelPassageiro.setRows(7);
        txtRelPassageiro.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));
        jScrollPane1RelPassageirio.setViewportView(txtRelPassageiro);

        javax.swing.GroupLayout PainelRelImpressoPassageiroLayout = new javax.swing.GroupLayout(PainelRelImpressoPassageiro);
        PainelRelImpressoPassageiro.setLayout(PainelRelImpressoPassageiroLayout);
        PainelRelImpressoPassageiroLayout.setHorizontalGroup(
            PainelRelImpressoPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRelImpressoPassageiroLayout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1RelPassageirio, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PainelRelImpressoPassageiroLayout.setVerticalGroup(
            PainelRelImpressoPassageiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRelImpressoPassageiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1RelPassageirio, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        );

        PanelTabRelPassageirosImpresso.addTab("Relatório Impresso", PainelRelImpressoPassageiro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PainelRelTituloPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRelatorioClientesFundo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelTabRelPassageirosImpresso, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelRelPassageiroBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(PainelRelTituloPassageiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRelatorioClientesFundo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PanelTabRelPassageirosImpresso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelRelPassageiroBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparRelPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparRelPassageiroActionPerformed
        //Limpar ComboBox
        cbxNomePassageiro.setSelectedIndex(-1);
        txtRelPassageiro.setText("");

    }//GEN-LAST:event_btnLimparRelPassageiroActionPerformed

    private void btnSairRelPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairRelPassageiroActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairRelPassageiroActionPerformed

    private void btnImprimirRelatorioPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirRelatorioPassageiroActionPerformed
        //criamos um documento vazio
        String msg ="";
        String tituloMsg = "Relatório PDF";
        String passagemTexto = txtRelPassageiro.getText();
        Document documento = new Document();

        try {
            try {
                //criar o documento no diretório do projeto Netbeans AeroFast
                PdfWriter.getInstance(documento, new FileOutputStream("documentoAeroFastPassageiros.pdf"));
            } catch (FileNotFoundException ex) {
                msg = msg + ex;
                msg = reduzString(msg);
                Logger.getLogger(TelaRelatorioPassageiro.class.getName()).log(Level.SEVERE, null, ex);
            }

            //abrir o documento criado.
            documento.open();

            //ajustar o tamanho da pagina
            documento.setPageSize(PageSize.A4);

            //Adicionar um paragrafo
            documento.add(new Paragraph(passagemTexto));

        } catch (DocumentException ex) {
            msg = msg + ex;
            msg = reduzString(msg);
            Logger.getLogger(FrameListaPassagem.class.getName()).log(Level.SEVERE, null, ex);

        }finally{
            documento.close();

            if (!"".equals(msg)){
                JOptionPane.showMessageDialog(this, msg, tituloMsg, JOptionPane.WARNING_MESSAGE);
                msg="";
            }else
            {
                msg = "Relatório criado em PDF com sucesso";
                JOptionPane.showMessageDialog(this, msg, tituloMsg, JOptionPane.WARNING_MESSAGE);
                msg="";
            }
        }
    }//GEN-LAST:event_btnImprimirRelatorioPassageiroActionPerformed

    private void cbxNomePassageiroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNomePassageiroItemStateChanged

    }//GEN-LAST:event_cbxNomePassageiroItemStateChanged

    private void cbxNomePassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNomePassageiroActionPerformed
        if((cbxNomePassageiro.getSelectedIndex())!=-1){
            btnListarPassageiro.setEnabled(true);
        }else{
            btnListarPassageiro.setEnabled(false);
        }
    }//GEN-LAST:event_cbxNomePassageiroActionPerformed

    private void btnListarPassageiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPassageiroActionPerformed
        String title="Relatórios Clientes";
        nomePassageiro = cbxNomePassageiro.getSelectedItem().toString();
        PassageiroCtrl cPassageiro = new PassageiroCtrl();
        List passageiro = cPassageiro.listaPassageiroNome(nomePassageiro);
       PanelTabRelPassageirosImpresso.setSelectedIndex(1); //troca para o painel do relatório
        this.carregarListaPassageiros(passageiro);

    }//GEN-LAST:event_btnListarPassageiroActionPerformed

    private void btnListarPassageiroTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPassageiroTodosActionPerformed
        String title="Relatórios Clientes";
        PassageiroCtrl cPassageiro = new PassageiroCtrl();
        PanelTabRelPassageirosImpresso.setSelectedIndex(1); //troca para o painel do relatório
        List passageiros = cPassageiro.listarTodosPassageiros();
        this.carregarListaPassageiros(passageiros);

    }//GEN-LAST:event_btnListarPassageiroTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelRelImpressoPassageiro;
    private javax.swing.JPanel PainelRelOpcoesPassageiro;
    private javax.swing.JPanel PainelRelTituloPassageiro;
    private javax.swing.JPanel PanelRelPassageiroBotoes;
    private javax.swing.JTabbedPane PanelTabRelPassageirosImpresso;
    private javax.swing.JButton btnImprimirRelatorioPassageiro;
    private javax.swing.JButton btnLimparRelPassageiro;
    private javax.swing.JButton btnListarPassageiro;
    private javax.swing.JButton btnListarPassageiroTodos;
    private javax.swing.JButton btnSairRelPassageiro;
    private javax.swing.JComboBox cbxNomePassageiro;
    private javax.swing.JScrollPane jScrollPane1RelPassageirio;
    private javax.swing.JLabel lblNomePassageiro;
    private javax.swing.JLabel lblRelatorioClientesFundo;
    private javax.swing.JLabel lblTelaRelatorioPassageiro;
    private javax.swing.JLabel lblTituloRelatorioPassageiro;
    private javax.swing.JTextArea txtRelPassageiro;
    // End of variables declaration//GEN-END:variables

    

    private void carregarListaPassageiros(List<Passageiro> listaPassageiros ) {
      String newline = System.getProperty("line.separator"); //verificar propriedades de System.getProperty
      String resultado = "";
      
      for (Passageiro p : listaPassageiros){
          
          resultado += ""
                  +"\n\tCódigo Passageiro: "+p.getIdPassageiro()+"\n"
                  +"\n\tNome: "+p.getNomePassageiro()+"\n"
                  +"\n\tData Nascimento: "+p.getNascimentoPassageiro()+"\n"
                  +"\n\tRG: "+p.getRgPassageiro()+"\n"
                  +"\n\tTelefone :"+p.getTelefonePassageiro()+"\n"
                  +"\n\tEmail :"+p.getEmailPassageiro()+"\n"
                  +"\n\tResponsável Financeiro: "+p.getResponsavelFinanceiro()+"\n"
                  +"\n\tCPF do Responsável Financeiro :"+p.getResponsavelCPF()+"\n"
                  +"\n\tPessoa para contato: "+p.getContatoNome()+"\n"
                  +"\n\tTelefone do contato: "+p.getTelefonePassageiro()+"\n"
                  +"\n\t- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -";
                  
                  resultado += newline;
          
      }
      resultado="\n\n\t\t\t CADASTRO PASSAGEIROS\n"+resultado;
      txtRelPassageiro.setText(resultado);
      txtRelPassageiro.setEditable(false);
    
    }
}
