/*
 * Este Software tem Objetivo Educacional
 * Para fins de aprendizagem e avaliacao na
  * Na Disciplina de Programa��o Orientada a Objetos - Avan�ada
  *  do Curso de Analise de Sistemas da Fatec - Ipiranga
  * Ano 2016 - Janeiro a Junho 
  * Aluno Decio Antonio de Carvalho  * 
 */
package view;

import Control.VooCtrl;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author deciocarvalho
 */
public class TelaRelatorioVoo extends javax.swing.JInternalFrame {
public static String numeroVoo;
    /**
     * Creates new form TelaRelatorioVoo
     */
    public TelaRelatorioVoo() {
        initComponents();
        populaJComboBoxVooNumero();
        cbxNumeroVoo.setSelectedIndex(-1);
    }
    
    private void populaJComboBoxVooNumero(){
     VooCtrl cVoo = new VooCtrl();
     cbxNumeroVoo.removeAllItems(); //remove os itens atuais do comboBox.
     ArrayList lista = cVoo.populaComboVooNumero(); //retorna os nomes dos clientes do banco.
     Iterator i = lista.iterator();
     while (i.hasNext()){
     cbxNumeroVoo.addItem(String.valueOf(i.next()));
     }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelVooRelTitulo = new javax.swing.JPanel();
        lblTituloRelatorioVoo = new javax.swing.JLabel();
        lblTelaRelatorioVoo = new javax.swing.JLabel();
        PainelRelOpcoesVoo = new javax.swing.JPanel();
        lblNomeVoo = new javax.swing.JLabel();
        cbxNumeroVoo = new javax.swing.JComboBox();
        btnListarVoo = new javax.swing.JButton();
        btnListarVoosTodos = new javax.swing.JButton();
        lblRelatorioVooFundo = new javax.swing.JLabel();
        PanelRelVoosBotoes = new javax.swing.JPanel();
        btnSairVooRelatorio = new javax.swing.JButton();
        btnLimparVooRelatorio = new javax.swing.JButton();

        PainelVooRelTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTituloRelatorioVoo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTituloRelatorioVoo.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloRelatorioVoo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRelatorioVoo.setText("Aerofast - Relatórios de Voos");

        lblTelaRelatorioVoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voo 40x40.png"))); // NOI18N

        javax.swing.GroupLayout PainelVooRelTituloLayout = new javax.swing.GroupLayout(PainelVooRelTitulo);
        PainelVooRelTitulo.setLayout(PainelVooRelTituloLayout);
        PainelVooRelTituloLayout.setHorizontalGroup(
            PainelVooRelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVooRelTituloLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(lblTelaRelatorioVoo)
                .addGap(57, 57, 57)
                .addComponent(lblTituloRelatorioVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelVooRelTituloLayout.setVerticalGroup(
            PainelVooRelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelVooRelTituloLayout.createSequentialGroup()
                .addGroup(PainelVooRelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelVooRelTituloLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTelaRelatorioVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelVooRelTituloLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblTituloRelatorioVoo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        PainelRelOpcoesVoo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        PainelRelOpcoesVoo.setLayout(null);

        lblNomeVoo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblNomeVoo.setForeground(new java.awt.Color(102, 102, 102));
        lblNomeVoo.setText("Número Voo: ");
        PainelRelOpcoesVoo.add(lblNomeVoo);
        lblNomeVoo.setBounds(10, 30, 84, 17);

        cbxNumeroVoo.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        cbxNumeroVoo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNumeroVooItemStateChanged(evt);
            }
        });
        PainelRelOpcoesVoo.add(cbxNumeroVoo);
        cbxNumeroVoo.setBounds(100, 30, 275, 21);

        btnListarVoo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnListarVoo.setText("Mostrar Voo");
        btnListarVoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVooActionPerformed(evt);
            }
        });
        PainelRelOpcoesVoo.add(btnListarVoo);
        btnListarVoo.setBounds(10, 90, 142, 23);

        btnListarVoosTodos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnListarVoosTodos.setText("Listar todos Voos");
        btnListarVoosTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVoosTodosActionPerformed(evt);
            }
        });
        PainelRelOpcoesVoo.add(btnListarVoosTodos);
        btnListarVoosTodos.setBounds(210, 90, 160, 23);

        lblRelatorioVooFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Airbus A330-200.gif"))); // NOI18N
        PainelRelOpcoesVoo.add(lblRelatorioVooFundo);
        lblRelatorioVooFundo.setBounds(380, 0, 495, 350);

        PanelRelVoosBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSairVooRelatorio.setBackground(new java.awt.Color(204, 204, 204));
        btnSairVooRelatorio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSairVooRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/saidaDireitaRed.png"))); // NOI18N
        btnSairVooRelatorio.setText("Voltar");
        btnSairVooRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSairVooRelatorio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSairVooRelatorio.setPreferredSize(new java.awt.Dimension(100, 50));
        btnSairVooRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairVooRelatorioActionPerformed(evt);
            }
        });

        btnLimparVooRelatorio.setBackground(new java.awt.Color(204, 204, 204));
        btnLimparVooRelatorio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLimparVooRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/oopsRed.png"))); // NOI18N
        btnLimparVooRelatorio.setText("Limpar");
        btnLimparVooRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLimparVooRelatorio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLimparVooRelatorio.setPreferredSize(new java.awt.Dimension(100, 50));
        btnLimparVooRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparVooRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRelVoosBotoesLayout = new javax.swing.GroupLayout(PanelRelVoosBotoes);
        PanelRelVoosBotoes.setLayout(PanelRelVoosBotoesLayout);
        PanelRelVoosBotoesLayout.setHorizontalGroup(
            PanelRelVoosBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRelVoosBotoesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnLimparVooRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398)
                .addComponent(btnSairVooRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        PanelRelVoosBotoesLayout.setVerticalGroup(
            PanelRelVoosBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRelVoosBotoesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelRelVoosBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSairVooRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparVooRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelRelVoosBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelVooRelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelRelOpcoesVoo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelVooRelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelRelOpcoesVoo, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelRelVoosBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxNumeroVooItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNumeroVooItemStateChanged

    }//GEN-LAST:event_cbxNumeroVooItemStateChanged

    private void btnListarVooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVooActionPerformed
        numeroVoo = cbxNumeroVoo.getSelectedItem().toString();
        VooCtrl cVoo = new VooCtrl();
        FrameListaVoos flv;
        flv = new FrameListaVoos(cVoo.listaVooNumero(numeroVoo));
        flv.setVisible(true);
        flv.setLocation(10, 10);

    }//GEN-LAST:event_btnListarVooActionPerformed

    private void btnListarVoosTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVoosTodosActionPerformed
        VooCtrl cVoo = new VooCtrl();
        FrameListaVoos flv;
        flv = new FrameListaVoos(cVoo.listaVoo());

        flv.setVisible(true);
        flv.setLocation(10, 10);
        

    }//GEN-LAST:event_btnListarVoosTodosActionPerformed

    private void btnSairVooRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairVooRelatorioActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairVooRelatorioActionPerformed

    private void btnLimparVooRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparVooRelatorioActionPerformed
        cbxNumeroVoo.setSelectedIndex(-1);
        
    }//GEN-LAST:event_btnLimparVooRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelRelOpcoesVoo;
    private javax.swing.JPanel PainelVooRelTitulo;
    private javax.swing.JPanel PanelRelVoosBotoes;
    private javax.swing.JButton btnLimparVooRelatorio;
    private javax.swing.JButton btnListarVoo;
    private javax.swing.JButton btnListarVoosTodos;
    private javax.swing.JButton btnSairVooRelatorio;
    private javax.swing.JComboBox cbxNumeroVoo;
    private javax.swing.JLabel lblNomeVoo;
    private javax.swing.JLabel lblRelatorioVooFundo;
    private javax.swing.JLabel lblTelaRelatorioVoo;
    private javax.swing.JLabel lblTituloRelatorioVoo;
    // End of variables declaration//GEN-END:variables
}
